
# This file is automatically generated, you probably don't want to edit this

enhancedBayesianLogisticRegressionOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "enhancedBayesianLogisticRegressionOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            dependent = NULL,
            covariates = NULL,
            factors = NULL,
            modelComparison = TRUE,
            posterior = TRUE,
            apaReport = TRUE, ...) {

            super$initialize(
                package="jaspEnhancedRegression",
                name="enhancedBayesianLogisticRegression",
                requiresData=TRUE,
                ...)

            private$..dependent <- jmvcore::OptionVariable$new(
                "dependent",
                dependent,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"))
            private$..covariates <- jmvcore::OptionVariables$new(
                "covariates",
                covariates,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..factors <- jmvcore::OptionVariables$new(
                "factors",
                factors,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"))
            private$..modelComparison <- jmvcore::OptionBool$new(
                "modelComparison",
                modelComparison,
                default=TRUE)
            private$..posterior <- jmvcore::OptionBool$new(
                "posterior",
                posterior,
                default=TRUE)
            private$..apaReport <- jmvcore::OptionBool$new(
                "apaReport",
                apaReport,
                default=TRUE)

            self$.addOption(private$..dependent)
            self$.addOption(private$..covariates)
            self$.addOption(private$..factors)
            self$.addOption(private$..modelComparison)
            self$.addOption(private$..posterior)
            self$.addOption(private$..apaReport)
        }),
    active = list(
        dependent = function() private$..dependent$value,
        covariates = function() private$..covariates$value,
        factors = function() private$..factors$value,
        modelComparison = function() private$..modelComparison$value,
        posterior = function() private$..posterior$value,
        apaReport = function() private$..apaReport$value),
    private = list(
        ..dependent = NA,
        ..covariates = NA,
        ..factors = NA,
        ..modelComparison = NA,
        ..posterior = NA,
        ..apaReport = NA)
)

enhancedBayesianLogisticRegressionResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "enhancedBayesianLogisticRegressionResults",
    inherit = jmvcore::Group,
    active = list(
        status = function() private$.items[["status"]],
        about = function() private$.items[["about"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="JASP Enhanced Bayesian Logistic Regression")
            self$add(jmvcore::Html$new(
                options=options,
                name="status",
                title="Implementation Status"))
            self$add(jmvcore::Html$new(
                options=options,
                name="about",
                title="About and Citation"))}))

enhancedBayesianLogisticRegressionBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "enhancedBayesianLogisticRegressionBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "jaspEnhancedRegression",
                name = "enhancedBayesianLogisticRegression",
                version = c(0,1,0),
                options = options,
                results = enhancedBayesianLogisticRegressionResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' JASP Enhanced Bayesian Logistic Regression
#'
#' jamovi-native shell for the JASP Bayesian logistic regression analysis.
#' @param data .
#' @param dependent .
#' @param covariates .
#' @param factors .
#' @param modelComparison .
#' @param posterior .
#' @param apaReport .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$status} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$about} \tab \tab \tab \tab \tab a html \cr
#' }
#'
#' @export
enhancedBayesianLogisticRegression <- function(
    data,
    dependent,
    covariates,
    factors,
    modelComparison = TRUE,
    posterior = TRUE,
    apaReport = TRUE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("enhancedBayesianLogisticRegression requires jmvcore to be installed (restart may be required)")

    if ( ! missing(dependent)) dependent <- jmvcore::resolveQuo(jmvcore::enquo(dependent))
    if ( ! missing(covariates)) covariates <- jmvcore::resolveQuo(jmvcore::enquo(covariates))
    if ( ! missing(factors)) factors <- jmvcore::resolveQuo(jmvcore::enquo(factors))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(dependent), dependent, NULL),
            `if`( ! missing(covariates), covariates, NULL),
            `if`( ! missing(factors), factors, NULL))

    for (v in dependent) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    for (v in factors) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])

    options <- enhancedBayesianLogisticRegressionOptions$new(
        dependent = dependent,
        covariates = covariates,
        factors = factors,
        modelComparison = modelComparison,
        posterior = posterior,
        apaReport = apaReport)

    analysis <- enhancedBayesianLogisticRegressionClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

