
# This file is automatically generated, you probably don't want to edit this

enhancedCorrelationOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "enhancedCorrelationOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            variables = NULL,
            partialOut = NULL,
            plots = TRUE,
            apaReport = TRUE, ...) {

            super$initialize(
                package="jaspEnhancedRegression",
                name="enhancedCorrelation",
                requiresData=TRUE,
                ...)

            private$..variables <- jmvcore::OptionVariables$new(
                "variables",
                variables,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..partialOut <- jmvcore::OptionVariables$new(
                "partialOut",
                partialOut,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..plots <- jmvcore::OptionBool$new(
                "plots",
                plots,
                default=TRUE)
            private$..apaReport <- jmvcore::OptionBool$new(
                "apaReport",
                apaReport,
                default=TRUE)

            self$.addOption(private$..variables)
            self$.addOption(private$..partialOut)
            self$.addOption(private$..plots)
            self$.addOption(private$..apaReport)
        }),
    active = list(
        variables = function() private$..variables$value,
        partialOut = function() private$..partialOut$value,
        plots = function() private$..plots$value,
        apaReport = function() private$..apaReport$value),
    private = list(
        ..variables = NA,
        ..partialOut = NA,
        ..plots = NA,
        ..apaReport = NA)
)

enhancedCorrelationResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "enhancedCorrelationResults",
    inherit = jmvcore::Group,
    active = list(
        status = function() private$.items[["status"]],
        about = function() private$.items[["about"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="JASP Enhanced Correlation")
            self$add(jmvcore::Html$new(
                options=options,
                name="status",
                title="Implementation Status"))
            self$add(jmvcore::Html$new(
                options=options,
                name="about",
                title="About and Citation"))}))

enhancedCorrelationBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "enhancedCorrelationBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "jaspEnhancedRegression",
                name = "enhancedCorrelation",
                version = c(0,1,0),
                options = options,
                results = enhancedCorrelationResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' JASP Enhanced Correlation
#'
#' jamovi-native shell for the JASP correlation analysis.
#' @param data .
#' @param variables .
#' @param partialOut .
#' @param plots .
#' @param apaReport .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$status} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$about} \tab \tab \tab \tab \tab a html \cr
#' }
#'
#' @export
enhancedCorrelation <- function(
    data,
    variables,
    partialOut,
    plots = TRUE,
    apaReport = TRUE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("enhancedCorrelation requires jmvcore to be installed (restart may be required)")

    if ( ! missing(variables)) variables <- jmvcore::resolveQuo(jmvcore::enquo(variables))
    if ( ! missing(partialOut)) partialOut <- jmvcore::resolveQuo(jmvcore::enquo(partialOut))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(variables), variables, NULL),
            `if`( ! missing(partialOut), partialOut, NULL))


    options <- enhancedCorrelationOptions$new(
        variables = variables,
        partialOut = partialOut,
        plots = plots,
        apaReport = apaReport)

    analysis <- enhancedCorrelationClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

