
# This file is automatically generated, you probably don't want to edit this

enhancedLinearRegressionOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "enhancedLinearRegressionOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            dependent = NULL,
            covariates = NULL,
            factors = NULL,
            modelFit = TRUE,
            diagnostics = TRUE,
            apaReport = TRUE, ...) {

            super$initialize(
                package="jaspEnhancedRegression",
                name="enhancedLinearRegression",
                requiresData=TRUE,
                ...)

            private$..dependent <- jmvcore::OptionVariable$new(
                "dependent",
                dependent,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..covariates <- jmvcore::OptionVariables$new(
                "covariates",
                covariates,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..factors <- jmvcore::OptionVariables$new(
                "factors",
                factors,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"))
            private$..modelFit <- jmvcore::OptionBool$new(
                "modelFit",
                modelFit,
                default=TRUE)
            private$..diagnostics <- jmvcore::OptionBool$new(
                "diagnostics",
                diagnostics,
                default=TRUE)
            private$..apaReport <- jmvcore::OptionBool$new(
                "apaReport",
                apaReport,
                default=TRUE)

            self$.addOption(private$..dependent)
            self$.addOption(private$..covariates)
            self$.addOption(private$..factors)
            self$.addOption(private$..modelFit)
            self$.addOption(private$..diagnostics)
            self$.addOption(private$..apaReport)
        }),
    active = list(
        dependent = function() private$..dependent$value,
        covariates = function() private$..covariates$value,
        factors = function() private$..factors$value,
        modelFit = function() private$..modelFit$value,
        diagnostics = function() private$..diagnostics$value,
        apaReport = function() private$..apaReport$value),
    private = list(
        ..dependent = NA,
        ..covariates = NA,
        ..factors = NA,
        ..modelFit = NA,
        ..diagnostics = NA,
        ..apaReport = NA)
)

enhancedLinearRegressionResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "enhancedLinearRegressionResults",
    inherit = jmvcore::Group,
    active = list(
        status = function() private$.items[["status"]],
        about = function() private$.items[["about"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="JASP Enhanced Linear Regression")
            self$add(jmvcore::Html$new(
                options=options,
                name="status",
                title="Implementation Status"))
            self$add(jmvcore::Html$new(
                options=options,
                name="about",
                title="About and Citation"))}))

enhancedLinearRegressionBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "enhancedLinearRegressionBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "jaspEnhancedRegression",
                name = "enhancedLinearRegression",
                version = c(0,1,0),
                options = options,
                results = enhancedLinearRegressionResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' JASP Enhanced Linear Regression
#'
#' jamovi-native shell for the JASP linear regression analysis.
#' @param data .
#' @param dependent .
#' @param covariates .
#' @param factors .
#' @param modelFit .
#' @param diagnostics .
#' @param apaReport .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$status} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$about} \tab \tab \tab \tab \tab a html \cr
#' }
#'
#' @export
enhancedLinearRegression <- function(
    data,
    dependent,
    covariates,
    factors,
    modelFit = TRUE,
    diagnostics = TRUE,
    apaReport = TRUE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("enhancedLinearRegression requires jmvcore to be installed (restart may be required)")

    if ( ! missing(dependent)) dependent <- jmvcore::resolveQuo(jmvcore::enquo(dependent))
    if ( ! missing(covariates)) covariates <- jmvcore::resolveQuo(jmvcore::enquo(covariates))
    if ( ! missing(factors)) factors <- jmvcore::resolveQuo(jmvcore::enquo(factors))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(dependent), dependent, NULL),
            `if`( ! missing(covariates), covariates, NULL),
            `if`( ! missing(factors), factors, NULL))

    for (v in factors) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])

    options <- enhancedLinearRegressionOptions$new(
        dependent = dependent,
        covariates = covariates,
        factors = factors,
        modelFit = modelFit,
        diagnostics = diagnostics,
        apaReport = apaReport)

    analysis <- enhancedLinearRegressionClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

