
# This file is automatically generated, you probably don't want to edit this

enhancedBayesianCorrelationOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "enhancedBayesianCorrelationOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            variables = NULL,
            prior = TRUE,
            posterior = TRUE,
            apaReport = TRUE, ...) {

            super$initialize(
                package="jaspEnhancedRegression",
                name="enhancedBayesianCorrelation",
                requiresData=TRUE,
                ...)

            private$..variables <- jmvcore::OptionVariables$new(
                "variables",
                variables,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..prior <- jmvcore::OptionBool$new(
                "prior",
                prior,
                default=TRUE)
            private$..posterior <- jmvcore::OptionBool$new(
                "posterior",
                posterior,
                default=TRUE)
            private$..apaReport <- jmvcore::OptionBool$new(
                "apaReport",
                apaReport,
                default=TRUE)

            self$.addOption(private$..variables)
            self$.addOption(private$..prior)
            self$.addOption(private$..posterior)
            self$.addOption(private$..apaReport)
        }),
    active = list(
        variables = function() private$..variables$value,
        prior = function() private$..prior$value,
        posterior = function() private$..posterior$value,
        apaReport = function() private$..apaReport$value),
    private = list(
        ..variables = NA,
        ..prior = NA,
        ..posterior = NA,
        ..apaReport = NA)
)

enhancedBayesianCorrelationResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "enhancedBayesianCorrelationResults",
    inherit = jmvcore::Group,
    active = list(
        status = function() private$.items[["status"]],
        about = function() private$.items[["about"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="JASP Enhanced Bayesian Correlation")
            self$add(jmvcore::Html$new(
                options=options,
                name="status",
                title="Implementation Status"))
            self$add(jmvcore::Html$new(
                options=options,
                name="about",
                title="About and Citation"))}))

enhancedBayesianCorrelationBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "enhancedBayesianCorrelationBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "jaspEnhancedRegression",
                name = "enhancedBayesianCorrelation",
                version = c(0,1,0),
                options = options,
                results = enhancedBayesianCorrelationResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' JASP Enhanced Bayesian Correlation
#'
#' jamovi-native shell for the JASP Bayesian correlation analysis.
#' @param data .
#' @param variables .
#' @param prior .
#' @param posterior .
#' @param apaReport .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$status} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$about} \tab \tab \tab \tab \tab a html \cr
#' }
#'
#' @export
enhancedBayesianCorrelation <- function(
    data,
    variables,
    prior = TRUE,
    posterior = TRUE,
    apaReport = TRUE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("enhancedBayesianCorrelation requires jmvcore to be installed (restart may be required)")

    if ( ! missing(variables)) variables <- jmvcore::resolveQuo(jmvcore::enquo(variables))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(variables), variables, NULL))


    options <- enhancedBayesianCorrelationOptions$new(
        variables = variables,
        prior = prior,
        posterior = posterior,
        apaReport = apaReport)

    analysis <- enhancedBayesianCorrelationClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

