
# This file is automatically generated, you probably don't want to edit this

enhancedBayesianRepeatedMeasuresAnovaOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "enhancedBayesianRepeatedMeasuresAnovaOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            repeatedMeasures = NULL,
            betweenFactors = NULL,
            modelComparison = TRUE,
            posterior = TRUE,
            apaReport = TRUE, ...) {

            super$initialize(
                package="jaspEnhancedAnova",
                name="enhancedBayesianRepeatedMeasuresAnova",
                requiresData=TRUE,
                ...)

            private$..repeatedMeasures <- jmvcore::OptionVariables$new(
                "repeatedMeasures",
                repeatedMeasures,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..betweenFactors <- jmvcore::OptionVariables$new(
                "betweenFactors",
                betweenFactors,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"))
            private$..modelComparison <- jmvcore::OptionBool$new(
                "modelComparison",
                modelComparison,
                default=TRUE)
            private$..posterior <- jmvcore::OptionBool$new(
                "posterior",
                posterior,
                default=TRUE)
            private$..apaReport <- jmvcore::OptionBool$new(
                "apaReport",
                apaReport,
                default=TRUE)

            self$.addOption(private$..repeatedMeasures)
            self$.addOption(private$..betweenFactors)
            self$.addOption(private$..modelComparison)
            self$.addOption(private$..posterior)
            self$.addOption(private$..apaReport)
        }),
    active = list(
        repeatedMeasures = function() private$..repeatedMeasures$value,
        betweenFactors = function() private$..betweenFactors$value,
        modelComparison = function() private$..modelComparison$value,
        posterior = function() private$..posterior$value,
        apaReport = function() private$..apaReport$value),
    private = list(
        ..repeatedMeasures = NA,
        ..betweenFactors = NA,
        ..modelComparison = NA,
        ..posterior = NA,
        ..apaReport = NA)
)

enhancedBayesianRepeatedMeasuresAnovaResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "enhancedBayesianRepeatedMeasuresAnovaResults",
    inherit = jmvcore::Group,
    active = list(
        status = function() private$.items[["status"]],
        about = function() private$.items[["about"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="JASP Enhanced Bayesian Repeated Measures ANOVA")
            self$add(jmvcore::Html$new(
                options=options,
                name="status",
                title="Implementation Status"))
            self$add(jmvcore::Html$new(
                options=options,
                name="about",
                title="About and Citation"))}))

enhancedBayesianRepeatedMeasuresAnovaBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "enhancedBayesianRepeatedMeasuresAnovaBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "jaspEnhancedAnova",
                name = "enhancedBayesianRepeatedMeasuresAnova",
                version = c(0,1,0),
                options = options,
                results = enhancedBayesianRepeatedMeasuresAnovaResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' JASP Enhanced Bayesian Repeated Measures ANOVA
#'
#' jamovi-native shell for the JASP Bayesian repeated measures ANOVA analysis.
#' @param data .
#' @param repeatedMeasures .
#' @param betweenFactors .
#' @param modelComparison .
#' @param posterior .
#' @param apaReport .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$status} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$about} \tab \tab \tab \tab \tab a html \cr
#' }
#'
#' @export
enhancedBayesianRepeatedMeasuresAnova <- function(
    data,
    repeatedMeasures,
    betweenFactors,
    modelComparison = TRUE,
    posterior = TRUE,
    apaReport = TRUE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("enhancedBayesianRepeatedMeasuresAnova requires jmvcore to be installed (restart may be required)")

    if ( ! missing(repeatedMeasures)) repeatedMeasures <- jmvcore::resolveQuo(jmvcore::enquo(repeatedMeasures))
    if ( ! missing(betweenFactors)) betweenFactors <- jmvcore::resolveQuo(jmvcore::enquo(betweenFactors))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(repeatedMeasures), repeatedMeasures, NULL),
            `if`( ! missing(betweenFactors), betweenFactors, NULL))

    for (v in betweenFactors) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])

    options <- enhancedBayesianRepeatedMeasuresAnovaOptions$new(
        repeatedMeasures = repeatedMeasures,
        betweenFactors = betweenFactors,
        modelComparison = modelComparison,
        posterior = posterior,
        apaReport = apaReport)

    analysis <- enhancedBayesianRepeatedMeasuresAnovaClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

