
# This file is automatically generated, you probably don't want to edit this

enhancedAncovaOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "enhancedAncovaOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            dependent = NULL,
            fixedFactors = NULL,
            covariates = NULL,
            homogeneity = TRUE,
            postHoc = FALSE,
            apaReport = TRUE, ...) {

            super$initialize(
                package="jaspEnhancedAnova",
                name="enhancedAncova",
                requiresData=TRUE,
                ...)

            private$..dependent <- jmvcore::OptionVariable$new(
                "dependent",
                dependent,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..fixedFactors <- jmvcore::OptionVariables$new(
                "fixedFactors",
                fixedFactors,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"))
            private$..covariates <- jmvcore::OptionVariables$new(
                "covariates",
                covariates,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..homogeneity <- jmvcore::OptionBool$new(
                "homogeneity",
                homogeneity,
                default=TRUE)
            private$..postHoc <- jmvcore::OptionBool$new(
                "postHoc",
                postHoc,
                default=FALSE)
            private$..apaReport <- jmvcore::OptionBool$new(
                "apaReport",
                apaReport,
                default=TRUE)

            self$.addOption(private$..dependent)
            self$.addOption(private$..fixedFactors)
            self$.addOption(private$..covariates)
            self$.addOption(private$..homogeneity)
            self$.addOption(private$..postHoc)
            self$.addOption(private$..apaReport)
        }),
    active = list(
        dependent = function() private$..dependent$value,
        fixedFactors = function() private$..fixedFactors$value,
        covariates = function() private$..covariates$value,
        homogeneity = function() private$..homogeneity$value,
        postHoc = function() private$..postHoc$value,
        apaReport = function() private$..apaReport$value),
    private = list(
        ..dependent = NA,
        ..fixedFactors = NA,
        ..covariates = NA,
        ..homogeneity = NA,
        ..postHoc = NA,
        ..apaReport = NA)
)

enhancedAncovaResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "enhancedAncovaResults",
    inherit = jmvcore::Group,
    active = list(
        status = function() private$.items[["status"]],
        about = function() private$.items[["about"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="JASP Enhanced ANCOVA")
            self$add(jmvcore::Html$new(
                options=options,
                name="status",
                title="Implementation Status"))
            self$add(jmvcore::Html$new(
                options=options,
                name="about",
                title="About and Citation"))}))

enhancedAncovaBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "enhancedAncovaBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "jaspEnhancedAnova",
                name = "enhancedAncova",
                version = c(0,1,0),
                options = options,
                results = enhancedAncovaResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' JASP Enhanced ANCOVA
#'
#' jamovi-native shell for the JASP ANCOVA analysis.
#' @param data .
#' @param dependent .
#' @param fixedFactors .
#' @param covariates .
#' @param homogeneity .
#' @param postHoc .
#' @param apaReport .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$status} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$about} \tab \tab \tab \tab \tab a html \cr
#' }
#'
#' @export
enhancedAncova <- function(
    data,
    dependent,
    fixedFactors,
    covariates,
    homogeneity = TRUE,
    postHoc = FALSE,
    apaReport = TRUE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("enhancedAncova requires jmvcore to be installed (restart may be required)")

    if ( ! missing(dependent)) dependent <- jmvcore::resolveQuo(jmvcore::enquo(dependent))
    if ( ! missing(fixedFactors)) fixedFactors <- jmvcore::resolveQuo(jmvcore::enquo(fixedFactors))
    if ( ! missing(covariates)) covariates <- jmvcore::resolveQuo(jmvcore::enquo(covariates))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(dependent), dependent, NULL),
            `if`( ! missing(fixedFactors), fixedFactors, NULL),
            `if`( ! missing(covariates), covariates, NULL))

    for (v in fixedFactors) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])

    options <- enhancedAncovaOptions$new(
        dependent = dependent,
        fixedFactors = fixedFactors,
        covariates = covariates,
        homogeneity = homogeneity,
        postHoc = postHoc,
        apaReport = apaReport)

    analysis <- enhancedAncovaClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

