
# This file is automatically generated, you probably don't want to edit this

enhancedRepeatedMeasuresAnovaOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "enhancedRepeatedMeasuresAnovaOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            rmFactorNames = "Time",
            rmFactorLevels = "Pre, Post",
            rmFactorSpec = "",
            repeatedMeasures = NULL,
            betweenFactors = NULL,
            covariates = NULL,
            groupingFactor = NULL,
            descriptives = TRUE,
            vovkSellke = FALSE,
            omegaSq = TRUE,
            partialOmegaSq = FALSE,
            etaSq = TRUE,
            partialEtaSq = TRUE,
            generalizedEtaSq = TRUE,
            effectSizeCi = FALSE,
            ciWidth = 95,
            automaticModel = TRUE,
            manualModelTerms = "",
            rmMainEffects = TRUE,
            rmInteractions = TRUE,
            rmHigherOrderInteractions = TRUE,
            betweenMainEffects = TRUE,
            betweenInteractions = TRUE,
            mixedInteractions = TRUE,
            sumOfSquares = "type3",
            poolErrorTerms = FALSE,
            mauchly = TRUE,
            sphericityCorrection = "greenhouseGeisser",
            levene = TRUE,
            homogeneityTests = TRUE,
            qqPlotResiduals = FALSE,
            residualDiagnostics = FALSE,
            residualPlots = FALSE,
            influenceDiagnostics = FALSE,
            cooksDistance = FALSE,
            mahalanobisDistance = FALSE,
            rmContrastType = "none",
            contrastCi = TRUE,
            contrastCohensD = FALSE,
            contrastEffectSizes = FALSE,
            contrastPoolError = FALSE,
            rmCustomContrasts = FALSE,
            rmContrastSyntax = "",
            orderRestricted = FALSE,
            orderRestrictedSyntax = "",
            multipleHypothesisModels = FALSE,
            hypothesisModelSpec = "",
            modelComparison = FALSE,
            referenceModel = "unconstrained",
            complementModel = FALSE,
            weightRatios = FALSE,
            relativeWeightsMatrix = FALSE,
            compareCoefficients = FALSE,
            informedHypothesisTests = FALSE,
            bootstrap = FALSE,
            bootstrapSamples = 1000,
            bootstrapCi = FALSE,
            postHoc = FALSE,
            postHocRmFactors = TRUE,
            postHocBetweenFactors = FALSE,
            postHocInteractions = FALSE,
            postHocHolm = TRUE,
            postHocBonferroni = FALSE,
            postHocTukey = FALSE,
            postHocScheffe = FALSE,
            postHocSidak = FALSE,
            postHocCi = TRUE,
            postHocSignificantFlags = TRUE,
            postHocLetters = FALSE,
            postHocEffectSizes = FALSE,
            conditionalComparisons = FALSE,
            postHocPoolError = FALSE,
            descriptivePlots = FALSE,
            descPlotXAxis = NULL,
            descPlotLines = NULL,
            descPlotSeparate = NULL,
            descPlotError = "ci",
            descPlotYAxisLabel = "",
            descPlotAverageUnused = FALSE,
            barPlots = FALSE,
            barPlotXAxis = NULL,
            barPlotSeparate = NULL,
            barPlotError = "ci",
            barPlotFixZero = FALSE,
            barPlotYAxisLabel = "",
            barPlotAverageUnused = FALSE,
            raincloudPlots = FALSE,
            raincloudXAxis = NULL,
            raincloudSeparate = NULL,
            raincloudYAxisLabel = "",
            marginalMeans = FALSE,
            marginalMeanTerms = NULL,
            marginalMeansBootstrap = FALSE,
            marginalMeansCompareZero = FALSE,
            marginalMeansCi = TRUE,
            marginalMeansCiAdjustment = "none",
            marginalMeansPoolError = FALSE,
            simpleEffects = FALSE,
            simpleEffectFactor = NULL,
            moderatorFactor1 = NULL,
            moderatorFactor2 = NULL,
            simpleEffectsTests = TRUE,
            simpleEffectsPairwise = FALSE,
            simpleEffectsEffectSizes = FALSE,
            simpleEffectsCi = TRUE,
            simpleEffectsPoolError = FALSE,
            friedman = FALSE,
            conoverPostHoc = FALSE,
            saveResiduals = FALSE,
            saveRawResiduals = TRUE,
            saveStudentizedResiduals = FALSE,
            saveStandardizedResiduals = FALSE,
            residualColumnName = "rm_anova_residuals",
            savePredictions = FALSE,
            predictionColumnName = "rm_anova_predictions",
            apaReport = TRUE,
            apaTables = TRUE,
            assumptionSummaries = TRUE,
            teachingMode = FALSE,
            explainSphericity = FALSE,
            explainCorrections = FALSE,
            effectSizeInterpretation = FALSE,
            interactionInterpretation = FALSE,
            publicationMode = FALSE,
            publicationFigures = FALSE,
            publicationTables = FALSE,
            exportWord = FALSE,
            exportPdf = FALSE,
            analysisSyntaxExport = FALSE,
            rSyntaxExport = FALSE,
            saveAnalysisConfiguration = FALSE, ...) {

            super$initialize(
                package="jaspEnhancedAnova",
                name="enhancedRepeatedMeasuresAnova",
                requiresData=TRUE,
                ...)

            private$..rmFactorNames <- jmvcore::OptionString$new(
                "rmFactorNames",
                rmFactorNames,
                default="Time")
            private$..rmFactorLevels <- jmvcore::OptionString$new(
                "rmFactorLevels",
                rmFactorLevels,
                default="Pre, Post")
            private$..rmFactorSpec <- jmvcore::OptionString$new(
                "rmFactorSpec",
                rmFactorSpec,
                default="")
            private$..repeatedMeasures <- jmvcore::OptionVariables$new(
                "repeatedMeasures",
                repeatedMeasures,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..betweenFactors <- jmvcore::OptionVariables$new(
                "betweenFactors",
                betweenFactors,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"))
            private$..covariates <- jmvcore::OptionVariables$new(
                "covariates",
                covariates,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..groupingFactor <- jmvcore::OptionVariable$new(
                "groupingFactor",
                groupingFactor,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"))
            private$..descriptives <- jmvcore::OptionBool$new(
                "descriptives",
                descriptives,
                default=TRUE)
            private$..vovkSellke <- jmvcore::OptionBool$new(
                "vovkSellke",
                vovkSellke,
                default=FALSE)
            private$..omegaSq <- jmvcore::OptionBool$new(
                "omegaSq",
                omegaSq,
                default=TRUE)
            private$..partialOmegaSq <- jmvcore::OptionBool$new(
                "partialOmegaSq",
                partialOmegaSq,
                default=FALSE)
            private$..etaSq <- jmvcore::OptionBool$new(
                "etaSq",
                etaSq,
                default=TRUE)
            private$..partialEtaSq <- jmvcore::OptionBool$new(
                "partialEtaSq",
                partialEtaSq,
                default=TRUE)
            private$..generalizedEtaSq <- jmvcore::OptionBool$new(
                "generalizedEtaSq",
                generalizedEtaSq,
                default=TRUE)
            private$..effectSizeCi <- jmvcore::OptionBool$new(
                "effectSizeCi",
                effectSizeCi,
                default=FALSE)
            private$..ciWidth <- jmvcore::OptionNumber$new(
                "ciWidth",
                ciWidth,
                min=50,
                max=99.9,
                default=95)
            private$..automaticModel <- jmvcore::OptionBool$new(
                "automaticModel",
                automaticModel,
                default=TRUE)
            private$..manualModelTerms <- jmvcore::OptionString$new(
                "manualModelTerms",
                manualModelTerms,
                default="")
            private$..rmMainEffects <- jmvcore::OptionBool$new(
                "rmMainEffects",
                rmMainEffects,
                default=TRUE)
            private$..rmInteractions <- jmvcore::OptionBool$new(
                "rmInteractions",
                rmInteractions,
                default=TRUE)
            private$..rmHigherOrderInteractions <- jmvcore::OptionBool$new(
                "rmHigherOrderInteractions",
                rmHigherOrderInteractions,
                default=TRUE)
            private$..betweenMainEffects <- jmvcore::OptionBool$new(
                "betweenMainEffects",
                betweenMainEffects,
                default=TRUE)
            private$..betweenInteractions <- jmvcore::OptionBool$new(
                "betweenInteractions",
                betweenInteractions,
                default=TRUE)
            private$..mixedInteractions <- jmvcore::OptionBool$new(
                "mixedInteractions",
                mixedInteractions,
                default=TRUE)
            private$..sumOfSquares <- jmvcore::OptionList$new(
                "sumOfSquares",
                sumOfSquares,
                options=list(
                    "type1",
                    "type2",
                    "type3"),
                default="type3")
            private$..poolErrorTerms <- jmvcore::OptionBool$new(
                "poolErrorTerms",
                poolErrorTerms,
                default=FALSE)
            private$..mauchly <- jmvcore::OptionBool$new(
                "mauchly",
                mauchly,
                default=TRUE)
            private$..sphericityCorrection <- jmvcore::OptionList$new(
                "sphericityCorrection",
                sphericityCorrection,
                options=list(
                    "none",
                    "greenhouseGeisser",
                    "huynhFeldt"),
                default="greenhouseGeisser")
            private$..levene <- jmvcore::OptionBool$new(
                "levene",
                levene,
                default=TRUE)
            private$..homogeneityTests <- jmvcore::OptionBool$new(
                "homogeneityTests",
                homogeneityTests,
                default=TRUE)
            private$..qqPlotResiduals <- jmvcore::OptionBool$new(
                "qqPlotResiduals",
                qqPlotResiduals,
                default=FALSE)
            private$..residualDiagnostics <- jmvcore::OptionBool$new(
                "residualDiagnostics",
                residualDiagnostics,
                default=FALSE)
            private$..residualPlots <- jmvcore::OptionBool$new(
                "residualPlots",
                residualPlots,
                default=FALSE)
            private$..influenceDiagnostics <- jmvcore::OptionBool$new(
                "influenceDiagnostics",
                influenceDiagnostics,
                default=FALSE)
            private$..cooksDistance <- jmvcore::OptionBool$new(
                "cooksDistance",
                cooksDistance,
                default=FALSE)
            private$..mahalanobisDistance <- jmvcore::OptionBool$new(
                "mahalanobisDistance",
                mahalanobisDistance,
                default=FALSE)
            private$..rmContrastType <- jmvcore::OptionList$new(
                "rmContrastType",
                rmContrastType,
                options=list(
                    "none",
                    "simple",
                    "deviation",
                    "difference",
                    "helmert",
                    "polynomial",
                    "repeated"),
                default="none")
            private$..contrastCi <- jmvcore::OptionBool$new(
                "contrastCi",
                contrastCi,
                default=TRUE)
            private$..contrastCohensD <- jmvcore::OptionBool$new(
                "contrastCohensD",
                contrastCohensD,
                default=FALSE)
            private$..contrastEffectSizes <- jmvcore::OptionBool$new(
                "contrastEffectSizes",
                contrastEffectSizes,
                default=FALSE)
            private$..contrastPoolError <- jmvcore::OptionBool$new(
                "contrastPoolError",
                contrastPoolError,
                default=FALSE)
            private$..rmCustomContrasts <- jmvcore::OptionBool$new(
                "rmCustomContrasts",
                rmCustomContrasts,
                default=FALSE)
            private$..rmContrastSyntax <- jmvcore::OptionString$new(
                "rmContrastSyntax",
                rmContrastSyntax,
                default="")
            private$..orderRestricted <- jmvcore::OptionBool$new(
                "orderRestricted",
                orderRestricted,
                default=FALSE)
            private$..orderRestrictedSyntax <- jmvcore::OptionString$new(
                "orderRestrictedSyntax",
                orderRestrictedSyntax,
                default="")
            private$..multipleHypothesisModels <- jmvcore::OptionBool$new(
                "multipleHypothesisModels",
                multipleHypothesisModels,
                default=FALSE)
            private$..hypothesisModelSpec <- jmvcore::OptionString$new(
                "hypothesisModelSpec",
                hypothesisModelSpec,
                default="")
            private$..modelComparison <- jmvcore::OptionBool$new(
                "modelComparison",
                modelComparison,
                default=FALSE)
            private$..referenceModel <- jmvcore::OptionList$new(
                "referenceModel",
                referenceModel,
                options=list(
                    "unconstrained",
                    "complement",
                    "nullModel"),
                default="unconstrained")
            private$..complementModel <- jmvcore::OptionBool$new(
                "complementModel",
                complementModel,
                default=FALSE)
            private$..weightRatios <- jmvcore::OptionBool$new(
                "weightRatios",
                weightRatios,
                default=FALSE)
            private$..relativeWeightsMatrix <- jmvcore::OptionBool$new(
                "relativeWeightsMatrix",
                relativeWeightsMatrix,
                default=FALSE)
            private$..compareCoefficients <- jmvcore::OptionBool$new(
                "compareCoefficients",
                compareCoefficients,
                default=FALSE)
            private$..informedHypothesisTests <- jmvcore::OptionBool$new(
                "informedHypothesisTests",
                informedHypothesisTests,
                default=FALSE)
            private$..bootstrap <- jmvcore::OptionBool$new(
                "bootstrap",
                bootstrap,
                default=FALSE)
            private$..bootstrapSamples <- jmvcore::OptionInteger$new(
                "bootstrapSamples",
                bootstrapSamples,
                min=100,
                max=100000,
                default=1000)
            private$..bootstrapCi <- jmvcore::OptionBool$new(
                "bootstrapCi",
                bootstrapCi,
                default=FALSE)
            private$..postHoc <- jmvcore::OptionBool$new(
                "postHoc",
                postHoc,
                default=FALSE)
            private$..postHocRmFactors <- jmvcore::OptionBool$new(
                "postHocRmFactors",
                postHocRmFactors,
                default=TRUE)
            private$..postHocBetweenFactors <- jmvcore::OptionBool$new(
                "postHocBetweenFactors",
                postHocBetweenFactors,
                default=FALSE)
            private$..postHocInteractions <- jmvcore::OptionBool$new(
                "postHocInteractions",
                postHocInteractions,
                default=FALSE)
            private$..postHocHolm <- jmvcore::OptionBool$new(
                "postHocHolm",
                postHocHolm,
                default=TRUE)
            private$..postHocBonferroni <- jmvcore::OptionBool$new(
                "postHocBonferroni",
                postHocBonferroni,
                default=FALSE)
            private$..postHocTukey <- jmvcore::OptionBool$new(
                "postHocTukey",
                postHocTukey,
                default=FALSE)
            private$..postHocScheffe <- jmvcore::OptionBool$new(
                "postHocScheffe",
                postHocScheffe,
                default=FALSE)
            private$..postHocSidak <- jmvcore::OptionBool$new(
                "postHocSidak",
                postHocSidak,
                default=FALSE)
            private$..postHocCi <- jmvcore::OptionBool$new(
                "postHocCi",
                postHocCi,
                default=TRUE)
            private$..postHocSignificantFlags <- jmvcore::OptionBool$new(
                "postHocSignificantFlags",
                postHocSignificantFlags,
                default=TRUE)
            private$..postHocLetters <- jmvcore::OptionBool$new(
                "postHocLetters",
                postHocLetters,
                default=FALSE)
            private$..postHocEffectSizes <- jmvcore::OptionBool$new(
                "postHocEffectSizes",
                postHocEffectSizes,
                default=FALSE)
            private$..conditionalComparisons <- jmvcore::OptionBool$new(
                "conditionalComparisons",
                conditionalComparisons,
                default=FALSE)
            private$..postHocPoolError <- jmvcore::OptionBool$new(
                "postHocPoolError",
                postHocPoolError,
                default=FALSE)
            private$..descriptivePlots <- jmvcore::OptionBool$new(
                "descriptivePlots",
                descriptivePlots,
                default=FALSE)
            private$..descPlotXAxis <- jmvcore::OptionVariable$new(
                "descPlotXAxis",
                descPlotXAxis,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"))
            private$..descPlotLines <- jmvcore::OptionVariable$new(
                "descPlotLines",
                descPlotLines,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"))
            private$..descPlotSeparate <- jmvcore::OptionVariable$new(
                "descPlotSeparate",
                descPlotSeparate,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"))
            private$..descPlotError <- jmvcore::OptionList$new(
                "descPlotError",
                descPlotError,
                options=list(
                    "ci",
                    "se",
                    "normalized"),
                default="ci")
            private$..descPlotYAxisLabel <- jmvcore::OptionString$new(
                "descPlotYAxisLabel",
                descPlotYAxisLabel,
                default="")
            private$..descPlotAverageUnused <- jmvcore::OptionBool$new(
                "descPlotAverageUnused",
                descPlotAverageUnused,
                default=FALSE)
            private$..barPlots <- jmvcore::OptionBool$new(
                "barPlots",
                barPlots,
                default=FALSE)
            private$..barPlotXAxis <- jmvcore::OptionVariable$new(
                "barPlotXAxis",
                barPlotXAxis,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"))
            private$..barPlotSeparate <- jmvcore::OptionVariable$new(
                "barPlotSeparate",
                barPlotSeparate,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"))
            private$..barPlotError <- jmvcore::OptionList$new(
                "barPlotError",
                barPlotError,
                options=list(
                    "ci",
                    "se",
                    "normalized"),
                default="ci")
            private$..barPlotFixZero <- jmvcore::OptionBool$new(
                "barPlotFixZero",
                barPlotFixZero,
                default=FALSE)
            private$..barPlotYAxisLabel <- jmvcore::OptionString$new(
                "barPlotYAxisLabel",
                barPlotYAxisLabel,
                default="")
            private$..barPlotAverageUnused <- jmvcore::OptionBool$new(
                "barPlotAverageUnused",
                barPlotAverageUnused,
                default=FALSE)
            private$..raincloudPlots <- jmvcore::OptionBool$new(
                "raincloudPlots",
                raincloudPlots,
                default=FALSE)
            private$..raincloudXAxis <- jmvcore::OptionVariable$new(
                "raincloudXAxis",
                raincloudXAxis,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"))
            private$..raincloudSeparate <- jmvcore::OptionVariable$new(
                "raincloudSeparate",
                raincloudSeparate,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"))
            private$..raincloudYAxisLabel <- jmvcore::OptionString$new(
                "raincloudYAxisLabel",
                raincloudYAxisLabel,
                default="")
            private$..marginalMeans <- jmvcore::OptionBool$new(
                "marginalMeans",
                marginalMeans,
                default=FALSE)
            private$..marginalMeanTerms <- jmvcore::OptionVariables$new(
                "marginalMeanTerms",
                marginalMeanTerms,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"))
            private$..marginalMeansBootstrap <- jmvcore::OptionBool$new(
                "marginalMeansBootstrap",
                marginalMeansBootstrap,
                default=FALSE)
            private$..marginalMeansCompareZero <- jmvcore::OptionBool$new(
                "marginalMeansCompareZero",
                marginalMeansCompareZero,
                default=FALSE)
            private$..marginalMeansCi <- jmvcore::OptionBool$new(
                "marginalMeansCi",
                marginalMeansCi,
                default=TRUE)
            private$..marginalMeansCiAdjustment <- jmvcore::OptionList$new(
                "marginalMeansCiAdjustment",
                marginalMeansCiAdjustment,
                options=list(
                    "none",
                    "bonferroni",
                    "holm",
                    "sidak",
                    "tukey"),
                default="none")
            private$..marginalMeansPoolError <- jmvcore::OptionBool$new(
                "marginalMeansPoolError",
                marginalMeansPoolError,
                default=FALSE)
            private$..simpleEffects <- jmvcore::OptionBool$new(
                "simpleEffects",
                simpleEffects,
                default=FALSE)
            private$..simpleEffectFactor <- jmvcore::OptionVariable$new(
                "simpleEffectFactor",
                simpleEffectFactor,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"))
            private$..moderatorFactor1 <- jmvcore::OptionVariable$new(
                "moderatorFactor1",
                moderatorFactor1,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"))
            private$..moderatorFactor2 <- jmvcore::OptionVariable$new(
                "moderatorFactor2",
                moderatorFactor2,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"))
            private$..simpleEffectsTests <- jmvcore::OptionBool$new(
                "simpleEffectsTests",
                simpleEffectsTests,
                default=TRUE)
            private$..simpleEffectsPairwise <- jmvcore::OptionBool$new(
                "simpleEffectsPairwise",
                simpleEffectsPairwise,
                default=FALSE)
            private$..simpleEffectsEffectSizes <- jmvcore::OptionBool$new(
                "simpleEffectsEffectSizes",
                simpleEffectsEffectSizes,
                default=FALSE)
            private$..simpleEffectsCi <- jmvcore::OptionBool$new(
                "simpleEffectsCi",
                simpleEffectsCi,
                default=TRUE)
            private$..simpleEffectsPoolError <- jmvcore::OptionBool$new(
                "simpleEffectsPoolError",
                simpleEffectsPoolError,
                default=FALSE)
            private$..friedman <- jmvcore::OptionBool$new(
                "friedman",
                friedman,
                default=FALSE)
            private$..conoverPostHoc <- jmvcore::OptionBool$new(
                "conoverPostHoc",
                conoverPostHoc,
                default=FALSE)
            private$..saveResiduals <- jmvcore::OptionBool$new(
                "saveResiduals",
                saveResiduals,
                default=FALSE)
            private$..saveRawResiduals <- jmvcore::OptionBool$new(
                "saveRawResiduals",
                saveRawResiduals,
                default=TRUE)
            private$..saveStudentizedResiduals <- jmvcore::OptionBool$new(
                "saveStudentizedResiduals",
                saveStudentizedResiduals,
                default=FALSE)
            private$..saveStandardizedResiduals <- jmvcore::OptionBool$new(
                "saveStandardizedResiduals",
                saveStandardizedResiduals,
                default=FALSE)
            private$..residualColumnName <- jmvcore::OptionString$new(
                "residualColumnName",
                residualColumnName,
                default="rm_anova_residuals")
            private$..rmResidsOV <- jmvcore::OptionOutput$new(
                "rmResidsOV")
            private$..rmStudentizedResidsOV <- jmvcore::OptionOutput$new(
                "rmStudentizedResidsOV")
            private$..rmStandardizedResidsOV <- jmvcore::OptionOutput$new(
                "rmStandardizedResidsOV")
            private$..savePredictions <- jmvcore::OptionBool$new(
                "savePredictions",
                savePredictions,
                default=FALSE)
            private$..predictionColumnName <- jmvcore::OptionString$new(
                "predictionColumnName",
                predictionColumnName,
                default="rm_anova_predictions")
            private$..rmPredictOV <- jmvcore::OptionOutput$new(
                "rmPredictOV")
            private$..apaReport <- jmvcore::OptionBool$new(
                "apaReport",
                apaReport,
                default=TRUE)
            private$..apaTables <- jmvcore::OptionBool$new(
                "apaTables",
                apaTables,
                default=TRUE)
            private$..assumptionSummaries <- jmvcore::OptionBool$new(
                "assumptionSummaries",
                assumptionSummaries,
                default=TRUE)
            private$..teachingMode <- jmvcore::OptionBool$new(
                "teachingMode",
                teachingMode,
                default=FALSE)
            private$..explainSphericity <- jmvcore::OptionBool$new(
                "explainSphericity",
                explainSphericity,
                default=FALSE)
            private$..explainCorrections <- jmvcore::OptionBool$new(
                "explainCorrections",
                explainCorrections,
                default=FALSE)
            private$..effectSizeInterpretation <- jmvcore::OptionBool$new(
                "effectSizeInterpretation",
                effectSizeInterpretation,
                default=FALSE)
            private$..interactionInterpretation <- jmvcore::OptionBool$new(
                "interactionInterpretation",
                interactionInterpretation,
                default=FALSE)
            private$..publicationMode <- jmvcore::OptionBool$new(
                "publicationMode",
                publicationMode,
                default=FALSE)
            private$..publicationFigures <- jmvcore::OptionBool$new(
                "publicationFigures",
                publicationFigures,
                default=FALSE)
            private$..publicationTables <- jmvcore::OptionBool$new(
                "publicationTables",
                publicationTables,
                default=FALSE)
            private$..exportWord <- jmvcore::OptionBool$new(
                "exportWord",
                exportWord,
                default=FALSE)
            private$..exportPdf <- jmvcore::OptionBool$new(
                "exportPdf",
                exportPdf,
                default=FALSE)
            private$..analysisSyntaxExport <- jmvcore::OptionBool$new(
                "analysisSyntaxExport",
                analysisSyntaxExport,
                default=FALSE)
            private$..rSyntaxExport <- jmvcore::OptionBool$new(
                "rSyntaxExport",
                rSyntaxExport,
                default=FALSE)
            private$..saveAnalysisConfiguration <- jmvcore::OptionBool$new(
                "saveAnalysisConfiguration",
                saveAnalysisConfiguration,
                default=FALSE)

            self$.addOption(private$..rmFactorNames)
            self$.addOption(private$..rmFactorLevels)
            self$.addOption(private$..rmFactorSpec)
            self$.addOption(private$..repeatedMeasures)
            self$.addOption(private$..betweenFactors)
            self$.addOption(private$..covariates)
            self$.addOption(private$..groupingFactor)
            self$.addOption(private$..descriptives)
            self$.addOption(private$..vovkSellke)
            self$.addOption(private$..omegaSq)
            self$.addOption(private$..partialOmegaSq)
            self$.addOption(private$..etaSq)
            self$.addOption(private$..partialEtaSq)
            self$.addOption(private$..generalizedEtaSq)
            self$.addOption(private$..effectSizeCi)
            self$.addOption(private$..ciWidth)
            self$.addOption(private$..automaticModel)
            self$.addOption(private$..manualModelTerms)
            self$.addOption(private$..rmMainEffects)
            self$.addOption(private$..rmInteractions)
            self$.addOption(private$..rmHigherOrderInteractions)
            self$.addOption(private$..betweenMainEffects)
            self$.addOption(private$..betweenInteractions)
            self$.addOption(private$..mixedInteractions)
            self$.addOption(private$..sumOfSquares)
            self$.addOption(private$..poolErrorTerms)
            self$.addOption(private$..mauchly)
            self$.addOption(private$..sphericityCorrection)
            self$.addOption(private$..levene)
            self$.addOption(private$..homogeneityTests)
            self$.addOption(private$..qqPlotResiduals)
            self$.addOption(private$..residualDiagnostics)
            self$.addOption(private$..residualPlots)
            self$.addOption(private$..influenceDiagnostics)
            self$.addOption(private$..cooksDistance)
            self$.addOption(private$..mahalanobisDistance)
            self$.addOption(private$..rmContrastType)
            self$.addOption(private$..contrastCi)
            self$.addOption(private$..contrastCohensD)
            self$.addOption(private$..contrastEffectSizes)
            self$.addOption(private$..contrastPoolError)
            self$.addOption(private$..rmCustomContrasts)
            self$.addOption(private$..rmContrastSyntax)
            self$.addOption(private$..orderRestricted)
            self$.addOption(private$..orderRestrictedSyntax)
            self$.addOption(private$..multipleHypothesisModels)
            self$.addOption(private$..hypothesisModelSpec)
            self$.addOption(private$..modelComparison)
            self$.addOption(private$..referenceModel)
            self$.addOption(private$..complementModel)
            self$.addOption(private$..weightRatios)
            self$.addOption(private$..relativeWeightsMatrix)
            self$.addOption(private$..compareCoefficients)
            self$.addOption(private$..informedHypothesisTests)
            self$.addOption(private$..bootstrap)
            self$.addOption(private$..bootstrapSamples)
            self$.addOption(private$..bootstrapCi)
            self$.addOption(private$..postHoc)
            self$.addOption(private$..postHocRmFactors)
            self$.addOption(private$..postHocBetweenFactors)
            self$.addOption(private$..postHocInteractions)
            self$.addOption(private$..postHocHolm)
            self$.addOption(private$..postHocBonferroni)
            self$.addOption(private$..postHocTukey)
            self$.addOption(private$..postHocScheffe)
            self$.addOption(private$..postHocSidak)
            self$.addOption(private$..postHocCi)
            self$.addOption(private$..postHocSignificantFlags)
            self$.addOption(private$..postHocLetters)
            self$.addOption(private$..postHocEffectSizes)
            self$.addOption(private$..conditionalComparisons)
            self$.addOption(private$..postHocPoolError)
            self$.addOption(private$..descriptivePlots)
            self$.addOption(private$..descPlotXAxis)
            self$.addOption(private$..descPlotLines)
            self$.addOption(private$..descPlotSeparate)
            self$.addOption(private$..descPlotError)
            self$.addOption(private$..descPlotYAxisLabel)
            self$.addOption(private$..descPlotAverageUnused)
            self$.addOption(private$..barPlots)
            self$.addOption(private$..barPlotXAxis)
            self$.addOption(private$..barPlotSeparate)
            self$.addOption(private$..barPlotError)
            self$.addOption(private$..barPlotFixZero)
            self$.addOption(private$..barPlotYAxisLabel)
            self$.addOption(private$..barPlotAverageUnused)
            self$.addOption(private$..raincloudPlots)
            self$.addOption(private$..raincloudXAxis)
            self$.addOption(private$..raincloudSeparate)
            self$.addOption(private$..raincloudYAxisLabel)
            self$.addOption(private$..marginalMeans)
            self$.addOption(private$..marginalMeanTerms)
            self$.addOption(private$..marginalMeansBootstrap)
            self$.addOption(private$..marginalMeansCompareZero)
            self$.addOption(private$..marginalMeansCi)
            self$.addOption(private$..marginalMeansCiAdjustment)
            self$.addOption(private$..marginalMeansPoolError)
            self$.addOption(private$..simpleEffects)
            self$.addOption(private$..simpleEffectFactor)
            self$.addOption(private$..moderatorFactor1)
            self$.addOption(private$..moderatorFactor2)
            self$.addOption(private$..simpleEffectsTests)
            self$.addOption(private$..simpleEffectsPairwise)
            self$.addOption(private$..simpleEffectsEffectSizes)
            self$.addOption(private$..simpleEffectsCi)
            self$.addOption(private$..simpleEffectsPoolError)
            self$.addOption(private$..friedman)
            self$.addOption(private$..conoverPostHoc)
            self$.addOption(private$..saveResiduals)
            self$.addOption(private$..saveRawResiduals)
            self$.addOption(private$..saveStudentizedResiduals)
            self$.addOption(private$..saveStandardizedResiduals)
            self$.addOption(private$..residualColumnName)
            self$.addOption(private$..rmResidsOV)
            self$.addOption(private$..rmStudentizedResidsOV)
            self$.addOption(private$..rmStandardizedResidsOV)
            self$.addOption(private$..savePredictions)
            self$.addOption(private$..predictionColumnName)
            self$.addOption(private$..rmPredictOV)
            self$.addOption(private$..apaReport)
            self$.addOption(private$..apaTables)
            self$.addOption(private$..assumptionSummaries)
            self$.addOption(private$..teachingMode)
            self$.addOption(private$..explainSphericity)
            self$.addOption(private$..explainCorrections)
            self$.addOption(private$..effectSizeInterpretation)
            self$.addOption(private$..interactionInterpretation)
            self$.addOption(private$..publicationMode)
            self$.addOption(private$..publicationFigures)
            self$.addOption(private$..publicationTables)
            self$.addOption(private$..exportWord)
            self$.addOption(private$..exportPdf)
            self$.addOption(private$..analysisSyntaxExport)
            self$.addOption(private$..rSyntaxExport)
            self$.addOption(private$..saveAnalysisConfiguration)
        }),
    active = list(
        rmFactorNames = function() private$..rmFactorNames$value,
        rmFactorLevels = function() private$..rmFactorLevels$value,
        rmFactorSpec = function() private$..rmFactorSpec$value,
        repeatedMeasures = function() private$..repeatedMeasures$value,
        betweenFactors = function() private$..betweenFactors$value,
        covariates = function() private$..covariates$value,
        groupingFactor = function() private$..groupingFactor$value,
        descriptives = function() private$..descriptives$value,
        vovkSellke = function() private$..vovkSellke$value,
        omegaSq = function() private$..omegaSq$value,
        partialOmegaSq = function() private$..partialOmegaSq$value,
        etaSq = function() private$..etaSq$value,
        partialEtaSq = function() private$..partialEtaSq$value,
        generalizedEtaSq = function() private$..generalizedEtaSq$value,
        effectSizeCi = function() private$..effectSizeCi$value,
        ciWidth = function() private$..ciWidth$value,
        automaticModel = function() private$..automaticModel$value,
        manualModelTerms = function() private$..manualModelTerms$value,
        rmMainEffects = function() private$..rmMainEffects$value,
        rmInteractions = function() private$..rmInteractions$value,
        rmHigherOrderInteractions = function() private$..rmHigherOrderInteractions$value,
        betweenMainEffects = function() private$..betweenMainEffects$value,
        betweenInteractions = function() private$..betweenInteractions$value,
        mixedInteractions = function() private$..mixedInteractions$value,
        sumOfSquares = function() private$..sumOfSquares$value,
        poolErrorTerms = function() private$..poolErrorTerms$value,
        mauchly = function() private$..mauchly$value,
        sphericityCorrection = function() private$..sphericityCorrection$value,
        levene = function() private$..levene$value,
        homogeneityTests = function() private$..homogeneityTests$value,
        qqPlotResiduals = function() private$..qqPlotResiduals$value,
        residualDiagnostics = function() private$..residualDiagnostics$value,
        residualPlots = function() private$..residualPlots$value,
        influenceDiagnostics = function() private$..influenceDiagnostics$value,
        cooksDistance = function() private$..cooksDistance$value,
        mahalanobisDistance = function() private$..mahalanobisDistance$value,
        rmContrastType = function() private$..rmContrastType$value,
        contrastCi = function() private$..contrastCi$value,
        contrastCohensD = function() private$..contrastCohensD$value,
        contrastEffectSizes = function() private$..contrastEffectSizes$value,
        contrastPoolError = function() private$..contrastPoolError$value,
        rmCustomContrasts = function() private$..rmCustomContrasts$value,
        rmContrastSyntax = function() private$..rmContrastSyntax$value,
        orderRestricted = function() private$..orderRestricted$value,
        orderRestrictedSyntax = function() private$..orderRestrictedSyntax$value,
        multipleHypothesisModels = function() private$..multipleHypothesisModels$value,
        hypothesisModelSpec = function() private$..hypothesisModelSpec$value,
        modelComparison = function() private$..modelComparison$value,
        referenceModel = function() private$..referenceModel$value,
        complementModel = function() private$..complementModel$value,
        weightRatios = function() private$..weightRatios$value,
        relativeWeightsMatrix = function() private$..relativeWeightsMatrix$value,
        compareCoefficients = function() private$..compareCoefficients$value,
        informedHypothesisTests = function() private$..informedHypothesisTests$value,
        bootstrap = function() private$..bootstrap$value,
        bootstrapSamples = function() private$..bootstrapSamples$value,
        bootstrapCi = function() private$..bootstrapCi$value,
        postHoc = function() private$..postHoc$value,
        postHocRmFactors = function() private$..postHocRmFactors$value,
        postHocBetweenFactors = function() private$..postHocBetweenFactors$value,
        postHocInteractions = function() private$..postHocInteractions$value,
        postHocHolm = function() private$..postHocHolm$value,
        postHocBonferroni = function() private$..postHocBonferroni$value,
        postHocTukey = function() private$..postHocTukey$value,
        postHocScheffe = function() private$..postHocScheffe$value,
        postHocSidak = function() private$..postHocSidak$value,
        postHocCi = function() private$..postHocCi$value,
        postHocSignificantFlags = function() private$..postHocSignificantFlags$value,
        postHocLetters = function() private$..postHocLetters$value,
        postHocEffectSizes = function() private$..postHocEffectSizes$value,
        conditionalComparisons = function() private$..conditionalComparisons$value,
        postHocPoolError = function() private$..postHocPoolError$value,
        descriptivePlots = function() private$..descriptivePlots$value,
        descPlotXAxis = function() private$..descPlotXAxis$value,
        descPlotLines = function() private$..descPlotLines$value,
        descPlotSeparate = function() private$..descPlotSeparate$value,
        descPlotError = function() private$..descPlotError$value,
        descPlotYAxisLabel = function() private$..descPlotYAxisLabel$value,
        descPlotAverageUnused = function() private$..descPlotAverageUnused$value,
        barPlots = function() private$..barPlots$value,
        barPlotXAxis = function() private$..barPlotXAxis$value,
        barPlotSeparate = function() private$..barPlotSeparate$value,
        barPlotError = function() private$..barPlotError$value,
        barPlotFixZero = function() private$..barPlotFixZero$value,
        barPlotYAxisLabel = function() private$..barPlotYAxisLabel$value,
        barPlotAverageUnused = function() private$..barPlotAverageUnused$value,
        raincloudPlots = function() private$..raincloudPlots$value,
        raincloudXAxis = function() private$..raincloudXAxis$value,
        raincloudSeparate = function() private$..raincloudSeparate$value,
        raincloudYAxisLabel = function() private$..raincloudYAxisLabel$value,
        marginalMeans = function() private$..marginalMeans$value,
        marginalMeanTerms = function() private$..marginalMeanTerms$value,
        marginalMeansBootstrap = function() private$..marginalMeansBootstrap$value,
        marginalMeansCompareZero = function() private$..marginalMeansCompareZero$value,
        marginalMeansCi = function() private$..marginalMeansCi$value,
        marginalMeansCiAdjustment = function() private$..marginalMeansCiAdjustment$value,
        marginalMeansPoolError = function() private$..marginalMeansPoolError$value,
        simpleEffects = function() private$..simpleEffects$value,
        simpleEffectFactor = function() private$..simpleEffectFactor$value,
        moderatorFactor1 = function() private$..moderatorFactor1$value,
        moderatorFactor2 = function() private$..moderatorFactor2$value,
        simpleEffectsTests = function() private$..simpleEffectsTests$value,
        simpleEffectsPairwise = function() private$..simpleEffectsPairwise$value,
        simpleEffectsEffectSizes = function() private$..simpleEffectsEffectSizes$value,
        simpleEffectsCi = function() private$..simpleEffectsCi$value,
        simpleEffectsPoolError = function() private$..simpleEffectsPoolError$value,
        friedman = function() private$..friedman$value,
        conoverPostHoc = function() private$..conoverPostHoc$value,
        saveResiduals = function() private$..saveResiduals$value,
        saveRawResiduals = function() private$..saveRawResiduals$value,
        saveStudentizedResiduals = function() private$..saveStudentizedResiduals$value,
        saveStandardizedResiduals = function() private$..saveStandardizedResiduals$value,
        residualColumnName = function() private$..residualColumnName$value,
        rmResidsOV = function() private$..rmResidsOV$value,
        rmStudentizedResidsOV = function() private$..rmStudentizedResidsOV$value,
        rmStandardizedResidsOV = function() private$..rmStandardizedResidsOV$value,
        savePredictions = function() private$..savePredictions$value,
        predictionColumnName = function() private$..predictionColumnName$value,
        rmPredictOV = function() private$..rmPredictOV$value,
        apaReport = function() private$..apaReport$value,
        apaTables = function() private$..apaTables$value,
        assumptionSummaries = function() private$..assumptionSummaries$value,
        teachingMode = function() private$..teachingMode$value,
        explainSphericity = function() private$..explainSphericity$value,
        explainCorrections = function() private$..explainCorrections$value,
        effectSizeInterpretation = function() private$..effectSizeInterpretation$value,
        interactionInterpretation = function() private$..interactionInterpretation$value,
        publicationMode = function() private$..publicationMode$value,
        publicationFigures = function() private$..publicationFigures$value,
        publicationTables = function() private$..publicationTables$value,
        exportWord = function() private$..exportWord$value,
        exportPdf = function() private$..exportPdf$value,
        analysisSyntaxExport = function() private$..analysisSyntaxExport$value,
        rSyntaxExport = function() private$..rSyntaxExport$value,
        saveAnalysisConfiguration = function() private$..saveAnalysisConfiguration$value),
    private = list(
        ..rmFactorNames = NA,
        ..rmFactorLevels = NA,
        ..rmFactorSpec = NA,
        ..repeatedMeasures = NA,
        ..betweenFactors = NA,
        ..covariates = NA,
        ..groupingFactor = NA,
        ..descriptives = NA,
        ..vovkSellke = NA,
        ..omegaSq = NA,
        ..partialOmegaSq = NA,
        ..etaSq = NA,
        ..partialEtaSq = NA,
        ..generalizedEtaSq = NA,
        ..effectSizeCi = NA,
        ..ciWidth = NA,
        ..automaticModel = NA,
        ..manualModelTerms = NA,
        ..rmMainEffects = NA,
        ..rmInteractions = NA,
        ..rmHigherOrderInteractions = NA,
        ..betweenMainEffects = NA,
        ..betweenInteractions = NA,
        ..mixedInteractions = NA,
        ..sumOfSquares = NA,
        ..poolErrorTerms = NA,
        ..mauchly = NA,
        ..sphericityCorrection = NA,
        ..levene = NA,
        ..homogeneityTests = NA,
        ..qqPlotResiduals = NA,
        ..residualDiagnostics = NA,
        ..residualPlots = NA,
        ..influenceDiagnostics = NA,
        ..cooksDistance = NA,
        ..mahalanobisDistance = NA,
        ..rmContrastType = NA,
        ..contrastCi = NA,
        ..contrastCohensD = NA,
        ..contrastEffectSizes = NA,
        ..contrastPoolError = NA,
        ..rmCustomContrasts = NA,
        ..rmContrastSyntax = NA,
        ..orderRestricted = NA,
        ..orderRestrictedSyntax = NA,
        ..multipleHypothesisModels = NA,
        ..hypothesisModelSpec = NA,
        ..modelComparison = NA,
        ..referenceModel = NA,
        ..complementModel = NA,
        ..weightRatios = NA,
        ..relativeWeightsMatrix = NA,
        ..compareCoefficients = NA,
        ..informedHypothesisTests = NA,
        ..bootstrap = NA,
        ..bootstrapSamples = NA,
        ..bootstrapCi = NA,
        ..postHoc = NA,
        ..postHocRmFactors = NA,
        ..postHocBetweenFactors = NA,
        ..postHocInteractions = NA,
        ..postHocHolm = NA,
        ..postHocBonferroni = NA,
        ..postHocTukey = NA,
        ..postHocScheffe = NA,
        ..postHocSidak = NA,
        ..postHocCi = NA,
        ..postHocSignificantFlags = NA,
        ..postHocLetters = NA,
        ..postHocEffectSizes = NA,
        ..conditionalComparisons = NA,
        ..postHocPoolError = NA,
        ..descriptivePlots = NA,
        ..descPlotXAxis = NA,
        ..descPlotLines = NA,
        ..descPlotSeparate = NA,
        ..descPlotError = NA,
        ..descPlotYAxisLabel = NA,
        ..descPlotAverageUnused = NA,
        ..barPlots = NA,
        ..barPlotXAxis = NA,
        ..barPlotSeparate = NA,
        ..barPlotError = NA,
        ..barPlotFixZero = NA,
        ..barPlotYAxisLabel = NA,
        ..barPlotAverageUnused = NA,
        ..raincloudPlots = NA,
        ..raincloudXAxis = NA,
        ..raincloudSeparate = NA,
        ..raincloudYAxisLabel = NA,
        ..marginalMeans = NA,
        ..marginalMeanTerms = NA,
        ..marginalMeansBootstrap = NA,
        ..marginalMeansCompareZero = NA,
        ..marginalMeansCi = NA,
        ..marginalMeansCiAdjustment = NA,
        ..marginalMeansPoolError = NA,
        ..simpleEffects = NA,
        ..simpleEffectFactor = NA,
        ..moderatorFactor1 = NA,
        ..moderatorFactor2 = NA,
        ..simpleEffectsTests = NA,
        ..simpleEffectsPairwise = NA,
        ..simpleEffectsEffectSizes = NA,
        ..simpleEffectsCi = NA,
        ..simpleEffectsPoolError = NA,
        ..friedman = NA,
        ..conoverPostHoc = NA,
        ..saveResiduals = NA,
        ..saveRawResiduals = NA,
        ..saveStudentizedResiduals = NA,
        ..saveStandardizedResiduals = NA,
        ..residualColumnName = NA,
        ..rmResidsOV = NA,
        ..rmStudentizedResidsOV = NA,
        ..rmStandardizedResidsOV = NA,
        ..savePredictions = NA,
        ..predictionColumnName = NA,
        ..rmPredictOV = NA,
        ..apaReport = NA,
        ..apaTables = NA,
        ..assumptionSummaries = NA,
        ..teachingMode = NA,
        ..explainSphericity = NA,
        ..explainCorrections = NA,
        ..effectSizeInterpretation = NA,
        ..interactionInterpretation = NA,
        ..publicationMode = NA,
        ..publicationFigures = NA,
        ..publicationTables = NA,
        ..exportWord = NA,
        ..exportPdf = NA,
        ..analysisSyntaxExport = NA,
        ..rSyntaxExport = NA,
        ..saveAnalysisConfiguration = NA)
)

enhancedRepeatedMeasuresAnovaResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "enhancedRepeatedMeasuresAnovaResults",
    inherit = jmvcore::Group,
    active = list(
        status = function() private$.items[["status"]],
        design = function() private$.items[["design"]],
        modelSummary = function() private$.items[["modelSummary"]],
        descriptivesSection = function() private$.items[["descriptivesSection"]],
        effectSizesSection = function() private$.items[["effectSizesSection"]],
        assumptionsSection = function() private$.items[["assumptionsSection"]],
        contrasts = function() private$.items[["contrasts"]],
        orderRestrictions = function() private$.items[["orderRestrictions"]],
        postHocSection = function() private$.items[["postHocSection"]],
        marginalMeansSection = function() private$.items[["marginalMeansSection"]],
        simpleEffectsSection = function() private$.items[["simpleEffectsSection"]],
        nonparametric = function() private$.items[["nonparametric"]],
        plots = function() private$.items[["plots"]],
        qqPlot = function() private$.items[["qqPlot"]],
        residualPlot = function() private$.items[["residualPlot"]],
        raincloudPlot = function() private$.items[["raincloudPlot"]],
        savedColumns = function() private$.items[["savedColumns"]],
        rmResidsOV = function() private$.items[["rmResidsOV"]],
        rmStudentizedResidsOV = function() private$.items[["rmStudentizedResidsOV"]],
        rmStandardizedResidsOV = function() private$.items[["rmStandardizedResidsOV"]],
        rmPredictOV = function() private$.items[["rmPredictOV"]],
        apa = function() private$.items[["apa"]],
        teaching = function() private$.items[["teaching"]],
        publication = function() private$.items[["publication"]],
        reproducibility = function() private$.items[["reproducibility"]],
        about = function() private$.items[["about"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="JASP Enhanced Repeated Measures ANOVA")
            self$add(jmvcore::Html$new(
                options=options,
                name="status",
                title="Implementation Status"))
            self$add(jmvcore::Html$new(
                options=options,
                name="design",
                title="Repeated Measures Design"))
            self$add(jmvcore::Html$new(
                options=options,
                name="modelSummary",
                title="Model Summary"))
            self$add(jmvcore::Html$new(
                options=options,
                name="descriptivesSection",
                title="Descriptive Statistics",
                visible="(descriptives)"))
            self$add(jmvcore::Html$new(
                options=options,
                name="effectSizesSection",
                title="Effect Sizes"))
            self$add(jmvcore::Html$new(
                options=options,
                name="assumptionsSection",
                title="Assumption Checks"))
            self$add(jmvcore::Html$new(
                options=options,
                name="contrasts",
                title="Repeated Measures Contrasts"))
            self$add(jmvcore::Html$new(
                options=options,
                name="orderRestrictions",
                title="Bayesian and Order Restricted Hypotheses"))
            self$add(jmvcore::Html$new(
                options=options,
                name="postHocSection",
                title="Post Hoc Tests",
                visible="(postHoc)"))
            self$add(jmvcore::Html$new(
                options=options,
                name="marginalMeansSection",
                title="Estimated Marginal Means",
                visible="(marginalMeans)"))
            self$add(jmvcore::Html$new(
                options=options,
                name="simpleEffectsSection",
                title="Simple Main Effects",
                visible="(simpleEffects)"))
            self$add(jmvcore::Html$new(
                options=options,
                name="nonparametric",
                title="Nonparametric Repeated Measures",
                visible="(friedman)"))
            self$add(jmvcore::Html$new(
                options=options,
                name="plots",
                title="Plots"))
            self$add(jmvcore::Image$new(
                options=options,
                name="qqPlot",
                title="Q-Q Plot of Residuals",
                visible="(qqPlotResiduals)",
                width=520,
                height=420,
                renderFun=".qqPlot"))
            self$add(jmvcore::Image$new(
                options=options,
                name="residualPlot",
                title="Residual Plot",
                visible="(residualPlots)",
                width=520,
                height=420,
                renderFun=".residualPlot"))
            self$add(jmvcore::Image$new(
                options=options,
                name="raincloudPlot",
                title="Raincloud Plot",
                visible="(raincloudPlots)",
                width=640,
                height=440,
                renderFun=".raincloudPlot"))
            self$add(jmvcore::Html$new(
                options=options,
                name="savedColumns",
                title="Saved Dataset Columns"))
            self$add(jmvcore::Output$new(
                options=options,
                name="rmResidsOV",
                title="Mean residuals",
                varTitle="RM mean residuals",
                varDescription="Subject-level mean residuals from JASP Enhanced Repeated Measures ANOVA",
                measureType="continuous",
                clearWith=list(
                    "repeatedMeasures",
                    "betweenFactors",
                    "covariates")))
            self$add(jmvcore::Output$new(
                options=options,
                name="rmStudentizedResidsOV",
                title="Mean studentized residuals",
                varTitle="RM mean studentized residuals",
                varDescription="Subject-level mean studentized residuals from JASP Enhanced Repeated Measures ANOVA",
                measureType="continuous",
                clearWith=list(
                    "repeatedMeasures",
                    "betweenFactors",
                    "covariates")))
            self$add(jmvcore::Output$new(
                options=options,
                name="rmStandardizedResidsOV",
                title="Mean standardized residuals",
                varTitle="RM mean standardized residuals",
                varDescription="Subject-level mean standardized residuals from JASP Enhanced Repeated Measures ANOVA",
                measureType="continuous",
                clearWith=list(
                    "repeatedMeasures",
                    "betweenFactors",
                    "covariates")))
            self$add(jmvcore::Output$new(
                options=options,
                name="rmPredictOV",
                title="Mean predicted values",
                varTitle="RM mean predicted values",
                varDescription="Subject-level mean predicted values from JASP Enhanced Repeated Measures ANOVA",
                measureType="continuous",
                clearWith=list(
                    "repeatedMeasures",
                    "betweenFactors",
                    "covariates")))
            self$add(jmvcore::Html$new(
                options=options,
                name="apa",
                title="APA Reporting",
                visible="(apaReport)"))
            self$add(jmvcore::Html$new(
                options=options,
                name="teaching",
                title="Teaching Mode",
                visible="(teachingMode)"))
            self$add(jmvcore::Html$new(
                options=options,
                name="publication",
                title="Publication Mode",
                visible="(publicationMode)"))
            self$add(jmvcore::Html$new(
                options=options,
                name="reproducibility",
                title="Reproducibility"))
            self$add(jmvcore::Html$new(
                options=options,
                name="about",
                title="About and Citation"))}))

enhancedRepeatedMeasuresAnovaBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "enhancedRepeatedMeasuresAnovaBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "jaspEnhancedAnova",
                name = "enhancedRepeatedMeasuresAnova",
                version = c(0,1,0),
                options = options,
                results = enhancedRepeatedMeasuresAnovaResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'none')
        }))

#' JASP Enhanced Repeated Measures ANOVA
#'
#' jamovi-native shell for the full JASP repeated measures ANOVA option 
#' surface, including repeated measures factor construction, model builder, 
#' sphericity testing, contrasts, post hoc tests, plots, marginal means, 
#' simple effects, nonparametric repeated measures procedures, export 
#' functions, APA reporting, teaching mode, publication mode, diagnostics, and 
#' reproducibility.
#' 
#' @param data .
#' @param rmFactorNames .
#' @param rmFactorLevels .
#' @param rmFactorSpec .
#' @param repeatedMeasures .
#' @param betweenFactors .
#' @param covariates .
#' @param groupingFactor .
#' @param descriptives .
#' @param vovkSellke .
#' @param omegaSq .
#' @param partialOmegaSq .
#' @param etaSq .
#' @param partialEtaSq .
#' @param generalizedEtaSq .
#' @param effectSizeCi .
#' @param ciWidth .
#' @param automaticModel .
#' @param manualModelTerms .
#' @param rmMainEffects .
#' @param rmInteractions .
#' @param rmHigherOrderInteractions .
#' @param betweenMainEffects .
#' @param betweenInteractions .
#' @param mixedInteractions .
#' @param sumOfSquares .
#' @param poolErrorTerms .
#' @param mauchly .
#' @param sphericityCorrection .
#' @param levene .
#' @param homogeneityTests .
#' @param qqPlotResiduals .
#' @param residualDiagnostics .
#' @param residualPlots .
#' @param influenceDiagnostics .
#' @param cooksDistance .
#' @param mahalanobisDistance .
#' @param rmContrastType .
#' @param contrastCi .
#' @param contrastCohensD .
#' @param contrastEffectSizes .
#' @param contrastPoolError .
#' @param rmCustomContrasts .
#' @param rmContrastSyntax .
#' @param orderRestricted .
#' @param orderRestrictedSyntax .
#' @param multipleHypothesisModels .
#' @param hypothesisModelSpec .
#' @param modelComparison .
#' @param referenceModel .
#' @param complementModel .
#' @param weightRatios .
#' @param relativeWeightsMatrix .
#' @param compareCoefficients .
#' @param informedHypothesisTests .
#' @param bootstrap .
#' @param bootstrapSamples .
#' @param bootstrapCi .
#' @param postHoc .
#' @param postHocRmFactors .
#' @param postHocBetweenFactors .
#' @param postHocInteractions .
#' @param postHocHolm .
#' @param postHocBonferroni .
#' @param postHocTukey .
#' @param postHocScheffe .
#' @param postHocSidak .
#' @param postHocCi .
#' @param postHocSignificantFlags .
#' @param postHocLetters .
#' @param postHocEffectSizes .
#' @param conditionalComparisons .
#' @param postHocPoolError .
#' @param descriptivePlots .
#' @param descPlotXAxis .
#' @param descPlotLines .
#' @param descPlotSeparate .
#' @param descPlotError .
#' @param descPlotYAxisLabel .
#' @param descPlotAverageUnused .
#' @param barPlots .
#' @param barPlotXAxis .
#' @param barPlotSeparate .
#' @param barPlotError .
#' @param barPlotFixZero .
#' @param barPlotYAxisLabel .
#' @param barPlotAverageUnused .
#' @param raincloudPlots .
#' @param raincloudXAxis .
#' @param raincloudSeparate .
#' @param raincloudYAxisLabel .
#' @param marginalMeans .
#' @param marginalMeanTerms .
#' @param marginalMeansBootstrap .
#' @param marginalMeansCompareZero .
#' @param marginalMeansCi .
#' @param marginalMeansCiAdjustment .
#' @param marginalMeansPoolError .
#' @param simpleEffects .
#' @param simpleEffectFactor .
#' @param moderatorFactor1 .
#' @param moderatorFactor2 .
#' @param simpleEffectsTests .
#' @param simpleEffectsPairwise .
#' @param simpleEffectsEffectSizes .
#' @param simpleEffectsCi .
#' @param simpleEffectsPoolError .
#' @param friedman .
#' @param conoverPostHoc .
#' @param saveResiduals .
#' @param saveRawResiduals .
#' @param saveStudentizedResiduals .
#' @param saveStandardizedResiduals .
#' @param residualColumnName .
#' @param savePredictions .
#' @param predictionColumnName .
#' @param apaReport .
#' @param apaTables .
#' @param assumptionSummaries .
#' @param teachingMode .
#' @param explainSphericity .
#' @param explainCorrections .
#' @param effectSizeInterpretation .
#' @param interactionInterpretation .
#' @param publicationMode .
#' @param publicationFigures .
#' @param publicationTables .
#' @param exportWord .
#' @param exportPdf .
#' @param analysisSyntaxExport .
#' @param rSyntaxExport .
#' @param saveAnalysisConfiguration .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$status} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$design} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$modelSummary} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$descriptivesSection} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$effectSizesSection} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$assumptionsSection} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$contrasts} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$orderRestrictions} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$postHocSection} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$marginalMeansSection} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$simpleEffectsSection} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$nonparametric} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$plots} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$qqPlot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$residualPlot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$raincloudPlot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$savedColumns} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$rmResidsOV} \tab \tab \tab \tab \tab an output \cr
#'   \code{results$rmStudentizedResidsOV} \tab \tab \tab \tab \tab an output \cr
#'   \code{results$rmStandardizedResidsOV} \tab \tab \tab \tab \tab an output \cr
#'   \code{results$rmPredictOV} \tab \tab \tab \tab \tab an output \cr
#'   \code{results$apa} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$teaching} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$publication} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$reproducibility} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$about} \tab \tab \tab \tab \tab a html \cr
#' }
#'
#' @export
enhancedRepeatedMeasuresAnova <- function(
    data,
    rmFactorNames = "Time",
    rmFactorLevels = "Pre, Post",
    rmFactorSpec = "",
    repeatedMeasures,
    betweenFactors,
    covariates,
    groupingFactor,
    descriptives = TRUE,
    vovkSellke = FALSE,
    omegaSq = TRUE,
    partialOmegaSq = FALSE,
    etaSq = TRUE,
    partialEtaSq = TRUE,
    generalizedEtaSq = TRUE,
    effectSizeCi = FALSE,
    ciWidth = 95,
    automaticModel = TRUE,
    manualModelTerms = "",
    rmMainEffects = TRUE,
    rmInteractions = TRUE,
    rmHigherOrderInteractions = TRUE,
    betweenMainEffects = TRUE,
    betweenInteractions = TRUE,
    mixedInteractions = TRUE,
    sumOfSquares = "type3",
    poolErrorTerms = FALSE,
    mauchly = TRUE,
    sphericityCorrection = "greenhouseGeisser",
    levene = TRUE,
    homogeneityTests = TRUE,
    qqPlotResiduals = FALSE,
    residualDiagnostics = FALSE,
    residualPlots = FALSE,
    influenceDiagnostics = FALSE,
    cooksDistance = FALSE,
    mahalanobisDistance = FALSE,
    rmContrastType = "none",
    contrastCi = TRUE,
    contrastCohensD = FALSE,
    contrastEffectSizes = FALSE,
    contrastPoolError = FALSE,
    rmCustomContrasts = FALSE,
    rmContrastSyntax = "",
    orderRestricted = FALSE,
    orderRestrictedSyntax = "",
    multipleHypothesisModels = FALSE,
    hypothesisModelSpec = "",
    modelComparison = FALSE,
    referenceModel = "unconstrained",
    complementModel = FALSE,
    weightRatios = FALSE,
    relativeWeightsMatrix = FALSE,
    compareCoefficients = FALSE,
    informedHypothesisTests = FALSE,
    bootstrap = FALSE,
    bootstrapSamples = 1000,
    bootstrapCi = FALSE,
    postHoc = FALSE,
    postHocRmFactors = TRUE,
    postHocBetweenFactors = FALSE,
    postHocInteractions = FALSE,
    postHocHolm = TRUE,
    postHocBonferroni = FALSE,
    postHocTukey = FALSE,
    postHocScheffe = FALSE,
    postHocSidak = FALSE,
    postHocCi = TRUE,
    postHocSignificantFlags = TRUE,
    postHocLetters = FALSE,
    postHocEffectSizes = FALSE,
    conditionalComparisons = FALSE,
    postHocPoolError = FALSE,
    descriptivePlots = FALSE,
    descPlotXAxis,
    descPlotLines,
    descPlotSeparate,
    descPlotError = "ci",
    descPlotYAxisLabel = "",
    descPlotAverageUnused = FALSE,
    barPlots = FALSE,
    barPlotXAxis,
    barPlotSeparate,
    barPlotError = "ci",
    barPlotFixZero = FALSE,
    barPlotYAxisLabel = "",
    barPlotAverageUnused = FALSE,
    raincloudPlots = FALSE,
    raincloudXAxis,
    raincloudSeparate,
    raincloudYAxisLabel = "",
    marginalMeans = FALSE,
    marginalMeanTerms,
    marginalMeansBootstrap = FALSE,
    marginalMeansCompareZero = FALSE,
    marginalMeansCi = TRUE,
    marginalMeansCiAdjustment = "none",
    marginalMeansPoolError = FALSE,
    simpleEffects = FALSE,
    simpleEffectFactor,
    moderatorFactor1,
    moderatorFactor2,
    simpleEffectsTests = TRUE,
    simpleEffectsPairwise = FALSE,
    simpleEffectsEffectSizes = FALSE,
    simpleEffectsCi = TRUE,
    simpleEffectsPoolError = FALSE,
    friedman = FALSE,
    conoverPostHoc = FALSE,
    saveResiduals = FALSE,
    saveRawResiduals = TRUE,
    saveStudentizedResiduals = FALSE,
    saveStandardizedResiduals = FALSE,
    residualColumnName = "rm_anova_residuals",
    savePredictions = FALSE,
    predictionColumnName = "rm_anova_predictions",
    apaReport = TRUE,
    apaTables = TRUE,
    assumptionSummaries = TRUE,
    teachingMode = FALSE,
    explainSphericity = FALSE,
    explainCorrections = FALSE,
    effectSizeInterpretation = FALSE,
    interactionInterpretation = FALSE,
    publicationMode = FALSE,
    publicationFigures = FALSE,
    publicationTables = FALSE,
    exportWord = FALSE,
    exportPdf = FALSE,
    analysisSyntaxExport = FALSE,
    rSyntaxExport = FALSE,
    saveAnalysisConfiguration = FALSE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("enhancedRepeatedMeasuresAnova requires jmvcore to be installed (restart may be required)")

    if ( ! missing(repeatedMeasures)) repeatedMeasures <- jmvcore::resolveQuo(jmvcore::enquo(repeatedMeasures))
    if ( ! missing(betweenFactors)) betweenFactors <- jmvcore::resolveQuo(jmvcore::enquo(betweenFactors))
    if ( ! missing(covariates)) covariates <- jmvcore::resolveQuo(jmvcore::enquo(covariates))
    if ( ! missing(groupingFactor)) groupingFactor <- jmvcore::resolveQuo(jmvcore::enquo(groupingFactor))
    if ( ! missing(descPlotXAxis)) descPlotXAxis <- jmvcore::resolveQuo(jmvcore::enquo(descPlotXAxis))
    if ( ! missing(descPlotLines)) descPlotLines <- jmvcore::resolveQuo(jmvcore::enquo(descPlotLines))
    if ( ! missing(descPlotSeparate)) descPlotSeparate <- jmvcore::resolveQuo(jmvcore::enquo(descPlotSeparate))
    if ( ! missing(barPlotXAxis)) barPlotXAxis <- jmvcore::resolveQuo(jmvcore::enquo(barPlotXAxis))
    if ( ! missing(barPlotSeparate)) barPlotSeparate <- jmvcore::resolveQuo(jmvcore::enquo(barPlotSeparate))
    if ( ! missing(raincloudXAxis)) raincloudXAxis <- jmvcore::resolveQuo(jmvcore::enquo(raincloudXAxis))
    if ( ! missing(raincloudSeparate)) raincloudSeparate <- jmvcore::resolveQuo(jmvcore::enquo(raincloudSeparate))
    if ( ! missing(marginalMeanTerms)) marginalMeanTerms <- jmvcore::resolveQuo(jmvcore::enquo(marginalMeanTerms))
    if ( ! missing(simpleEffectFactor)) simpleEffectFactor <- jmvcore::resolveQuo(jmvcore::enquo(simpleEffectFactor))
    if ( ! missing(moderatorFactor1)) moderatorFactor1 <- jmvcore::resolveQuo(jmvcore::enquo(moderatorFactor1))
    if ( ! missing(moderatorFactor2)) moderatorFactor2 <- jmvcore::resolveQuo(jmvcore::enquo(moderatorFactor2))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(repeatedMeasures), repeatedMeasures, NULL),
            `if`( ! missing(betweenFactors), betweenFactors, NULL),
            `if`( ! missing(covariates), covariates, NULL),
            `if`( ! missing(groupingFactor), groupingFactor, NULL),
            `if`( ! missing(descPlotXAxis), descPlotXAxis, NULL),
            `if`( ! missing(descPlotLines), descPlotLines, NULL),
            `if`( ! missing(descPlotSeparate), descPlotSeparate, NULL),
            `if`( ! missing(barPlotXAxis), barPlotXAxis, NULL),
            `if`( ! missing(barPlotSeparate), barPlotSeparate, NULL),
            `if`( ! missing(raincloudXAxis), raincloudXAxis, NULL),
            `if`( ! missing(raincloudSeparate), raincloudSeparate, NULL),
            `if`( ! missing(marginalMeanTerms), marginalMeanTerms, NULL),
            `if`( ! missing(simpleEffectFactor), simpleEffectFactor, NULL),
            `if`( ! missing(moderatorFactor1), moderatorFactor1, NULL),
            `if`( ! missing(moderatorFactor2), moderatorFactor2, NULL))

    for (v in betweenFactors) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    for (v in groupingFactor) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    for (v in descPlotXAxis) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    for (v in descPlotLines) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    for (v in descPlotSeparate) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    for (v in barPlotXAxis) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    for (v in barPlotSeparate) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    for (v in raincloudXAxis) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    for (v in raincloudSeparate) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    for (v in marginalMeanTerms) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    for (v in simpleEffectFactor) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    for (v in moderatorFactor1) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    for (v in moderatorFactor2) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])

    options <- enhancedRepeatedMeasuresAnovaOptions$new(
        rmFactorNames = rmFactorNames,
        rmFactorLevels = rmFactorLevels,
        rmFactorSpec = rmFactorSpec,
        repeatedMeasures = repeatedMeasures,
        betweenFactors = betweenFactors,
        covariates = covariates,
        groupingFactor = groupingFactor,
        descriptives = descriptives,
        vovkSellke = vovkSellke,
        omegaSq = omegaSq,
        partialOmegaSq = partialOmegaSq,
        etaSq = etaSq,
        partialEtaSq = partialEtaSq,
        generalizedEtaSq = generalizedEtaSq,
        effectSizeCi = effectSizeCi,
        ciWidth = ciWidth,
        automaticModel = automaticModel,
        manualModelTerms = manualModelTerms,
        rmMainEffects = rmMainEffects,
        rmInteractions = rmInteractions,
        rmHigherOrderInteractions = rmHigherOrderInteractions,
        betweenMainEffects = betweenMainEffects,
        betweenInteractions = betweenInteractions,
        mixedInteractions = mixedInteractions,
        sumOfSquares = sumOfSquares,
        poolErrorTerms = poolErrorTerms,
        mauchly = mauchly,
        sphericityCorrection = sphericityCorrection,
        levene = levene,
        homogeneityTests = homogeneityTests,
        qqPlotResiduals = qqPlotResiduals,
        residualDiagnostics = residualDiagnostics,
        residualPlots = residualPlots,
        influenceDiagnostics = influenceDiagnostics,
        cooksDistance = cooksDistance,
        mahalanobisDistance = mahalanobisDistance,
        rmContrastType = rmContrastType,
        contrastCi = contrastCi,
        contrastCohensD = contrastCohensD,
        contrastEffectSizes = contrastEffectSizes,
        contrastPoolError = contrastPoolError,
        rmCustomContrasts = rmCustomContrasts,
        rmContrastSyntax = rmContrastSyntax,
        orderRestricted = orderRestricted,
        orderRestrictedSyntax = orderRestrictedSyntax,
        multipleHypothesisModels = multipleHypothesisModels,
        hypothesisModelSpec = hypothesisModelSpec,
        modelComparison = modelComparison,
        referenceModel = referenceModel,
        complementModel = complementModel,
        weightRatios = weightRatios,
        relativeWeightsMatrix = relativeWeightsMatrix,
        compareCoefficients = compareCoefficients,
        informedHypothesisTests = informedHypothesisTests,
        bootstrap = bootstrap,
        bootstrapSamples = bootstrapSamples,
        bootstrapCi = bootstrapCi,
        postHoc = postHoc,
        postHocRmFactors = postHocRmFactors,
        postHocBetweenFactors = postHocBetweenFactors,
        postHocInteractions = postHocInteractions,
        postHocHolm = postHocHolm,
        postHocBonferroni = postHocBonferroni,
        postHocTukey = postHocTukey,
        postHocScheffe = postHocScheffe,
        postHocSidak = postHocSidak,
        postHocCi = postHocCi,
        postHocSignificantFlags = postHocSignificantFlags,
        postHocLetters = postHocLetters,
        postHocEffectSizes = postHocEffectSizes,
        conditionalComparisons = conditionalComparisons,
        postHocPoolError = postHocPoolError,
        descriptivePlots = descriptivePlots,
        descPlotXAxis = descPlotXAxis,
        descPlotLines = descPlotLines,
        descPlotSeparate = descPlotSeparate,
        descPlotError = descPlotError,
        descPlotYAxisLabel = descPlotYAxisLabel,
        descPlotAverageUnused = descPlotAverageUnused,
        barPlots = barPlots,
        barPlotXAxis = barPlotXAxis,
        barPlotSeparate = barPlotSeparate,
        barPlotError = barPlotError,
        barPlotFixZero = barPlotFixZero,
        barPlotYAxisLabel = barPlotYAxisLabel,
        barPlotAverageUnused = barPlotAverageUnused,
        raincloudPlots = raincloudPlots,
        raincloudXAxis = raincloudXAxis,
        raincloudSeparate = raincloudSeparate,
        raincloudYAxisLabel = raincloudYAxisLabel,
        marginalMeans = marginalMeans,
        marginalMeanTerms = marginalMeanTerms,
        marginalMeansBootstrap = marginalMeansBootstrap,
        marginalMeansCompareZero = marginalMeansCompareZero,
        marginalMeansCi = marginalMeansCi,
        marginalMeansCiAdjustment = marginalMeansCiAdjustment,
        marginalMeansPoolError = marginalMeansPoolError,
        simpleEffects = simpleEffects,
        simpleEffectFactor = simpleEffectFactor,
        moderatorFactor1 = moderatorFactor1,
        moderatorFactor2 = moderatorFactor2,
        simpleEffectsTests = simpleEffectsTests,
        simpleEffectsPairwise = simpleEffectsPairwise,
        simpleEffectsEffectSizes = simpleEffectsEffectSizes,
        simpleEffectsCi = simpleEffectsCi,
        simpleEffectsPoolError = simpleEffectsPoolError,
        friedman = friedman,
        conoverPostHoc = conoverPostHoc,
        saveResiduals = saveResiduals,
        saveRawResiduals = saveRawResiduals,
        saveStudentizedResiduals = saveStudentizedResiduals,
        saveStandardizedResiduals = saveStandardizedResiduals,
        residualColumnName = residualColumnName,
        savePredictions = savePredictions,
        predictionColumnName = predictionColumnName,
        apaReport = apaReport,
        apaTables = apaTables,
        assumptionSummaries = assumptionSummaries,
        teachingMode = teachingMode,
        explainSphericity = explainSphericity,
        explainCorrections = explainCorrections,
        effectSizeInterpretation = effectSizeInterpretation,
        interactionInterpretation = interactionInterpretation,
        publicationMode = publicationMode,
        publicationFigures = publicationFigures,
        publicationTables = publicationTables,
        exportWord = exportWord,
        exportPdf = exportPdf,
        analysisSyntaxExport = analysisSyntaxExport,
        rSyntaxExport = rSyntaxExport,
        saveAnalysisConfiguration = saveAnalysisConfiguration)

    analysis <- enhancedRepeatedMeasuresAnovaClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

