
# This file is automatically generated, you probably don't want to edit this

enhancedAnovaOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "enhancedAnovaOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            dependent = NULL,
            fixedFactors = NULL,
            covariates = NULL,
            randomFactors = NULL,
            wlsWeights = NULL,
            descriptives = TRUE,
            vovkSellke = FALSE,
            omegaSq = TRUE,
            partialOmegaSq = FALSE,
            etaSq = TRUE,
            partialEtaSq = TRUE,
            effectSizeCi = FALSE,
            ciWidth = 95,
            homogeneityCorrection = "none",
            qqPlotResiduals = FALSE,
            residualPlots = FALSE,
            leveragePlots = FALSE,
            influenceDiagnostics = FALSE,
            cooksDistance = FALSE,
            mahalanobisDistance = FALSE,
            customContrasts = FALSE,
            contrastSyntax = "",
            plannedContrasts = FALSE,
            polynomialContrasts = FALSE,
            repeatedContrasts = FALSE,
            helmertContrasts = FALSE,
            differenceContrasts = FALSE,
            deviationContrasts = FALSE,
            contrastCi = TRUE,
            contrastCohensD = FALSE,
            orderRestricted = FALSE,
            orderRestrictedSyntax = "",
            multipleHypothesisModels = FALSE,
            modelComparison = FALSE,
            referenceModel = "unconstrained",
            weightRatios = FALSE,
            relativeWeightsMatrix = FALSE,
            compareModelCoefficients = FALSE,
            informedHypothesisTests = FALSE,
            heterogeneityCorrection = FALSE,
            bootstrapCi = FALSE,
            bootstrapSamples = 1000,
            postHoc = FALSE,
            postHocTukey = TRUE,
            postHocScheffe = FALSE,
            postHocBonferroni = FALSE,
            postHocHolm = FALSE,
            postHocSidak = FALSE,
            postHocGamesHowell = FALSE,
            postHocDunnett = FALSE,
            postHocCi = TRUE,
            postHocSignificantFlags = TRUE,
            postHocLetters = FALSE,
            postHocEffectSizes = FALSE,
            postHocBootstrap = FALSE,
            conditionalComparisons = FALSE,
            descriptivePlots = FALSE,
            descPlotXAxis = NULL,
            descPlotLines = NULL,
            descPlotSeparate = NULL,
            descPlotError = "ci",
            barPlots = FALSE,
            barPlotXAxis = NULL,
            barPlotSeparate = NULL,
            barPlotError = "ci",
            barPlotFixZero = FALSE,
            raincloudPlots = FALSE,
            raincloudXAxis = NULL,
            raincloudSeparate = NULL,
            raincloudHorizontal = FALSE,
            marginalMeans = FALSE,
            marginalMeanTerms = NULL,
            marginalMeansTable = TRUE,
            marginalMeansPairwise = FALSE,
            marginalMeansCi = TRUE,
            marginalMeansCompareZero = FALSE,
            marginalMeansCiAdjustment = "none",
            simpleEffects = FALSE,
            simpleEffectFactor = NULL,
            moderatorFactor1 = NULL,
            moderatorFactor2 = NULL,
            simpleEffectsTables = TRUE,
            simpleEffectsPostHoc = FALSE,
            simpleEffectsCi = TRUE,
            simpleEffectsEffectSizes = FALSE,
            kruskalWallis = FALSE,
            kruskalEpsilonSq = TRUE,
            kruskalEtaSq = FALSE,
            kruskalCi = FALSE,
            dunnPostHoc = FALSE,
            saveResiduals = FALSE,
            saveRawResiduals = TRUE,
            saveStudentizedResiduals = FALSE,
            saveStandardizedResiduals = FALSE,
            residualColumnName = "anova_residuals",
            savePredictions = FALSE,
            predictionColumnName = "anova_predictions",
            apaReport = TRUE,
            apaTables = TRUE,
            copyReadyReport = FALSE,
            teachingMode = FALSE,
            explainStatistics = FALSE,
            effectSizeInterpretation = FALSE,
            assumptionGuidance = FALSE,
            assumptionRemedies = FALSE,
            publicationMode = FALSE,
            publicationTables = FALSE,
            publicationFigures = FALSE,
            exportWord = FALSE,
            exportPdf = FALSE,
            analysisSyntaxExport = FALSE,
            rSyntaxExport = FALSE,
            saveAnalysisConfiguration = FALSE, ...) {

            super$initialize(
                package="jaspEnhancedAnova",
                name="enhancedAnova",
                requiresData=TRUE,
                ...)

            private$..dependent <- jmvcore::OptionVariable$new(
                "dependent",
                dependent,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..fixedFactors <- jmvcore::OptionVariables$new(
                "fixedFactors",
                fixedFactors,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"))
            private$..covariates <- jmvcore::OptionVariables$new(
                "covariates",
                covariates,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..randomFactors <- jmvcore::OptionVariables$new(
                "randomFactors",
                randomFactors,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"))
            private$..wlsWeights <- jmvcore::OptionVariable$new(
                "wlsWeights",
                wlsWeights,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..descriptives <- jmvcore::OptionBool$new(
                "descriptives",
                descriptives,
                default=TRUE)
            private$..vovkSellke <- jmvcore::OptionBool$new(
                "vovkSellke",
                vovkSellke,
                default=FALSE)
            private$..omegaSq <- jmvcore::OptionBool$new(
                "omegaSq",
                omegaSq,
                default=TRUE)
            private$..partialOmegaSq <- jmvcore::OptionBool$new(
                "partialOmegaSq",
                partialOmegaSq,
                default=FALSE)
            private$..etaSq <- jmvcore::OptionBool$new(
                "etaSq",
                etaSq,
                default=TRUE)
            private$..partialEtaSq <- jmvcore::OptionBool$new(
                "partialEtaSq",
                partialEtaSq,
                default=TRUE)
            private$..effectSizeCi <- jmvcore::OptionBool$new(
                "effectSizeCi",
                effectSizeCi,
                default=FALSE)
            private$..ciWidth <- jmvcore::OptionNumber$new(
                "ciWidth",
                ciWidth,
                min=50,
                max=99.9,
                default=95)
            private$..homogeneityCorrection <- jmvcore::OptionList$new(
                "homogeneityCorrection",
                homogeneityCorrection,
                options=list(
                    "none",
                    "brownForsythe",
                    "welch"),
                default="none")
            private$..qqPlotResiduals <- jmvcore::OptionBool$new(
                "qqPlotResiduals",
                qqPlotResiduals,
                default=FALSE)
            private$..residualPlots <- jmvcore::OptionBool$new(
                "residualPlots",
                residualPlots,
                default=FALSE)
            private$..leveragePlots <- jmvcore::OptionBool$new(
                "leveragePlots",
                leveragePlots,
                default=FALSE)
            private$..influenceDiagnostics <- jmvcore::OptionBool$new(
                "influenceDiagnostics",
                influenceDiagnostics,
                default=FALSE)
            private$..cooksDistance <- jmvcore::OptionBool$new(
                "cooksDistance",
                cooksDistance,
                default=FALSE)
            private$..mahalanobisDistance <- jmvcore::OptionBool$new(
                "mahalanobisDistance",
                mahalanobisDistance,
                default=FALSE)
            private$..customContrasts <- jmvcore::OptionBool$new(
                "customContrasts",
                customContrasts,
                default=FALSE)
            private$..contrastSyntax <- jmvcore::OptionString$new(
                "contrastSyntax",
                contrastSyntax,
                default="")
            private$..plannedContrasts <- jmvcore::OptionBool$new(
                "plannedContrasts",
                plannedContrasts,
                default=FALSE)
            private$..polynomialContrasts <- jmvcore::OptionBool$new(
                "polynomialContrasts",
                polynomialContrasts,
                default=FALSE)
            private$..repeatedContrasts <- jmvcore::OptionBool$new(
                "repeatedContrasts",
                repeatedContrasts,
                default=FALSE)
            private$..helmertContrasts <- jmvcore::OptionBool$new(
                "helmertContrasts",
                helmertContrasts,
                default=FALSE)
            private$..differenceContrasts <- jmvcore::OptionBool$new(
                "differenceContrasts",
                differenceContrasts,
                default=FALSE)
            private$..deviationContrasts <- jmvcore::OptionBool$new(
                "deviationContrasts",
                deviationContrasts,
                default=FALSE)
            private$..contrastCi <- jmvcore::OptionBool$new(
                "contrastCi",
                contrastCi,
                default=TRUE)
            private$..contrastCohensD <- jmvcore::OptionBool$new(
                "contrastCohensD",
                contrastCohensD,
                default=FALSE)
            private$..orderRestricted <- jmvcore::OptionBool$new(
                "orderRestricted",
                orderRestricted,
                default=FALSE)
            private$..orderRestrictedSyntax <- jmvcore::OptionString$new(
                "orderRestrictedSyntax",
                orderRestrictedSyntax,
                default="")
            private$..multipleHypothesisModels <- jmvcore::OptionBool$new(
                "multipleHypothesisModels",
                multipleHypothesisModels,
                default=FALSE)
            private$..modelComparison <- jmvcore::OptionBool$new(
                "modelComparison",
                modelComparison,
                default=FALSE)
            private$..referenceModel <- jmvcore::OptionList$new(
                "referenceModel",
                referenceModel,
                options=list(
                    "unconstrained",
                    "complement",
                    "nullModel"),
                default="unconstrained")
            private$..weightRatios <- jmvcore::OptionBool$new(
                "weightRatios",
                weightRatios,
                default=FALSE)
            private$..relativeWeightsMatrix <- jmvcore::OptionBool$new(
                "relativeWeightsMatrix",
                relativeWeightsMatrix,
                default=FALSE)
            private$..compareModelCoefficients <- jmvcore::OptionBool$new(
                "compareModelCoefficients",
                compareModelCoefficients,
                default=FALSE)
            private$..informedHypothesisTests <- jmvcore::OptionBool$new(
                "informedHypothesisTests",
                informedHypothesisTests,
                default=FALSE)
            private$..heterogeneityCorrection <- jmvcore::OptionBool$new(
                "heterogeneityCorrection",
                heterogeneityCorrection,
                default=FALSE)
            private$..bootstrapCi <- jmvcore::OptionBool$new(
                "bootstrapCi",
                bootstrapCi,
                default=FALSE)
            private$..bootstrapSamples <- jmvcore::OptionInteger$new(
                "bootstrapSamples",
                bootstrapSamples,
                min=100,
                max=100000,
                default=1000)
            private$..postHoc <- jmvcore::OptionBool$new(
                "postHoc",
                postHoc,
                default=FALSE)
            private$..postHocTukey <- jmvcore::OptionBool$new(
                "postHocTukey",
                postHocTukey,
                default=TRUE)
            private$..postHocScheffe <- jmvcore::OptionBool$new(
                "postHocScheffe",
                postHocScheffe,
                default=FALSE)
            private$..postHocBonferroni <- jmvcore::OptionBool$new(
                "postHocBonferroni",
                postHocBonferroni,
                default=FALSE)
            private$..postHocHolm <- jmvcore::OptionBool$new(
                "postHocHolm",
                postHocHolm,
                default=FALSE)
            private$..postHocSidak <- jmvcore::OptionBool$new(
                "postHocSidak",
                postHocSidak,
                default=FALSE)
            private$..postHocGamesHowell <- jmvcore::OptionBool$new(
                "postHocGamesHowell",
                postHocGamesHowell,
                default=FALSE)
            private$..postHocDunnett <- jmvcore::OptionBool$new(
                "postHocDunnett",
                postHocDunnett,
                default=FALSE)
            private$..postHocCi <- jmvcore::OptionBool$new(
                "postHocCi",
                postHocCi,
                default=TRUE)
            private$..postHocSignificantFlags <- jmvcore::OptionBool$new(
                "postHocSignificantFlags",
                postHocSignificantFlags,
                default=TRUE)
            private$..postHocLetters <- jmvcore::OptionBool$new(
                "postHocLetters",
                postHocLetters,
                default=FALSE)
            private$..postHocEffectSizes <- jmvcore::OptionBool$new(
                "postHocEffectSizes",
                postHocEffectSizes,
                default=FALSE)
            private$..postHocBootstrap <- jmvcore::OptionBool$new(
                "postHocBootstrap",
                postHocBootstrap,
                default=FALSE)
            private$..conditionalComparisons <- jmvcore::OptionBool$new(
                "conditionalComparisons",
                conditionalComparisons,
                default=FALSE)
            private$..descriptivePlots <- jmvcore::OptionBool$new(
                "descriptivePlots",
                descriptivePlots,
                default=FALSE)
            private$..descPlotXAxis <- jmvcore::OptionVariable$new(
                "descPlotXAxis",
                descPlotXAxis,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"))
            private$..descPlotLines <- jmvcore::OptionVariable$new(
                "descPlotLines",
                descPlotLines,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"))
            private$..descPlotSeparate <- jmvcore::OptionVariable$new(
                "descPlotSeparate",
                descPlotSeparate,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"))
            private$..descPlotError <- jmvcore::OptionList$new(
                "descPlotError",
                descPlotError,
                options=list(
                    "ci",
                    "se"),
                default="ci")
            private$..barPlots <- jmvcore::OptionBool$new(
                "barPlots",
                barPlots,
                default=FALSE)
            private$..barPlotXAxis <- jmvcore::OptionVariable$new(
                "barPlotXAxis",
                barPlotXAxis,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"))
            private$..barPlotSeparate <- jmvcore::OptionVariable$new(
                "barPlotSeparate",
                barPlotSeparate,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"))
            private$..barPlotError <- jmvcore::OptionList$new(
                "barPlotError",
                barPlotError,
                options=list(
                    "ci",
                    "se"),
                default="ci")
            private$..barPlotFixZero <- jmvcore::OptionBool$new(
                "barPlotFixZero",
                barPlotFixZero,
                default=FALSE)
            private$..raincloudPlots <- jmvcore::OptionBool$new(
                "raincloudPlots",
                raincloudPlots,
                default=FALSE)
            private$..raincloudXAxis <- jmvcore::OptionVariable$new(
                "raincloudXAxis",
                raincloudXAxis,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"))
            private$..raincloudSeparate <- jmvcore::OptionVariable$new(
                "raincloudSeparate",
                raincloudSeparate,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"))
            private$..raincloudHorizontal <- jmvcore::OptionBool$new(
                "raincloudHorizontal",
                raincloudHorizontal,
                default=FALSE)
            private$..marginalMeans <- jmvcore::OptionBool$new(
                "marginalMeans",
                marginalMeans,
                default=FALSE)
            private$..marginalMeanTerms <- jmvcore::OptionVariables$new(
                "marginalMeanTerms",
                marginalMeanTerms,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"))
            private$..marginalMeansTable <- jmvcore::OptionBool$new(
                "marginalMeansTable",
                marginalMeansTable,
                default=TRUE)
            private$..marginalMeansPairwise <- jmvcore::OptionBool$new(
                "marginalMeansPairwise",
                marginalMeansPairwise,
                default=FALSE)
            private$..marginalMeansCi <- jmvcore::OptionBool$new(
                "marginalMeansCi",
                marginalMeansCi,
                default=TRUE)
            private$..marginalMeansCompareZero <- jmvcore::OptionBool$new(
                "marginalMeansCompareZero",
                marginalMeansCompareZero,
                default=FALSE)
            private$..marginalMeansCiAdjustment <- jmvcore::OptionList$new(
                "marginalMeansCiAdjustment",
                marginalMeansCiAdjustment,
                options=list(
                    "none",
                    "bonferroni",
                    "holm",
                    "sidak",
                    "tukey"),
                default="none")
            private$..simpleEffects <- jmvcore::OptionBool$new(
                "simpleEffects",
                simpleEffects,
                default=FALSE)
            private$..simpleEffectFactor <- jmvcore::OptionVariable$new(
                "simpleEffectFactor",
                simpleEffectFactor,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"))
            private$..moderatorFactor1 <- jmvcore::OptionVariable$new(
                "moderatorFactor1",
                moderatorFactor1,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"))
            private$..moderatorFactor2 <- jmvcore::OptionVariable$new(
                "moderatorFactor2",
                moderatorFactor2,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"))
            private$..simpleEffectsTables <- jmvcore::OptionBool$new(
                "simpleEffectsTables",
                simpleEffectsTables,
                default=TRUE)
            private$..simpleEffectsPostHoc <- jmvcore::OptionBool$new(
                "simpleEffectsPostHoc",
                simpleEffectsPostHoc,
                default=FALSE)
            private$..simpleEffectsCi <- jmvcore::OptionBool$new(
                "simpleEffectsCi",
                simpleEffectsCi,
                default=TRUE)
            private$..simpleEffectsEffectSizes <- jmvcore::OptionBool$new(
                "simpleEffectsEffectSizes",
                simpleEffectsEffectSizes,
                default=FALSE)
            private$..kruskalWallis <- jmvcore::OptionBool$new(
                "kruskalWallis",
                kruskalWallis,
                default=FALSE)
            private$..kruskalEpsilonSq <- jmvcore::OptionBool$new(
                "kruskalEpsilonSq",
                kruskalEpsilonSq,
                default=TRUE)
            private$..kruskalEtaSq <- jmvcore::OptionBool$new(
                "kruskalEtaSq",
                kruskalEtaSq,
                default=FALSE)
            private$..kruskalCi <- jmvcore::OptionBool$new(
                "kruskalCi",
                kruskalCi,
                default=FALSE)
            private$..dunnPostHoc <- jmvcore::OptionBool$new(
                "dunnPostHoc",
                dunnPostHoc,
                default=FALSE)
            private$..saveResiduals <- jmvcore::OptionBool$new(
                "saveResiduals",
                saveResiduals,
                default=FALSE)
            private$..saveRawResiduals <- jmvcore::OptionBool$new(
                "saveRawResiduals",
                saveRawResiduals,
                default=TRUE)
            private$..saveStudentizedResiduals <- jmvcore::OptionBool$new(
                "saveStudentizedResiduals",
                saveStudentizedResiduals,
                default=FALSE)
            private$..saveStandardizedResiduals <- jmvcore::OptionBool$new(
                "saveStandardizedResiduals",
                saveStandardizedResiduals,
                default=FALSE)
            private$..residualColumnName <- jmvcore::OptionString$new(
                "residualColumnName",
                residualColumnName,
                default="anova_residuals")
            private$..residsOV <- jmvcore::OptionOutput$new(
                "residsOV")
            private$..studentizedResidsOV <- jmvcore::OptionOutput$new(
                "studentizedResidsOV")
            private$..standardizedResidsOV <- jmvcore::OptionOutput$new(
                "standardizedResidsOV")
            private$..savePredictions <- jmvcore::OptionBool$new(
                "savePredictions",
                savePredictions,
                default=FALSE)
            private$..predictionColumnName <- jmvcore::OptionString$new(
                "predictionColumnName",
                predictionColumnName,
                default="anova_predictions")
            private$..predictOV <- jmvcore::OptionOutput$new(
                "predictOV")
            private$..apaReport <- jmvcore::OptionBool$new(
                "apaReport",
                apaReport,
                default=TRUE)
            private$..apaTables <- jmvcore::OptionBool$new(
                "apaTables",
                apaTables,
                default=TRUE)
            private$..copyReadyReport <- jmvcore::OptionBool$new(
                "copyReadyReport",
                copyReadyReport,
                default=FALSE)
            private$..teachingMode <- jmvcore::OptionBool$new(
                "teachingMode",
                teachingMode,
                default=FALSE)
            private$..explainStatistics <- jmvcore::OptionBool$new(
                "explainStatistics",
                explainStatistics,
                default=FALSE)
            private$..effectSizeInterpretation <- jmvcore::OptionBool$new(
                "effectSizeInterpretation",
                effectSizeInterpretation,
                default=FALSE)
            private$..assumptionGuidance <- jmvcore::OptionBool$new(
                "assumptionGuidance",
                assumptionGuidance,
                default=FALSE)
            private$..assumptionRemedies <- jmvcore::OptionBool$new(
                "assumptionRemedies",
                assumptionRemedies,
                default=FALSE)
            private$..publicationMode <- jmvcore::OptionBool$new(
                "publicationMode",
                publicationMode,
                default=FALSE)
            private$..publicationTables <- jmvcore::OptionBool$new(
                "publicationTables",
                publicationTables,
                default=FALSE)
            private$..publicationFigures <- jmvcore::OptionBool$new(
                "publicationFigures",
                publicationFigures,
                default=FALSE)
            private$..exportWord <- jmvcore::OptionBool$new(
                "exportWord",
                exportWord,
                default=FALSE)
            private$..exportPdf <- jmvcore::OptionBool$new(
                "exportPdf",
                exportPdf,
                default=FALSE)
            private$..analysisSyntaxExport <- jmvcore::OptionBool$new(
                "analysisSyntaxExport",
                analysisSyntaxExport,
                default=FALSE)
            private$..rSyntaxExport <- jmvcore::OptionBool$new(
                "rSyntaxExport",
                rSyntaxExport,
                default=FALSE)
            private$..saveAnalysisConfiguration <- jmvcore::OptionBool$new(
                "saveAnalysisConfiguration",
                saveAnalysisConfiguration,
                default=FALSE)

            self$.addOption(private$..dependent)
            self$.addOption(private$..fixedFactors)
            self$.addOption(private$..covariates)
            self$.addOption(private$..randomFactors)
            self$.addOption(private$..wlsWeights)
            self$.addOption(private$..descriptives)
            self$.addOption(private$..vovkSellke)
            self$.addOption(private$..omegaSq)
            self$.addOption(private$..partialOmegaSq)
            self$.addOption(private$..etaSq)
            self$.addOption(private$..partialEtaSq)
            self$.addOption(private$..effectSizeCi)
            self$.addOption(private$..ciWidth)
            self$.addOption(private$..homogeneityCorrection)
            self$.addOption(private$..qqPlotResiduals)
            self$.addOption(private$..residualPlots)
            self$.addOption(private$..leveragePlots)
            self$.addOption(private$..influenceDiagnostics)
            self$.addOption(private$..cooksDistance)
            self$.addOption(private$..mahalanobisDistance)
            self$.addOption(private$..customContrasts)
            self$.addOption(private$..contrastSyntax)
            self$.addOption(private$..plannedContrasts)
            self$.addOption(private$..polynomialContrasts)
            self$.addOption(private$..repeatedContrasts)
            self$.addOption(private$..helmertContrasts)
            self$.addOption(private$..differenceContrasts)
            self$.addOption(private$..deviationContrasts)
            self$.addOption(private$..contrastCi)
            self$.addOption(private$..contrastCohensD)
            self$.addOption(private$..orderRestricted)
            self$.addOption(private$..orderRestrictedSyntax)
            self$.addOption(private$..multipleHypothesisModels)
            self$.addOption(private$..modelComparison)
            self$.addOption(private$..referenceModel)
            self$.addOption(private$..weightRatios)
            self$.addOption(private$..relativeWeightsMatrix)
            self$.addOption(private$..compareModelCoefficients)
            self$.addOption(private$..informedHypothesisTests)
            self$.addOption(private$..heterogeneityCorrection)
            self$.addOption(private$..bootstrapCi)
            self$.addOption(private$..bootstrapSamples)
            self$.addOption(private$..postHoc)
            self$.addOption(private$..postHocTukey)
            self$.addOption(private$..postHocScheffe)
            self$.addOption(private$..postHocBonferroni)
            self$.addOption(private$..postHocHolm)
            self$.addOption(private$..postHocSidak)
            self$.addOption(private$..postHocGamesHowell)
            self$.addOption(private$..postHocDunnett)
            self$.addOption(private$..postHocCi)
            self$.addOption(private$..postHocSignificantFlags)
            self$.addOption(private$..postHocLetters)
            self$.addOption(private$..postHocEffectSizes)
            self$.addOption(private$..postHocBootstrap)
            self$.addOption(private$..conditionalComparisons)
            self$.addOption(private$..descriptivePlots)
            self$.addOption(private$..descPlotXAxis)
            self$.addOption(private$..descPlotLines)
            self$.addOption(private$..descPlotSeparate)
            self$.addOption(private$..descPlotError)
            self$.addOption(private$..barPlots)
            self$.addOption(private$..barPlotXAxis)
            self$.addOption(private$..barPlotSeparate)
            self$.addOption(private$..barPlotError)
            self$.addOption(private$..barPlotFixZero)
            self$.addOption(private$..raincloudPlots)
            self$.addOption(private$..raincloudXAxis)
            self$.addOption(private$..raincloudSeparate)
            self$.addOption(private$..raincloudHorizontal)
            self$.addOption(private$..marginalMeans)
            self$.addOption(private$..marginalMeanTerms)
            self$.addOption(private$..marginalMeansTable)
            self$.addOption(private$..marginalMeansPairwise)
            self$.addOption(private$..marginalMeansCi)
            self$.addOption(private$..marginalMeansCompareZero)
            self$.addOption(private$..marginalMeansCiAdjustment)
            self$.addOption(private$..simpleEffects)
            self$.addOption(private$..simpleEffectFactor)
            self$.addOption(private$..moderatorFactor1)
            self$.addOption(private$..moderatorFactor2)
            self$.addOption(private$..simpleEffectsTables)
            self$.addOption(private$..simpleEffectsPostHoc)
            self$.addOption(private$..simpleEffectsCi)
            self$.addOption(private$..simpleEffectsEffectSizes)
            self$.addOption(private$..kruskalWallis)
            self$.addOption(private$..kruskalEpsilonSq)
            self$.addOption(private$..kruskalEtaSq)
            self$.addOption(private$..kruskalCi)
            self$.addOption(private$..dunnPostHoc)
            self$.addOption(private$..saveResiduals)
            self$.addOption(private$..saveRawResiduals)
            self$.addOption(private$..saveStudentizedResiduals)
            self$.addOption(private$..saveStandardizedResiduals)
            self$.addOption(private$..residualColumnName)
            self$.addOption(private$..residsOV)
            self$.addOption(private$..studentizedResidsOV)
            self$.addOption(private$..standardizedResidsOV)
            self$.addOption(private$..savePredictions)
            self$.addOption(private$..predictionColumnName)
            self$.addOption(private$..predictOV)
            self$.addOption(private$..apaReport)
            self$.addOption(private$..apaTables)
            self$.addOption(private$..copyReadyReport)
            self$.addOption(private$..teachingMode)
            self$.addOption(private$..explainStatistics)
            self$.addOption(private$..effectSizeInterpretation)
            self$.addOption(private$..assumptionGuidance)
            self$.addOption(private$..assumptionRemedies)
            self$.addOption(private$..publicationMode)
            self$.addOption(private$..publicationTables)
            self$.addOption(private$..publicationFigures)
            self$.addOption(private$..exportWord)
            self$.addOption(private$..exportPdf)
            self$.addOption(private$..analysisSyntaxExport)
            self$.addOption(private$..rSyntaxExport)
            self$.addOption(private$..saveAnalysisConfiguration)
        }),
    active = list(
        dependent = function() private$..dependent$value,
        fixedFactors = function() private$..fixedFactors$value,
        covariates = function() private$..covariates$value,
        randomFactors = function() private$..randomFactors$value,
        wlsWeights = function() private$..wlsWeights$value,
        descriptives = function() private$..descriptives$value,
        vovkSellke = function() private$..vovkSellke$value,
        omegaSq = function() private$..omegaSq$value,
        partialOmegaSq = function() private$..partialOmegaSq$value,
        etaSq = function() private$..etaSq$value,
        partialEtaSq = function() private$..partialEtaSq$value,
        effectSizeCi = function() private$..effectSizeCi$value,
        ciWidth = function() private$..ciWidth$value,
        homogeneityCorrection = function() private$..homogeneityCorrection$value,
        qqPlotResiduals = function() private$..qqPlotResiduals$value,
        residualPlots = function() private$..residualPlots$value,
        leveragePlots = function() private$..leveragePlots$value,
        influenceDiagnostics = function() private$..influenceDiagnostics$value,
        cooksDistance = function() private$..cooksDistance$value,
        mahalanobisDistance = function() private$..mahalanobisDistance$value,
        customContrasts = function() private$..customContrasts$value,
        contrastSyntax = function() private$..contrastSyntax$value,
        plannedContrasts = function() private$..plannedContrasts$value,
        polynomialContrasts = function() private$..polynomialContrasts$value,
        repeatedContrasts = function() private$..repeatedContrasts$value,
        helmertContrasts = function() private$..helmertContrasts$value,
        differenceContrasts = function() private$..differenceContrasts$value,
        deviationContrasts = function() private$..deviationContrasts$value,
        contrastCi = function() private$..contrastCi$value,
        contrastCohensD = function() private$..contrastCohensD$value,
        orderRestricted = function() private$..orderRestricted$value,
        orderRestrictedSyntax = function() private$..orderRestrictedSyntax$value,
        multipleHypothesisModels = function() private$..multipleHypothesisModels$value,
        modelComparison = function() private$..modelComparison$value,
        referenceModel = function() private$..referenceModel$value,
        weightRatios = function() private$..weightRatios$value,
        relativeWeightsMatrix = function() private$..relativeWeightsMatrix$value,
        compareModelCoefficients = function() private$..compareModelCoefficients$value,
        informedHypothesisTests = function() private$..informedHypothesisTests$value,
        heterogeneityCorrection = function() private$..heterogeneityCorrection$value,
        bootstrapCi = function() private$..bootstrapCi$value,
        bootstrapSamples = function() private$..bootstrapSamples$value,
        postHoc = function() private$..postHoc$value,
        postHocTukey = function() private$..postHocTukey$value,
        postHocScheffe = function() private$..postHocScheffe$value,
        postHocBonferroni = function() private$..postHocBonferroni$value,
        postHocHolm = function() private$..postHocHolm$value,
        postHocSidak = function() private$..postHocSidak$value,
        postHocGamesHowell = function() private$..postHocGamesHowell$value,
        postHocDunnett = function() private$..postHocDunnett$value,
        postHocCi = function() private$..postHocCi$value,
        postHocSignificantFlags = function() private$..postHocSignificantFlags$value,
        postHocLetters = function() private$..postHocLetters$value,
        postHocEffectSizes = function() private$..postHocEffectSizes$value,
        postHocBootstrap = function() private$..postHocBootstrap$value,
        conditionalComparisons = function() private$..conditionalComparisons$value,
        descriptivePlots = function() private$..descriptivePlots$value,
        descPlotXAxis = function() private$..descPlotXAxis$value,
        descPlotLines = function() private$..descPlotLines$value,
        descPlotSeparate = function() private$..descPlotSeparate$value,
        descPlotError = function() private$..descPlotError$value,
        barPlots = function() private$..barPlots$value,
        barPlotXAxis = function() private$..barPlotXAxis$value,
        barPlotSeparate = function() private$..barPlotSeparate$value,
        barPlotError = function() private$..barPlotError$value,
        barPlotFixZero = function() private$..barPlotFixZero$value,
        raincloudPlots = function() private$..raincloudPlots$value,
        raincloudXAxis = function() private$..raincloudXAxis$value,
        raincloudSeparate = function() private$..raincloudSeparate$value,
        raincloudHorizontal = function() private$..raincloudHorizontal$value,
        marginalMeans = function() private$..marginalMeans$value,
        marginalMeanTerms = function() private$..marginalMeanTerms$value,
        marginalMeansTable = function() private$..marginalMeansTable$value,
        marginalMeansPairwise = function() private$..marginalMeansPairwise$value,
        marginalMeansCi = function() private$..marginalMeansCi$value,
        marginalMeansCompareZero = function() private$..marginalMeansCompareZero$value,
        marginalMeansCiAdjustment = function() private$..marginalMeansCiAdjustment$value,
        simpleEffects = function() private$..simpleEffects$value,
        simpleEffectFactor = function() private$..simpleEffectFactor$value,
        moderatorFactor1 = function() private$..moderatorFactor1$value,
        moderatorFactor2 = function() private$..moderatorFactor2$value,
        simpleEffectsTables = function() private$..simpleEffectsTables$value,
        simpleEffectsPostHoc = function() private$..simpleEffectsPostHoc$value,
        simpleEffectsCi = function() private$..simpleEffectsCi$value,
        simpleEffectsEffectSizes = function() private$..simpleEffectsEffectSizes$value,
        kruskalWallis = function() private$..kruskalWallis$value,
        kruskalEpsilonSq = function() private$..kruskalEpsilonSq$value,
        kruskalEtaSq = function() private$..kruskalEtaSq$value,
        kruskalCi = function() private$..kruskalCi$value,
        dunnPostHoc = function() private$..dunnPostHoc$value,
        saveResiduals = function() private$..saveResiduals$value,
        saveRawResiduals = function() private$..saveRawResiduals$value,
        saveStudentizedResiduals = function() private$..saveStudentizedResiduals$value,
        saveStandardizedResiduals = function() private$..saveStandardizedResiduals$value,
        residualColumnName = function() private$..residualColumnName$value,
        residsOV = function() private$..residsOV$value,
        studentizedResidsOV = function() private$..studentizedResidsOV$value,
        standardizedResidsOV = function() private$..standardizedResidsOV$value,
        savePredictions = function() private$..savePredictions$value,
        predictionColumnName = function() private$..predictionColumnName$value,
        predictOV = function() private$..predictOV$value,
        apaReport = function() private$..apaReport$value,
        apaTables = function() private$..apaTables$value,
        copyReadyReport = function() private$..copyReadyReport$value,
        teachingMode = function() private$..teachingMode$value,
        explainStatistics = function() private$..explainStatistics$value,
        effectSizeInterpretation = function() private$..effectSizeInterpretation$value,
        assumptionGuidance = function() private$..assumptionGuidance$value,
        assumptionRemedies = function() private$..assumptionRemedies$value,
        publicationMode = function() private$..publicationMode$value,
        publicationTables = function() private$..publicationTables$value,
        publicationFigures = function() private$..publicationFigures$value,
        exportWord = function() private$..exportWord$value,
        exportPdf = function() private$..exportPdf$value,
        analysisSyntaxExport = function() private$..analysisSyntaxExport$value,
        rSyntaxExport = function() private$..rSyntaxExport$value,
        saveAnalysisConfiguration = function() private$..saveAnalysisConfiguration$value),
    private = list(
        ..dependent = NA,
        ..fixedFactors = NA,
        ..covariates = NA,
        ..randomFactors = NA,
        ..wlsWeights = NA,
        ..descriptives = NA,
        ..vovkSellke = NA,
        ..omegaSq = NA,
        ..partialOmegaSq = NA,
        ..etaSq = NA,
        ..partialEtaSq = NA,
        ..effectSizeCi = NA,
        ..ciWidth = NA,
        ..homogeneityCorrection = NA,
        ..qqPlotResiduals = NA,
        ..residualPlots = NA,
        ..leveragePlots = NA,
        ..influenceDiagnostics = NA,
        ..cooksDistance = NA,
        ..mahalanobisDistance = NA,
        ..customContrasts = NA,
        ..contrastSyntax = NA,
        ..plannedContrasts = NA,
        ..polynomialContrasts = NA,
        ..repeatedContrasts = NA,
        ..helmertContrasts = NA,
        ..differenceContrasts = NA,
        ..deviationContrasts = NA,
        ..contrastCi = NA,
        ..contrastCohensD = NA,
        ..orderRestricted = NA,
        ..orderRestrictedSyntax = NA,
        ..multipleHypothesisModels = NA,
        ..modelComparison = NA,
        ..referenceModel = NA,
        ..weightRatios = NA,
        ..relativeWeightsMatrix = NA,
        ..compareModelCoefficients = NA,
        ..informedHypothesisTests = NA,
        ..heterogeneityCorrection = NA,
        ..bootstrapCi = NA,
        ..bootstrapSamples = NA,
        ..postHoc = NA,
        ..postHocTukey = NA,
        ..postHocScheffe = NA,
        ..postHocBonferroni = NA,
        ..postHocHolm = NA,
        ..postHocSidak = NA,
        ..postHocGamesHowell = NA,
        ..postHocDunnett = NA,
        ..postHocCi = NA,
        ..postHocSignificantFlags = NA,
        ..postHocLetters = NA,
        ..postHocEffectSizes = NA,
        ..postHocBootstrap = NA,
        ..conditionalComparisons = NA,
        ..descriptivePlots = NA,
        ..descPlotXAxis = NA,
        ..descPlotLines = NA,
        ..descPlotSeparate = NA,
        ..descPlotError = NA,
        ..barPlots = NA,
        ..barPlotXAxis = NA,
        ..barPlotSeparate = NA,
        ..barPlotError = NA,
        ..barPlotFixZero = NA,
        ..raincloudPlots = NA,
        ..raincloudXAxis = NA,
        ..raincloudSeparate = NA,
        ..raincloudHorizontal = NA,
        ..marginalMeans = NA,
        ..marginalMeanTerms = NA,
        ..marginalMeansTable = NA,
        ..marginalMeansPairwise = NA,
        ..marginalMeansCi = NA,
        ..marginalMeansCompareZero = NA,
        ..marginalMeansCiAdjustment = NA,
        ..simpleEffects = NA,
        ..simpleEffectFactor = NA,
        ..moderatorFactor1 = NA,
        ..moderatorFactor2 = NA,
        ..simpleEffectsTables = NA,
        ..simpleEffectsPostHoc = NA,
        ..simpleEffectsCi = NA,
        ..simpleEffectsEffectSizes = NA,
        ..kruskalWallis = NA,
        ..kruskalEpsilonSq = NA,
        ..kruskalEtaSq = NA,
        ..kruskalCi = NA,
        ..dunnPostHoc = NA,
        ..saveResiduals = NA,
        ..saveRawResiduals = NA,
        ..saveStudentizedResiduals = NA,
        ..saveStandardizedResiduals = NA,
        ..residualColumnName = NA,
        ..residsOV = NA,
        ..studentizedResidsOV = NA,
        ..standardizedResidsOV = NA,
        ..savePredictions = NA,
        ..predictionColumnName = NA,
        ..predictOV = NA,
        ..apaReport = NA,
        ..apaTables = NA,
        ..copyReadyReport = NA,
        ..teachingMode = NA,
        ..explainStatistics = NA,
        ..effectSizeInterpretation = NA,
        ..assumptionGuidance = NA,
        ..assumptionRemedies = NA,
        ..publicationMode = NA,
        ..publicationTables = NA,
        ..publicationFigures = NA,
        ..exportWord = NA,
        ..exportPdf = NA,
        ..analysisSyntaxExport = NA,
        ..rSyntaxExport = NA,
        ..saveAnalysisConfiguration = NA)
)

enhancedAnovaResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "enhancedAnovaResults",
    inherit = jmvcore::Group,
    active = list(
        status = function() private$.items[["status"]],
        modelSummary = function() private$.items[["modelSummary"]],
        descriptivesSection = function() private$.items[["descriptivesSection"]],
        effectSizesSection = function() private$.items[["effectSizesSection"]],
        assumptionsSection = function() private$.items[["assumptionsSection"]],
        contrasts = function() private$.items[["contrasts"]],
        orderRestrictions = function() private$.items[["orderRestrictions"]],
        postHocSection = function() private$.items[["postHocSection"]],
        marginalMeansSection = function() private$.items[["marginalMeansSection"]],
        simpleEffectsSection = function() private$.items[["simpleEffectsSection"]],
        nonparametric = function() private$.items[["nonparametric"]],
        plots = function() private$.items[["plots"]],
        qqPlot = function() private$.items[["qqPlot"]],
        residualPlot = function() private$.items[["residualPlot"]],
        raincloudPlot = function() private$.items[["raincloudPlot"]],
        savedColumns = function() private$.items[["savedColumns"]],
        residsOV = function() private$.items[["residsOV"]],
        studentizedResidsOV = function() private$.items[["studentizedResidsOV"]],
        standardizedResidsOV = function() private$.items[["standardizedResidsOV"]],
        predictOV = function() private$.items[["predictOV"]],
        apa = function() private$.items[["apa"]],
        teaching = function() private$.items[["teaching"]],
        publication = function() private$.items[["publication"]],
        reproducibility = function() private$.items[["reproducibility"]],
        about = function() private$.items[["about"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="JASP Enhanced ANOVA")
            self$add(jmvcore::Html$new(
                options=options,
                name="status",
                title="Implementation Status"))
            self$add(jmvcore::Html$new(
                options=options,
                name="modelSummary",
                title="Model Summary"))
            self$add(jmvcore::Html$new(
                options=options,
                name="descriptivesSection",
                title="Descriptive Statistics",
                visible="(descriptives)"))
            self$add(jmvcore::Html$new(
                options=options,
                name="effectSizesSection",
                title="Effect Sizes"))
            self$add(jmvcore::Html$new(
                options=options,
                name="assumptionsSection",
                title="Assumption Checks and Diagnostics"))
            self$add(jmvcore::Html$new(
                options=options,
                name="contrasts",
                title="Contrasts"))
            self$add(jmvcore::Html$new(
                options=options,
                name="orderRestrictions",
                title="Bayesian and Order Restricted Hypotheses"))
            self$add(jmvcore::Html$new(
                options=options,
                name="postHocSection",
                title="Post Hoc Tests",
                visible="(postHoc)"))
            self$add(jmvcore::Html$new(
                options=options,
                name="marginalMeansSection",
                title="Estimated Marginal Means",
                visible="(marginalMeans)"))
            self$add(jmvcore::Html$new(
                options=options,
                name="simpleEffectsSection",
                title="Simple Main Effects",
                visible="(simpleEffects)"))
            self$add(jmvcore::Html$new(
                options=options,
                name="nonparametric",
                title="Nonparametric Alternatives",
                visible="(kruskalWallis)"))
            self$add(jmvcore::Html$new(
                options=options,
                name="plots",
                title="Plots"))
            self$add(jmvcore::Image$new(
                options=options,
                name="qqPlot",
                title="Q-Q Plot of Residuals",
                visible="(qqPlotResiduals)",
                width=520,
                height=420,
                renderFun=".qqPlot"))
            self$add(jmvcore::Image$new(
                options=options,
                name="residualPlot",
                title="Residual Plot",
                visible="(residualPlots)",
                width=520,
                height=420,
                renderFun=".residualPlot"))
            self$add(jmvcore::Image$new(
                options=options,
                name="raincloudPlot",
                title="Raincloud Plot",
                visible="(raincloudPlots)",
                width=640,
                height=440,
                renderFun=".raincloudPlot"))
            self$add(jmvcore::Html$new(
                options=options,
                name="savedColumns",
                title="Saved Dataset Columns"))
            self$add(jmvcore::Output$new(
                options=options,
                name="residsOV",
                title="Residuals",
                varTitle="Residuals",
                varDescription="Residuals from JASP Enhanced ANOVA",
                measureType="continuous",
                clearWith=list(
                    "dependent",
                    "fixedFactors",
                    "covariates")))
            self$add(jmvcore::Output$new(
                options=options,
                name="studentizedResidsOV",
                title="Studentized residuals",
                varTitle="Studentized residuals",
                varDescription="Studentized residuals from JASP Enhanced ANOVA",
                measureType="continuous",
                clearWith=list(
                    "dependent",
                    "fixedFactors",
                    "covariates")))
            self$add(jmvcore::Output$new(
                options=options,
                name="standardizedResidsOV",
                title="Standardized residuals",
                varTitle="Standardized residuals",
                varDescription="Standardized residuals from JASP Enhanced ANOVA",
                measureType="continuous",
                clearWith=list(
                    "dependent",
                    "fixedFactors",
                    "covariates")))
            self$add(jmvcore::Output$new(
                options=options,
                name="predictOV",
                title="Predicted values",
                varTitle="Predicted values",
                varDescription="Predicted values from JASP Enhanced ANOVA",
                measureType="continuous",
                clearWith=list(
                    "dependent",
                    "fixedFactors",
                    "covariates")))
            self$add(jmvcore::Html$new(
                options=options,
                name="apa",
                title="APA Reporting",
                visible="(apaReport)"))
            self$add(jmvcore::Html$new(
                options=options,
                name="teaching",
                title="Teaching Mode",
                visible="(teachingMode)"))
            self$add(jmvcore::Html$new(
                options=options,
                name="publication",
                title="Publication Mode",
                visible="(publicationMode)"))
            self$add(jmvcore::Html$new(
                options=options,
                name="reproducibility",
                title="Reproducibility"))
            self$add(jmvcore::Html$new(
                options=options,
                name="about",
                title="About and Citation"))}))

enhancedAnovaBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "enhancedAnovaBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "jaspEnhancedAnova",
                name = "enhancedAnova",
                version = c(0,1,0),
                options = options,
                results = enhancedAnovaResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'none')
        }))

#' JASP Enhanced ANOVA
#'
#' jamovi-native shell for the full JASP classical ANOVA option surface, 
#' including planned feature parity for corrections, contrasts, post hoc 
#' tests, plots, marginal means, simple effects, nonparametric alternatives, 
#' export functions, APA reporting, teaching mode, and reproducibility.
#' 
#' @param data .
#' @param dependent .
#' @param fixedFactors .
#' @param covariates .
#' @param randomFactors .
#' @param wlsWeights .
#' @param descriptives .
#' @param vovkSellke .
#' @param omegaSq .
#' @param partialOmegaSq .
#' @param etaSq .
#' @param partialEtaSq .
#' @param effectSizeCi .
#' @param ciWidth .
#' @param homogeneityCorrection .
#' @param qqPlotResiduals .
#' @param residualPlots .
#' @param leveragePlots .
#' @param influenceDiagnostics .
#' @param cooksDistance .
#' @param mahalanobisDistance .
#' @param customContrasts .
#' @param contrastSyntax .
#' @param plannedContrasts .
#' @param polynomialContrasts .
#' @param repeatedContrasts .
#' @param helmertContrasts .
#' @param differenceContrasts .
#' @param deviationContrasts .
#' @param contrastCi .
#' @param contrastCohensD .
#' @param orderRestricted .
#' @param orderRestrictedSyntax .
#' @param multipleHypothesisModels .
#' @param modelComparison .
#' @param referenceModel .
#' @param weightRatios .
#' @param relativeWeightsMatrix .
#' @param compareModelCoefficients .
#' @param informedHypothesisTests .
#' @param heterogeneityCorrection .
#' @param bootstrapCi .
#' @param bootstrapSamples .
#' @param postHoc .
#' @param postHocTukey .
#' @param postHocScheffe .
#' @param postHocBonferroni .
#' @param postHocHolm .
#' @param postHocSidak .
#' @param postHocGamesHowell .
#' @param postHocDunnett .
#' @param postHocCi .
#' @param postHocSignificantFlags .
#' @param postHocLetters .
#' @param postHocEffectSizes .
#' @param postHocBootstrap .
#' @param conditionalComparisons .
#' @param descriptivePlots .
#' @param descPlotXAxis .
#' @param descPlotLines .
#' @param descPlotSeparate .
#' @param descPlotError .
#' @param barPlots .
#' @param barPlotXAxis .
#' @param barPlotSeparate .
#' @param barPlotError .
#' @param barPlotFixZero .
#' @param raincloudPlots .
#' @param raincloudXAxis .
#' @param raincloudSeparate .
#' @param raincloudHorizontal .
#' @param marginalMeans .
#' @param marginalMeanTerms .
#' @param marginalMeansTable .
#' @param marginalMeansPairwise .
#' @param marginalMeansCi .
#' @param marginalMeansCompareZero .
#' @param marginalMeansCiAdjustment .
#' @param simpleEffects .
#' @param simpleEffectFactor .
#' @param moderatorFactor1 .
#' @param moderatorFactor2 .
#' @param simpleEffectsTables .
#' @param simpleEffectsPostHoc .
#' @param simpleEffectsCi .
#' @param simpleEffectsEffectSizes .
#' @param kruskalWallis .
#' @param kruskalEpsilonSq .
#' @param kruskalEtaSq .
#' @param kruskalCi .
#' @param dunnPostHoc .
#' @param saveResiduals .
#' @param saveRawResiduals .
#' @param saveStudentizedResiduals .
#' @param saveStandardizedResiduals .
#' @param residualColumnName .
#' @param savePredictions .
#' @param predictionColumnName .
#' @param apaReport .
#' @param apaTables .
#' @param copyReadyReport .
#' @param teachingMode .
#' @param explainStatistics .
#' @param effectSizeInterpretation .
#' @param assumptionGuidance .
#' @param assumptionRemedies .
#' @param publicationMode .
#' @param publicationTables .
#' @param publicationFigures .
#' @param exportWord .
#' @param exportPdf .
#' @param analysisSyntaxExport .
#' @param rSyntaxExport .
#' @param saveAnalysisConfiguration .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$status} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$modelSummary} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$descriptivesSection} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$effectSizesSection} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$assumptionsSection} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$contrasts} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$orderRestrictions} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$postHocSection} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$marginalMeansSection} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$simpleEffectsSection} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$nonparametric} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$plots} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$qqPlot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$residualPlot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$raincloudPlot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$savedColumns} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$residsOV} \tab \tab \tab \tab \tab an output \cr
#'   \code{results$studentizedResidsOV} \tab \tab \tab \tab \tab an output \cr
#'   \code{results$standardizedResidsOV} \tab \tab \tab \tab \tab an output \cr
#'   \code{results$predictOV} \tab \tab \tab \tab \tab an output \cr
#'   \code{results$apa} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$teaching} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$publication} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$reproducibility} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$about} \tab \tab \tab \tab \tab a html \cr
#' }
#'
#' @export
enhancedAnova <- function(
    data,
    dependent,
    fixedFactors,
    covariates,
    randomFactors,
    wlsWeights,
    descriptives = TRUE,
    vovkSellke = FALSE,
    omegaSq = TRUE,
    partialOmegaSq = FALSE,
    etaSq = TRUE,
    partialEtaSq = TRUE,
    effectSizeCi = FALSE,
    ciWidth = 95,
    homogeneityCorrection = "none",
    qqPlotResiduals = FALSE,
    residualPlots = FALSE,
    leveragePlots = FALSE,
    influenceDiagnostics = FALSE,
    cooksDistance = FALSE,
    mahalanobisDistance = FALSE,
    customContrasts = FALSE,
    contrastSyntax = "",
    plannedContrasts = FALSE,
    polynomialContrasts = FALSE,
    repeatedContrasts = FALSE,
    helmertContrasts = FALSE,
    differenceContrasts = FALSE,
    deviationContrasts = FALSE,
    contrastCi = TRUE,
    contrastCohensD = FALSE,
    orderRestricted = FALSE,
    orderRestrictedSyntax = "",
    multipleHypothesisModels = FALSE,
    modelComparison = FALSE,
    referenceModel = "unconstrained",
    weightRatios = FALSE,
    relativeWeightsMatrix = FALSE,
    compareModelCoefficients = FALSE,
    informedHypothesisTests = FALSE,
    heterogeneityCorrection = FALSE,
    bootstrapCi = FALSE,
    bootstrapSamples = 1000,
    postHoc = FALSE,
    postHocTukey = TRUE,
    postHocScheffe = FALSE,
    postHocBonferroni = FALSE,
    postHocHolm = FALSE,
    postHocSidak = FALSE,
    postHocGamesHowell = FALSE,
    postHocDunnett = FALSE,
    postHocCi = TRUE,
    postHocSignificantFlags = TRUE,
    postHocLetters = FALSE,
    postHocEffectSizes = FALSE,
    postHocBootstrap = FALSE,
    conditionalComparisons = FALSE,
    descriptivePlots = FALSE,
    descPlotXAxis,
    descPlotLines,
    descPlotSeparate,
    descPlotError = "ci",
    barPlots = FALSE,
    barPlotXAxis,
    barPlotSeparate,
    barPlotError = "ci",
    barPlotFixZero = FALSE,
    raincloudPlots = FALSE,
    raincloudXAxis,
    raincloudSeparate,
    raincloudHorizontal = FALSE,
    marginalMeans = FALSE,
    marginalMeanTerms,
    marginalMeansTable = TRUE,
    marginalMeansPairwise = FALSE,
    marginalMeansCi = TRUE,
    marginalMeansCompareZero = FALSE,
    marginalMeansCiAdjustment = "none",
    simpleEffects = FALSE,
    simpleEffectFactor,
    moderatorFactor1,
    moderatorFactor2,
    simpleEffectsTables = TRUE,
    simpleEffectsPostHoc = FALSE,
    simpleEffectsCi = TRUE,
    simpleEffectsEffectSizes = FALSE,
    kruskalWallis = FALSE,
    kruskalEpsilonSq = TRUE,
    kruskalEtaSq = FALSE,
    kruskalCi = FALSE,
    dunnPostHoc = FALSE,
    saveResiduals = FALSE,
    saveRawResiduals = TRUE,
    saveStudentizedResiduals = FALSE,
    saveStandardizedResiduals = FALSE,
    residualColumnName = "anova_residuals",
    savePredictions = FALSE,
    predictionColumnName = "anova_predictions",
    apaReport = TRUE,
    apaTables = TRUE,
    copyReadyReport = FALSE,
    teachingMode = FALSE,
    explainStatistics = FALSE,
    effectSizeInterpretation = FALSE,
    assumptionGuidance = FALSE,
    assumptionRemedies = FALSE,
    publicationMode = FALSE,
    publicationTables = FALSE,
    publicationFigures = FALSE,
    exportWord = FALSE,
    exportPdf = FALSE,
    analysisSyntaxExport = FALSE,
    rSyntaxExport = FALSE,
    saveAnalysisConfiguration = FALSE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("enhancedAnova requires jmvcore to be installed (restart may be required)")

    if ( ! missing(dependent)) dependent <- jmvcore::resolveQuo(jmvcore::enquo(dependent))
    if ( ! missing(fixedFactors)) fixedFactors <- jmvcore::resolveQuo(jmvcore::enquo(fixedFactors))
    if ( ! missing(covariates)) covariates <- jmvcore::resolveQuo(jmvcore::enquo(covariates))
    if ( ! missing(randomFactors)) randomFactors <- jmvcore::resolveQuo(jmvcore::enquo(randomFactors))
    if ( ! missing(wlsWeights)) wlsWeights <- jmvcore::resolveQuo(jmvcore::enquo(wlsWeights))
    if ( ! missing(descPlotXAxis)) descPlotXAxis <- jmvcore::resolveQuo(jmvcore::enquo(descPlotXAxis))
    if ( ! missing(descPlotLines)) descPlotLines <- jmvcore::resolveQuo(jmvcore::enquo(descPlotLines))
    if ( ! missing(descPlotSeparate)) descPlotSeparate <- jmvcore::resolveQuo(jmvcore::enquo(descPlotSeparate))
    if ( ! missing(barPlotXAxis)) barPlotXAxis <- jmvcore::resolveQuo(jmvcore::enquo(barPlotXAxis))
    if ( ! missing(barPlotSeparate)) barPlotSeparate <- jmvcore::resolveQuo(jmvcore::enquo(barPlotSeparate))
    if ( ! missing(raincloudXAxis)) raincloudXAxis <- jmvcore::resolveQuo(jmvcore::enquo(raincloudXAxis))
    if ( ! missing(raincloudSeparate)) raincloudSeparate <- jmvcore::resolveQuo(jmvcore::enquo(raincloudSeparate))
    if ( ! missing(marginalMeanTerms)) marginalMeanTerms <- jmvcore::resolveQuo(jmvcore::enquo(marginalMeanTerms))
    if ( ! missing(simpleEffectFactor)) simpleEffectFactor <- jmvcore::resolveQuo(jmvcore::enquo(simpleEffectFactor))
    if ( ! missing(moderatorFactor1)) moderatorFactor1 <- jmvcore::resolveQuo(jmvcore::enquo(moderatorFactor1))
    if ( ! missing(moderatorFactor2)) moderatorFactor2 <- jmvcore::resolveQuo(jmvcore::enquo(moderatorFactor2))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(dependent), dependent, NULL),
            `if`( ! missing(fixedFactors), fixedFactors, NULL),
            `if`( ! missing(covariates), covariates, NULL),
            `if`( ! missing(randomFactors), randomFactors, NULL),
            `if`( ! missing(wlsWeights), wlsWeights, NULL),
            `if`( ! missing(descPlotXAxis), descPlotXAxis, NULL),
            `if`( ! missing(descPlotLines), descPlotLines, NULL),
            `if`( ! missing(descPlotSeparate), descPlotSeparate, NULL),
            `if`( ! missing(barPlotXAxis), barPlotXAxis, NULL),
            `if`( ! missing(barPlotSeparate), barPlotSeparate, NULL),
            `if`( ! missing(raincloudXAxis), raincloudXAxis, NULL),
            `if`( ! missing(raincloudSeparate), raincloudSeparate, NULL),
            `if`( ! missing(marginalMeanTerms), marginalMeanTerms, NULL),
            `if`( ! missing(simpleEffectFactor), simpleEffectFactor, NULL),
            `if`( ! missing(moderatorFactor1), moderatorFactor1, NULL),
            `if`( ! missing(moderatorFactor2), moderatorFactor2, NULL))

    for (v in fixedFactors) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    for (v in randomFactors) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    for (v in descPlotXAxis) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    for (v in descPlotLines) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    for (v in descPlotSeparate) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    for (v in barPlotXAxis) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    for (v in barPlotSeparate) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    for (v in raincloudXAxis) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    for (v in raincloudSeparate) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    for (v in marginalMeanTerms) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    for (v in simpleEffectFactor) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    for (v in moderatorFactor1) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    for (v in moderatorFactor2) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])

    options <- enhancedAnovaOptions$new(
        dependent = dependent,
        fixedFactors = fixedFactors,
        covariates = covariates,
        randomFactors = randomFactors,
        wlsWeights = wlsWeights,
        descriptives = descriptives,
        vovkSellke = vovkSellke,
        omegaSq = omegaSq,
        partialOmegaSq = partialOmegaSq,
        etaSq = etaSq,
        partialEtaSq = partialEtaSq,
        effectSizeCi = effectSizeCi,
        ciWidth = ciWidth,
        homogeneityCorrection = homogeneityCorrection,
        qqPlotResiduals = qqPlotResiduals,
        residualPlots = residualPlots,
        leveragePlots = leveragePlots,
        influenceDiagnostics = influenceDiagnostics,
        cooksDistance = cooksDistance,
        mahalanobisDistance = mahalanobisDistance,
        customContrasts = customContrasts,
        contrastSyntax = contrastSyntax,
        plannedContrasts = plannedContrasts,
        polynomialContrasts = polynomialContrasts,
        repeatedContrasts = repeatedContrasts,
        helmertContrasts = helmertContrasts,
        differenceContrasts = differenceContrasts,
        deviationContrasts = deviationContrasts,
        contrastCi = contrastCi,
        contrastCohensD = contrastCohensD,
        orderRestricted = orderRestricted,
        orderRestrictedSyntax = orderRestrictedSyntax,
        multipleHypothesisModels = multipleHypothesisModels,
        modelComparison = modelComparison,
        referenceModel = referenceModel,
        weightRatios = weightRatios,
        relativeWeightsMatrix = relativeWeightsMatrix,
        compareModelCoefficients = compareModelCoefficients,
        informedHypothesisTests = informedHypothesisTests,
        heterogeneityCorrection = heterogeneityCorrection,
        bootstrapCi = bootstrapCi,
        bootstrapSamples = bootstrapSamples,
        postHoc = postHoc,
        postHocTukey = postHocTukey,
        postHocScheffe = postHocScheffe,
        postHocBonferroni = postHocBonferroni,
        postHocHolm = postHocHolm,
        postHocSidak = postHocSidak,
        postHocGamesHowell = postHocGamesHowell,
        postHocDunnett = postHocDunnett,
        postHocCi = postHocCi,
        postHocSignificantFlags = postHocSignificantFlags,
        postHocLetters = postHocLetters,
        postHocEffectSizes = postHocEffectSizes,
        postHocBootstrap = postHocBootstrap,
        conditionalComparisons = conditionalComparisons,
        descriptivePlots = descriptivePlots,
        descPlotXAxis = descPlotXAxis,
        descPlotLines = descPlotLines,
        descPlotSeparate = descPlotSeparate,
        descPlotError = descPlotError,
        barPlots = barPlots,
        barPlotXAxis = barPlotXAxis,
        barPlotSeparate = barPlotSeparate,
        barPlotError = barPlotError,
        barPlotFixZero = barPlotFixZero,
        raincloudPlots = raincloudPlots,
        raincloudXAxis = raincloudXAxis,
        raincloudSeparate = raincloudSeparate,
        raincloudHorizontal = raincloudHorizontal,
        marginalMeans = marginalMeans,
        marginalMeanTerms = marginalMeanTerms,
        marginalMeansTable = marginalMeansTable,
        marginalMeansPairwise = marginalMeansPairwise,
        marginalMeansCi = marginalMeansCi,
        marginalMeansCompareZero = marginalMeansCompareZero,
        marginalMeansCiAdjustment = marginalMeansCiAdjustment,
        simpleEffects = simpleEffects,
        simpleEffectFactor = simpleEffectFactor,
        moderatorFactor1 = moderatorFactor1,
        moderatorFactor2 = moderatorFactor2,
        simpleEffectsTables = simpleEffectsTables,
        simpleEffectsPostHoc = simpleEffectsPostHoc,
        simpleEffectsCi = simpleEffectsCi,
        simpleEffectsEffectSizes = simpleEffectsEffectSizes,
        kruskalWallis = kruskalWallis,
        kruskalEpsilonSq = kruskalEpsilonSq,
        kruskalEtaSq = kruskalEtaSq,
        kruskalCi = kruskalCi,
        dunnPostHoc = dunnPostHoc,
        saveResiduals = saveResiduals,
        saveRawResiduals = saveRawResiduals,
        saveStudentizedResiduals = saveStudentizedResiduals,
        saveStandardizedResiduals = saveStandardizedResiduals,
        residualColumnName = residualColumnName,
        savePredictions = savePredictions,
        predictionColumnName = predictionColumnName,
        apaReport = apaReport,
        apaTables = apaTables,
        copyReadyReport = copyReadyReport,
        teachingMode = teachingMode,
        explainStatistics = explainStatistics,
        effectSizeInterpretation = effectSizeInterpretation,
        assumptionGuidance = assumptionGuidance,
        assumptionRemedies = assumptionRemedies,
        publicationMode = publicationMode,
        publicationTables = publicationTables,
        publicationFigures = publicationFigures,
        exportWord = exportWord,
        exportPdf = exportPdf,
        analysisSyntaxExport = analysisSyntaxExport,
        rSyntaxExport = rSyntaxExport,
        saveAnalysisConfiguration = saveAnalysisConfiguration)

    analysis <- enhancedAnovaClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

