
# This file is automatically generated, you probably don't want to edit this

enhancedAnovaOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "enhancedAnovaOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            dependent = NULL,
            fixedFactors = NULL,
            randomFactors = NULL,
            covariates = NULL,
            wlsWeights = NULL,
            descriptives = FALSE,
            effectSizeEstimates = FALSE,
            effectSizeOmegaSquared = TRUE,
            effectSizePartialOmegaSquared = FALSE,
            effectSizeEtaSquared = FALSE,
            effectSizePartialEtaSquared = FALSE,
            effectSizeCi = FALSE,
            effectSizeCiLevel = 95,
            vovkSellke = FALSE,
            sumOfSquares = "type3",
            homogeneityTests = FALSE,
            homogeneityCorrectionNone = TRUE,
            homogeneityCorrectionBrown = FALSE,
            homogeneityCorrectionWelch = FALSE,
            qqPlot = FALSE,
            qqPlotCi = FALSE,
            qqPlotCiLevel = 95,
            contrastType = "none",
            contrastCi = TRUE,
            contrastCiLevel = 95,
            contrastEffectSize = FALSE,
            restrictedSyntax = "",
            restrictedInterceptInclusion = FALSE,
            restrictedAvailableCoefficients = FALSE,
            restrictedModelSummaryForAllModels = FALSE,
            restrictedMarginalMeanForAllModels = FALSE,
            restrictedInformedHypothesisTestForAllModels = FALSE,
            restrictedModelComparison = "complement",
            restrictedModelComparisonWeights = TRUE,
            restrictedModelComparisonReference = "complement",
            restrictedModelComparisonMatrix = FALSE,
            restrictedModelComparisonCoefficients = FALSE,
            restrictedModelComparisonCoefficientsHighlight = TRUE,
            restrictedHeterogeneityCorrection = "none",
            restrictedBootstrap = FALSE,
            restrictedBootstrapSamples = 1000,
            restrictedBootstrapCiLevel = 95,
            restrictedMarginalMeanTerms = NULL,
            postHocTerms = NULL,
            postHocTypeStandard = TRUE,
            postHocTypeStandardBootstrap = FALSE,
            postHocTypeStandardBootstrapSamples = 1000,
            postHocTypeStandardEffectSize = FALSE,
            postHocConditionalTable = FALSE,
            postHocTypeGames = FALSE,
            postHocTypeDunnet = FALSE,
            postHocCorrectionTukey = TRUE,
            postHocCorrectionScheffe = FALSE,
            postHocCorrectionBonferroni = FALSE,
            postHocCorrectionHolm = FALSE,
            postHocCorrectionSidak = FALSE,
            postHocCorrectionFdr = FALSE,
            postHocCi = TRUE,
            postHocCiLevel = 95,
            postHocSignificanceFlag = FALSE,
            postHocLetterTable = FALSE,
            postHocLetterAlpha = 0.05,
            descriptivePlotHorizontalAxis = NULL,
            descriptivePlotSeparateLines = NULL,
            descriptivePlotSeparatePlot = NULL,
            descriptivePlotErrorBar = TRUE,
            descriptivePlotErrorBarType = "ci",
            descriptivePlotCiLevel = 95,
            barPlotHorizontalAxis = NULL,
            barPlotSeparatePlots = NULL,
            barPlotErrorBars = TRUE,
            barPlotErrorBarType = "ci",
            barPlotCiInterval = 95,
            barPlotHorizontalZeroFix = TRUE,
            rainCloudHorizontalAxis = NULL,
            rainCloudSeparatePlots = NULL,
            rainCloudHorizontalDisplay = FALSE,
            marginalMeanTerms = NULL,
            marginalMeanBootstrap = FALSE,
            marginalMeanBootstrapSamples = 1000,
            marginalMeanComparedToZero = FALSE,
            marginalMeanCiCorrection = "none",
            simpleMainEffectFactor = NULL,
            simpleMainEffectModeratorFactorOne = NULL,
            simpleMainEffectModeratorFactorTwo = NULL,
            kruskalWallisFactors = NULL,
            kruskalEffectSizeEstimates = FALSE,
            kruskalEpsilon = TRUE,
            kruskalEta = FALSE,
            kruskalCiLevel = 95,
            postHocTypeDunn = FALSE,
            residualsSavedToData = FALSE,
            residualsSavedToDataColumn = "residuals",
            residualsSavedToDataType = "raw",
            predictionsSavedToData = FALSE,
            predictionsSavedToDataColumn = "predictions", ...) {

            super$initialize(
                package="jaspEnhancedAnova",
                name="enhancedAnova",
                requiresData=TRUE,
                ...)

            private$..dependent <- jmvcore::OptionVariable$new(
                "dependent",
                dependent,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..fixedFactors <- jmvcore::OptionVariables$new(
                "fixedFactors",
                fixedFactors,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"))
            private$..randomFactors <- jmvcore::OptionVariables$new(
                "randomFactors",
                randomFactors,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"))
            private$..covariates <- jmvcore::OptionVariables$new(
                "covariates",
                covariates,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..wlsWeights <- jmvcore::OptionVariable$new(
                "wlsWeights",
                wlsWeights,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..descriptives <- jmvcore::OptionBool$new(
                "descriptives",
                descriptives,
                default=FALSE)
            private$..effectSizeEstimates <- jmvcore::OptionBool$new(
                "effectSizeEstimates",
                effectSizeEstimates,
                default=FALSE)
            private$..effectSizeOmegaSquared <- jmvcore::OptionBool$new(
                "effectSizeOmegaSquared",
                effectSizeOmegaSquared,
                default=TRUE)
            private$..effectSizePartialOmegaSquared <- jmvcore::OptionBool$new(
                "effectSizePartialOmegaSquared",
                effectSizePartialOmegaSquared,
                default=FALSE)
            private$..effectSizeEtaSquared <- jmvcore::OptionBool$new(
                "effectSizeEtaSquared",
                effectSizeEtaSquared,
                default=FALSE)
            private$..effectSizePartialEtaSquared <- jmvcore::OptionBool$new(
                "effectSizePartialEtaSquared",
                effectSizePartialEtaSquared,
                default=FALSE)
            private$..effectSizeCi <- jmvcore::OptionBool$new(
                "effectSizeCi",
                effectSizeCi,
                default=FALSE)
            private$..effectSizeCiLevel <- jmvcore::OptionNumber$new(
                "effectSizeCiLevel",
                effectSizeCiLevel,
                min=50,
                max=99.9,
                default=95)
            private$..vovkSellke <- jmvcore::OptionBool$new(
                "vovkSellke",
                vovkSellke,
                default=FALSE)
            private$..sumOfSquares <- jmvcore::OptionList$new(
                "sumOfSquares",
                sumOfSquares,
                options=list(
                    "type1",
                    "type2",
                    "type3"),
                default="type3")
            private$..homogeneityTests <- jmvcore::OptionBool$new(
                "homogeneityTests",
                homogeneityTests,
                default=FALSE)
            private$..homogeneityCorrectionNone <- jmvcore::OptionBool$new(
                "homogeneityCorrectionNone",
                homogeneityCorrectionNone,
                default=TRUE)
            private$..homogeneityCorrectionBrown <- jmvcore::OptionBool$new(
                "homogeneityCorrectionBrown",
                homogeneityCorrectionBrown,
                default=FALSE)
            private$..homogeneityCorrectionWelch <- jmvcore::OptionBool$new(
                "homogeneityCorrectionWelch",
                homogeneityCorrectionWelch,
                default=FALSE)
            private$..qqPlot <- jmvcore::OptionBool$new(
                "qqPlot",
                qqPlot,
                default=FALSE)
            private$..qqPlotCi <- jmvcore::OptionBool$new(
                "qqPlotCi",
                qqPlotCi,
                default=FALSE)
            private$..qqPlotCiLevel <- jmvcore::OptionNumber$new(
                "qqPlotCiLevel",
                qqPlotCiLevel,
                min=50,
                max=99.9,
                default=95)
            private$..contrastType <- jmvcore::OptionList$new(
                "contrastType",
                contrastType,
                options=list(
                    "none",
                    "deviation",
                    "simple",
                    "difference",
                    "helmert",
                    "repeated",
                    "polynomial"),
                default="none")
            private$..contrastCi <- jmvcore::OptionBool$new(
                "contrastCi",
                contrastCi,
                default=TRUE)
            private$..contrastCiLevel <- jmvcore::OptionNumber$new(
                "contrastCiLevel",
                contrastCiLevel,
                min=50,
                max=99.9,
                default=95)
            private$..contrastEffectSize <- jmvcore::OptionBool$new(
                "contrastEffectSize",
                contrastEffectSize,
                default=FALSE)
            private$..restrictedSyntax <- jmvcore::OptionString$new(
                "restrictedSyntax",
                restrictedSyntax,
                default="")
            private$..restrictedInterceptInclusion <- jmvcore::OptionBool$new(
                "restrictedInterceptInclusion",
                restrictedInterceptInclusion,
                default=FALSE)
            private$..restrictedAvailableCoefficients <- jmvcore::OptionBool$new(
                "restrictedAvailableCoefficients",
                restrictedAvailableCoefficients,
                default=FALSE)
            private$..restrictedModelSummaryForAllModels <- jmvcore::OptionBool$new(
                "restrictedModelSummaryForAllModels",
                restrictedModelSummaryForAllModels,
                default=FALSE)
            private$..restrictedMarginalMeanForAllModels <- jmvcore::OptionBool$new(
                "restrictedMarginalMeanForAllModels",
                restrictedMarginalMeanForAllModels,
                default=FALSE)
            private$..restrictedInformedHypothesisTestForAllModels <- jmvcore::OptionBool$new(
                "restrictedInformedHypothesisTestForAllModels",
                restrictedInformedHypothesisTestForAllModels,
                default=FALSE)
            private$..restrictedModelComparison <- jmvcore::OptionList$new(
                "restrictedModelComparison",
                restrictedModelComparison,
                options=list(
                    "complement",
                    "unconstrained",
                    "none"),
                default="complement")
            private$..restrictedModelComparisonWeights <- jmvcore::OptionBool$new(
                "restrictedModelComparisonWeights",
                restrictedModelComparisonWeights,
                default=TRUE)
            private$..restrictedModelComparisonReference <- jmvcore::OptionList$new(
                "restrictedModelComparisonReference",
                restrictedModelComparisonReference,
                options=list(
                    "complement",
                    "unconstrained"),
                default="complement")
            private$..restrictedModelComparisonMatrix <- jmvcore::OptionBool$new(
                "restrictedModelComparisonMatrix",
                restrictedModelComparisonMatrix,
                default=FALSE)
            private$..restrictedModelComparisonCoefficients <- jmvcore::OptionBool$new(
                "restrictedModelComparisonCoefficients",
                restrictedModelComparisonCoefficients,
                default=FALSE)
            private$..restrictedModelComparisonCoefficientsHighlight <- jmvcore::OptionBool$new(
                "restrictedModelComparisonCoefficientsHighlight",
                restrictedModelComparisonCoefficientsHighlight,
                default=TRUE)
            private$..restrictedHeterogeneityCorrection <- jmvcore::OptionList$new(
                "restrictedHeterogeneityCorrection",
                restrictedHeterogeneityCorrection,
                options=list(
                    "none",
                    "huberWhite0",
                    "huberWhite1",
                    "huberWhite2",
                    "huberWhite3",
                    "huberWhite4",
                    "huberWhite4m",
                    "huberWhite5"),
                default="none")
            private$..restrictedBootstrap <- jmvcore::OptionBool$new(
                "restrictedBootstrap",
                restrictedBootstrap,
                default=FALSE)
            private$..restrictedBootstrapSamples <- jmvcore::OptionInteger$new(
                "restrictedBootstrapSamples",
                restrictedBootstrapSamples,
                min=100,
                max=100000,
                default=1000)
            private$..restrictedBootstrapCiLevel <- jmvcore::OptionNumber$new(
                "restrictedBootstrapCiLevel",
                restrictedBootstrapCiLevel,
                min=50,
                max=99.9,
                default=95)
            private$..restrictedMarginalMeanTerms <- jmvcore::OptionVariables$new(
                "restrictedMarginalMeanTerms",
                restrictedMarginalMeanTerms,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"))
            private$..postHocTerms <- jmvcore::OptionVariables$new(
                "postHocTerms",
                postHocTerms,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"))
            private$..postHocTypeStandard <- jmvcore::OptionBool$new(
                "postHocTypeStandard",
                postHocTypeStandard,
                default=TRUE)
            private$..postHocTypeStandardBootstrap <- jmvcore::OptionBool$new(
                "postHocTypeStandardBootstrap",
                postHocTypeStandardBootstrap,
                default=FALSE)
            private$..postHocTypeStandardBootstrapSamples <- jmvcore::OptionInteger$new(
                "postHocTypeStandardBootstrapSamples",
                postHocTypeStandardBootstrapSamples,
                min=100,
                max=100000,
                default=1000)
            private$..postHocTypeStandardEffectSize <- jmvcore::OptionBool$new(
                "postHocTypeStandardEffectSize",
                postHocTypeStandardEffectSize,
                default=FALSE)
            private$..postHocConditionalTable <- jmvcore::OptionBool$new(
                "postHocConditionalTable",
                postHocConditionalTable,
                default=FALSE)
            private$..postHocTypeGames <- jmvcore::OptionBool$new(
                "postHocTypeGames",
                postHocTypeGames,
                default=FALSE)
            private$..postHocTypeDunnet <- jmvcore::OptionBool$new(
                "postHocTypeDunnet",
                postHocTypeDunnet,
                default=FALSE)
            private$..postHocCorrectionTukey <- jmvcore::OptionBool$new(
                "postHocCorrectionTukey",
                postHocCorrectionTukey,
                default=TRUE)
            private$..postHocCorrectionScheffe <- jmvcore::OptionBool$new(
                "postHocCorrectionScheffe",
                postHocCorrectionScheffe,
                default=FALSE)
            private$..postHocCorrectionBonferroni <- jmvcore::OptionBool$new(
                "postHocCorrectionBonferroni",
                postHocCorrectionBonferroni,
                default=FALSE)
            private$..postHocCorrectionHolm <- jmvcore::OptionBool$new(
                "postHocCorrectionHolm",
                postHocCorrectionHolm,
                default=FALSE)
            private$..postHocCorrectionSidak <- jmvcore::OptionBool$new(
                "postHocCorrectionSidak",
                postHocCorrectionSidak,
                default=FALSE)
            private$..postHocCorrectionFdr <- jmvcore::OptionBool$new(
                "postHocCorrectionFdr",
                postHocCorrectionFdr,
                default=FALSE)
            private$..postHocCi <- jmvcore::OptionBool$new(
                "postHocCi",
                postHocCi,
                default=TRUE)
            private$..postHocCiLevel <- jmvcore::OptionNumber$new(
                "postHocCiLevel",
                postHocCiLevel,
                min=50,
                max=99.9,
                default=95)
            private$..postHocSignificanceFlag <- jmvcore::OptionBool$new(
                "postHocSignificanceFlag",
                postHocSignificanceFlag,
                default=FALSE)
            private$..postHocLetterTable <- jmvcore::OptionBool$new(
                "postHocLetterTable",
                postHocLetterTable,
                default=FALSE)
            private$..postHocLetterAlpha <- jmvcore::OptionNumber$new(
                "postHocLetterAlpha",
                postHocLetterAlpha,
                min=0,
                max=1,
                default=0.05)
            private$..descriptivePlotHorizontalAxis <- jmvcore::OptionVariable$new(
                "descriptivePlotHorizontalAxis",
                descriptivePlotHorizontalAxis,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"))
            private$..descriptivePlotSeparateLines <- jmvcore::OptionVariable$new(
                "descriptivePlotSeparateLines",
                descriptivePlotSeparateLines,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"))
            private$..descriptivePlotSeparatePlot <- jmvcore::OptionVariable$new(
                "descriptivePlotSeparatePlot",
                descriptivePlotSeparatePlot,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"))
            private$..descriptivePlotErrorBar <- jmvcore::OptionBool$new(
                "descriptivePlotErrorBar",
                descriptivePlotErrorBar,
                default=TRUE)
            private$..descriptivePlotErrorBarType <- jmvcore::OptionList$new(
                "descriptivePlotErrorBarType",
                descriptivePlotErrorBarType,
                options=list(
                    "ci",
                    "se"),
                default="ci")
            private$..descriptivePlotCiLevel <- jmvcore::OptionNumber$new(
                "descriptivePlotCiLevel",
                descriptivePlotCiLevel,
                min=50,
                max=99.9,
                default=95)
            private$..barPlotHorizontalAxis <- jmvcore::OptionVariable$new(
                "barPlotHorizontalAxis",
                barPlotHorizontalAxis,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"))
            private$..barPlotSeparatePlots <- jmvcore::OptionVariable$new(
                "barPlotSeparatePlots",
                barPlotSeparatePlots,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"))
            private$..barPlotErrorBars <- jmvcore::OptionBool$new(
                "barPlotErrorBars",
                barPlotErrorBars,
                default=TRUE)
            private$..barPlotErrorBarType <- jmvcore::OptionList$new(
                "barPlotErrorBarType",
                barPlotErrorBarType,
                options=list(
                    "ci",
                    "se"),
                default="ci")
            private$..barPlotCiInterval <- jmvcore::OptionNumber$new(
                "barPlotCiInterval",
                barPlotCiInterval,
                min=50,
                max=99.9,
                default=95)
            private$..barPlotHorizontalZeroFix <- jmvcore::OptionBool$new(
                "barPlotHorizontalZeroFix",
                barPlotHorizontalZeroFix,
                default=TRUE)
            private$..rainCloudHorizontalAxis <- jmvcore::OptionVariable$new(
                "rainCloudHorizontalAxis",
                rainCloudHorizontalAxis,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"))
            private$..rainCloudSeparatePlots <- jmvcore::OptionVariable$new(
                "rainCloudSeparatePlots",
                rainCloudSeparatePlots,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"))
            private$..rainCloudHorizontalDisplay <- jmvcore::OptionBool$new(
                "rainCloudHorizontalDisplay",
                rainCloudHorizontalDisplay,
                default=FALSE)
            private$..marginalMeanTerms <- jmvcore::OptionVariables$new(
                "marginalMeanTerms",
                marginalMeanTerms,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"))
            private$..marginalMeanBootstrap <- jmvcore::OptionBool$new(
                "marginalMeanBootstrap",
                marginalMeanBootstrap,
                default=FALSE)
            private$..marginalMeanBootstrapSamples <- jmvcore::OptionInteger$new(
                "marginalMeanBootstrapSamples",
                marginalMeanBootstrapSamples,
                min=100,
                max=100000,
                default=1000)
            private$..marginalMeanComparedToZero <- jmvcore::OptionBool$new(
                "marginalMeanComparedToZero",
                marginalMeanComparedToZero,
                default=FALSE)
            private$..marginalMeanCiCorrection <- jmvcore::OptionList$new(
                "marginalMeanCiCorrection",
                marginalMeanCiCorrection,
                options=list(
                    "none",
                    "bonferroni",
                    "sidak"),
                default="none")
            private$..simpleMainEffectFactor <- jmvcore::OptionVariable$new(
                "simpleMainEffectFactor",
                simpleMainEffectFactor,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"))
            private$..simpleMainEffectModeratorFactorOne <- jmvcore::OptionVariable$new(
                "simpleMainEffectModeratorFactorOne",
                simpleMainEffectModeratorFactorOne,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"))
            private$..simpleMainEffectModeratorFactorTwo <- jmvcore::OptionVariable$new(
                "simpleMainEffectModeratorFactorTwo",
                simpleMainEffectModeratorFactorTwo,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"))
            private$..kruskalWallisFactors <- jmvcore::OptionVariables$new(
                "kruskalWallisFactors",
                kruskalWallisFactors,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"))
            private$..kruskalEffectSizeEstimates <- jmvcore::OptionBool$new(
                "kruskalEffectSizeEstimates",
                kruskalEffectSizeEstimates,
                default=FALSE)
            private$..kruskalEpsilon <- jmvcore::OptionBool$new(
                "kruskalEpsilon",
                kruskalEpsilon,
                default=TRUE)
            private$..kruskalEta <- jmvcore::OptionBool$new(
                "kruskalEta",
                kruskalEta,
                default=FALSE)
            private$..kruskalCiLevel <- jmvcore::OptionNumber$new(
                "kruskalCiLevel",
                kruskalCiLevel,
                min=50,
                max=99.9,
                default=95)
            private$..postHocTypeDunn <- jmvcore::OptionBool$new(
                "postHocTypeDunn",
                postHocTypeDunn,
                default=FALSE)
            private$..residualsSavedToData <- jmvcore::OptionBool$new(
                "residualsSavedToData",
                residualsSavedToData,
                default=FALSE)
            private$..residualsSavedToDataColumn <- jmvcore::OptionString$new(
                "residualsSavedToDataColumn",
                residualsSavedToDataColumn,
                default="residuals")
            private$..residualsSavedToDataType <- jmvcore::OptionList$new(
                "residualsSavedToDataType",
                residualsSavedToDataType,
                options=list(
                    "raw",
                    "standard",
                    "student"),
                default="raw")
            private$..predictionsSavedToData <- jmvcore::OptionBool$new(
                "predictionsSavedToData",
                predictionsSavedToData,
                default=FALSE)
            private$..predictionsSavedToDataColumn <- jmvcore::OptionString$new(
                "predictionsSavedToDataColumn",
                predictionsSavedToDataColumn,
                default="predictions")
            private$..residsOV <- jmvcore::OptionOutput$new(
                "residsOV")
            private$..predictOV <- jmvcore::OptionOutput$new(
                "predictOV")

            self$.addOption(private$..dependent)
            self$.addOption(private$..fixedFactors)
            self$.addOption(private$..randomFactors)
            self$.addOption(private$..covariates)
            self$.addOption(private$..wlsWeights)
            self$.addOption(private$..descriptives)
            self$.addOption(private$..effectSizeEstimates)
            self$.addOption(private$..effectSizeOmegaSquared)
            self$.addOption(private$..effectSizePartialOmegaSquared)
            self$.addOption(private$..effectSizeEtaSquared)
            self$.addOption(private$..effectSizePartialEtaSquared)
            self$.addOption(private$..effectSizeCi)
            self$.addOption(private$..effectSizeCiLevel)
            self$.addOption(private$..vovkSellke)
            self$.addOption(private$..sumOfSquares)
            self$.addOption(private$..homogeneityTests)
            self$.addOption(private$..homogeneityCorrectionNone)
            self$.addOption(private$..homogeneityCorrectionBrown)
            self$.addOption(private$..homogeneityCorrectionWelch)
            self$.addOption(private$..qqPlot)
            self$.addOption(private$..qqPlotCi)
            self$.addOption(private$..qqPlotCiLevel)
            self$.addOption(private$..contrastType)
            self$.addOption(private$..contrastCi)
            self$.addOption(private$..contrastCiLevel)
            self$.addOption(private$..contrastEffectSize)
            self$.addOption(private$..restrictedSyntax)
            self$.addOption(private$..restrictedInterceptInclusion)
            self$.addOption(private$..restrictedAvailableCoefficients)
            self$.addOption(private$..restrictedModelSummaryForAllModels)
            self$.addOption(private$..restrictedMarginalMeanForAllModels)
            self$.addOption(private$..restrictedInformedHypothesisTestForAllModels)
            self$.addOption(private$..restrictedModelComparison)
            self$.addOption(private$..restrictedModelComparisonWeights)
            self$.addOption(private$..restrictedModelComparisonReference)
            self$.addOption(private$..restrictedModelComparisonMatrix)
            self$.addOption(private$..restrictedModelComparisonCoefficients)
            self$.addOption(private$..restrictedModelComparisonCoefficientsHighlight)
            self$.addOption(private$..restrictedHeterogeneityCorrection)
            self$.addOption(private$..restrictedBootstrap)
            self$.addOption(private$..restrictedBootstrapSamples)
            self$.addOption(private$..restrictedBootstrapCiLevel)
            self$.addOption(private$..restrictedMarginalMeanTerms)
            self$.addOption(private$..postHocTerms)
            self$.addOption(private$..postHocTypeStandard)
            self$.addOption(private$..postHocTypeStandardBootstrap)
            self$.addOption(private$..postHocTypeStandardBootstrapSamples)
            self$.addOption(private$..postHocTypeStandardEffectSize)
            self$.addOption(private$..postHocConditionalTable)
            self$.addOption(private$..postHocTypeGames)
            self$.addOption(private$..postHocTypeDunnet)
            self$.addOption(private$..postHocCorrectionTukey)
            self$.addOption(private$..postHocCorrectionScheffe)
            self$.addOption(private$..postHocCorrectionBonferroni)
            self$.addOption(private$..postHocCorrectionHolm)
            self$.addOption(private$..postHocCorrectionSidak)
            self$.addOption(private$..postHocCorrectionFdr)
            self$.addOption(private$..postHocCi)
            self$.addOption(private$..postHocCiLevel)
            self$.addOption(private$..postHocSignificanceFlag)
            self$.addOption(private$..postHocLetterTable)
            self$.addOption(private$..postHocLetterAlpha)
            self$.addOption(private$..descriptivePlotHorizontalAxis)
            self$.addOption(private$..descriptivePlotSeparateLines)
            self$.addOption(private$..descriptivePlotSeparatePlot)
            self$.addOption(private$..descriptivePlotErrorBar)
            self$.addOption(private$..descriptivePlotErrorBarType)
            self$.addOption(private$..descriptivePlotCiLevel)
            self$.addOption(private$..barPlotHorizontalAxis)
            self$.addOption(private$..barPlotSeparatePlots)
            self$.addOption(private$..barPlotErrorBars)
            self$.addOption(private$..barPlotErrorBarType)
            self$.addOption(private$..barPlotCiInterval)
            self$.addOption(private$..barPlotHorizontalZeroFix)
            self$.addOption(private$..rainCloudHorizontalAxis)
            self$.addOption(private$..rainCloudSeparatePlots)
            self$.addOption(private$..rainCloudHorizontalDisplay)
            self$.addOption(private$..marginalMeanTerms)
            self$.addOption(private$..marginalMeanBootstrap)
            self$.addOption(private$..marginalMeanBootstrapSamples)
            self$.addOption(private$..marginalMeanComparedToZero)
            self$.addOption(private$..marginalMeanCiCorrection)
            self$.addOption(private$..simpleMainEffectFactor)
            self$.addOption(private$..simpleMainEffectModeratorFactorOne)
            self$.addOption(private$..simpleMainEffectModeratorFactorTwo)
            self$.addOption(private$..kruskalWallisFactors)
            self$.addOption(private$..kruskalEffectSizeEstimates)
            self$.addOption(private$..kruskalEpsilon)
            self$.addOption(private$..kruskalEta)
            self$.addOption(private$..kruskalCiLevel)
            self$.addOption(private$..postHocTypeDunn)
            self$.addOption(private$..residualsSavedToData)
            self$.addOption(private$..residualsSavedToDataColumn)
            self$.addOption(private$..residualsSavedToDataType)
            self$.addOption(private$..predictionsSavedToData)
            self$.addOption(private$..predictionsSavedToDataColumn)
            self$.addOption(private$..residsOV)
            self$.addOption(private$..predictOV)
        }),
    active = list(
        dependent = function() private$..dependent$value,
        fixedFactors = function() private$..fixedFactors$value,
        randomFactors = function() private$..randomFactors$value,
        covariates = function() private$..covariates$value,
        wlsWeights = function() private$..wlsWeights$value,
        descriptives = function() private$..descriptives$value,
        effectSizeEstimates = function() private$..effectSizeEstimates$value,
        effectSizeOmegaSquared = function() private$..effectSizeOmegaSquared$value,
        effectSizePartialOmegaSquared = function() private$..effectSizePartialOmegaSquared$value,
        effectSizeEtaSquared = function() private$..effectSizeEtaSquared$value,
        effectSizePartialEtaSquared = function() private$..effectSizePartialEtaSquared$value,
        effectSizeCi = function() private$..effectSizeCi$value,
        effectSizeCiLevel = function() private$..effectSizeCiLevel$value,
        vovkSellke = function() private$..vovkSellke$value,
        sumOfSquares = function() private$..sumOfSquares$value,
        homogeneityTests = function() private$..homogeneityTests$value,
        homogeneityCorrectionNone = function() private$..homogeneityCorrectionNone$value,
        homogeneityCorrectionBrown = function() private$..homogeneityCorrectionBrown$value,
        homogeneityCorrectionWelch = function() private$..homogeneityCorrectionWelch$value,
        qqPlot = function() private$..qqPlot$value,
        qqPlotCi = function() private$..qqPlotCi$value,
        qqPlotCiLevel = function() private$..qqPlotCiLevel$value,
        contrastType = function() private$..contrastType$value,
        contrastCi = function() private$..contrastCi$value,
        contrastCiLevel = function() private$..contrastCiLevel$value,
        contrastEffectSize = function() private$..contrastEffectSize$value,
        restrictedSyntax = function() private$..restrictedSyntax$value,
        restrictedInterceptInclusion = function() private$..restrictedInterceptInclusion$value,
        restrictedAvailableCoefficients = function() private$..restrictedAvailableCoefficients$value,
        restrictedModelSummaryForAllModels = function() private$..restrictedModelSummaryForAllModels$value,
        restrictedMarginalMeanForAllModels = function() private$..restrictedMarginalMeanForAllModels$value,
        restrictedInformedHypothesisTestForAllModels = function() private$..restrictedInformedHypothesisTestForAllModels$value,
        restrictedModelComparison = function() private$..restrictedModelComparison$value,
        restrictedModelComparisonWeights = function() private$..restrictedModelComparisonWeights$value,
        restrictedModelComparisonReference = function() private$..restrictedModelComparisonReference$value,
        restrictedModelComparisonMatrix = function() private$..restrictedModelComparisonMatrix$value,
        restrictedModelComparisonCoefficients = function() private$..restrictedModelComparisonCoefficients$value,
        restrictedModelComparisonCoefficientsHighlight = function() private$..restrictedModelComparisonCoefficientsHighlight$value,
        restrictedHeterogeneityCorrection = function() private$..restrictedHeterogeneityCorrection$value,
        restrictedBootstrap = function() private$..restrictedBootstrap$value,
        restrictedBootstrapSamples = function() private$..restrictedBootstrapSamples$value,
        restrictedBootstrapCiLevel = function() private$..restrictedBootstrapCiLevel$value,
        restrictedMarginalMeanTerms = function() private$..restrictedMarginalMeanTerms$value,
        postHocTerms = function() private$..postHocTerms$value,
        postHocTypeStandard = function() private$..postHocTypeStandard$value,
        postHocTypeStandardBootstrap = function() private$..postHocTypeStandardBootstrap$value,
        postHocTypeStandardBootstrapSamples = function() private$..postHocTypeStandardBootstrapSamples$value,
        postHocTypeStandardEffectSize = function() private$..postHocTypeStandardEffectSize$value,
        postHocConditionalTable = function() private$..postHocConditionalTable$value,
        postHocTypeGames = function() private$..postHocTypeGames$value,
        postHocTypeDunnet = function() private$..postHocTypeDunnet$value,
        postHocCorrectionTukey = function() private$..postHocCorrectionTukey$value,
        postHocCorrectionScheffe = function() private$..postHocCorrectionScheffe$value,
        postHocCorrectionBonferroni = function() private$..postHocCorrectionBonferroni$value,
        postHocCorrectionHolm = function() private$..postHocCorrectionHolm$value,
        postHocCorrectionSidak = function() private$..postHocCorrectionSidak$value,
        postHocCorrectionFdr = function() private$..postHocCorrectionFdr$value,
        postHocCi = function() private$..postHocCi$value,
        postHocCiLevel = function() private$..postHocCiLevel$value,
        postHocSignificanceFlag = function() private$..postHocSignificanceFlag$value,
        postHocLetterTable = function() private$..postHocLetterTable$value,
        postHocLetterAlpha = function() private$..postHocLetterAlpha$value,
        descriptivePlotHorizontalAxis = function() private$..descriptivePlotHorizontalAxis$value,
        descriptivePlotSeparateLines = function() private$..descriptivePlotSeparateLines$value,
        descriptivePlotSeparatePlot = function() private$..descriptivePlotSeparatePlot$value,
        descriptivePlotErrorBar = function() private$..descriptivePlotErrorBar$value,
        descriptivePlotErrorBarType = function() private$..descriptivePlotErrorBarType$value,
        descriptivePlotCiLevel = function() private$..descriptivePlotCiLevel$value,
        barPlotHorizontalAxis = function() private$..barPlotHorizontalAxis$value,
        barPlotSeparatePlots = function() private$..barPlotSeparatePlots$value,
        barPlotErrorBars = function() private$..barPlotErrorBars$value,
        barPlotErrorBarType = function() private$..barPlotErrorBarType$value,
        barPlotCiInterval = function() private$..barPlotCiInterval$value,
        barPlotHorizontalZeroFix = function() private$..barPlotHorizontalZeroFix$value,
        rainCloudHorizontalAxis = function() private$..rainCloudHorizontalAxis$value,
        rainCloudSeparatePlots = function() private$..rainCloudSeparatePlots$value,
        rainCloudHorizontalDisplay = function() private$..rainCloudHorizontalDisplay$value,
        marginalMeanTerms = function() private$..marginalMeanTerms$value,
        marginalMeanBootstrap = function() private$..marginalMeanBootstrap$value,
        marginalMeanBootstrapSamples = function() private$..marginalMeanBootstrapSamples$value,
        marginalMeanComparedToZero = function() private$..marginalMeanComparedToZero$value,
        marginalMeanCiCorrection = function() private$..marginalMeanCiCorrection$value,
        simpleMainEffectFactor = function() private$..simpleMainEffectFactor$value,
        simpleMainEffectModeratorFactorOne = function() private$..simpleMainEffectModeratorFactorOne$value,
        simpleMainEffectModeratorFactorTwo = function() private$..simpleMainEffectModeratorFactorTwo$value,
        kruskalWallisFactors = function() private$..kruskalWallisFactors$value,
        kruskalEffectSizeEstimates = function() private$..kruskalEffectSizeEstimates$value,
        kruskalEpsilon = function() private$..kruskalEpsilon$value,
        kruskalEta = function() private$..kruskalEta$value,
        kruskalCiLevel = function() private$..kruskalCiLevel$value,
        postHocTypeDunn = function() private$..postHocTypeDunn$value,
        residualsSavedToData = function() private$..residualsSavedToData$value,
        residualsSavedToDataColumn = function() private$..residualsSavedToDataColumn$value,
        residualsSavedToDataType = function() private$..residualsSavedToDataType$value,
        predictionsSavedToData = function() private$..predictionsSavedToData$value,
        predictionsSavedToDataColumn = function() private$..predictionsSavedToDataColumn$value,
        residsOV = function() private$..residsOV$value,
        predictOV = function() private$..predictOV$value),
    private = list(
        ..dependent = NA,
        ..fixedFactors = NA,
        ..randomFactors = NA,
        ..covariates = NA,
        ..wlsWeights = NA,
        ..descriptives = NA,
        ..effectSizeEstimates = NA,
        ..effectSizeOmegaSquared = NA,
        ..effectSizePartialOmegaSquared = NA,
        ..effectSizeEtaSquared = NA,
        ..effectSizePartialEtaSquared = NA,
        ..effectSizeCi = NA,
        ..effectSizeCiLevel = NA,
        ..vovkSellke = NA,
        ..sumOfSquares = NA,
        ..homogeneityTests = NA,
        ..homogeneityCorrectionNone = NA,
        ..homogeneityCorrectionBrown = NA,
        ..homogeneityCorrectionWelch = NA,
        ..qqPlot = NA,
        ..qqPlotCi = NA,
        ..qqPlotCiLevel = NA,
        ..contrastType = NA,
        ..contrastCi = NA,
        ..contrastCiLevel = NA,
        ..contrastEffectSize = NA,
        ..restrictedSyntax = NA,
        ..restrictedInterceptInclusion = NA,
        ..restrictedAvailableCoefficients = NA,
        ..restrictedModelSummaryForAllModels = NA,
        ..restrictedMarginalMeanForAllModels = NA,
        ..restrictedInformedHypothesisTestForAllModels = NA,
        ..restrictedModelComparison = NA,
        ..restrictedModelComparisonWeights = NA,
        ..restrictedModelComparisonReference = NA,
        ..restrictedModelComparisonMatrix = NA,
        ..restrictedModelComparisonCoefficients = NA,
        ..restrictedModelComparisonCoefficientsHighlight = NA,
        ..restrictedHeterogeneityCorrection = NA,
        ..restrictedBootstrap = NA,
        ..restrictedBootstrapSamples = NA,
        ..restrictedBootstrapCiLevel = NA,
        ..restrictedMarginalMeanTerms = NA,
        ..postHocTerms = NA,
        ..postHocTypeStandard = NA,
        ..postHocTypeStandardBootstrap = NA,
        ..postHocTypeStandardBootstrapSamples = NA,
        ..postHocTypeStandardEffectSize = NA,
        ..postHocConditionalTable = NA,
        ..postHocTypeGames = NA,
        ..postHocTypeDunnet = NA,
        ..postHocCorrectionTukey = NA,
        ..postHocCorrectionScheffe = NA,
        ..postHocCorrectionBonferroni = NA,
        ..postHocCorrectionHolm = NA,
        ..postHocCorrectionSidak = NA,
        ..postHocCorrectionFdr = NA,
        ..postHocCi = NA,
        ..postHocCiLevel = NA,
        ..postHocSignificanceFlag = NA,
        ..postHocLetterTable = NA,
        ..postHocLetterAlpha = NA,
        ..descriptivePlotHorizontalAxis = NA,
        ..descriptivePlotSeparateLines = NA,
        ..descriptivePlotSeparatePlot = NA,
        ..descriptivePlotErrorBar = NA,
        ..descriptivePlotErrorBarType = NA,
        ..descriptivePlotCiLevel = NA,
        ..barPlotHorizontalAxis = NA,
        ..barPlotSeparatePlots = NA,
        ..barPlotErrorBars = NA,
        ..barPlotErrorBarType = NA,
        ..barPlotCiInterval = NA,
        ..barPlotHorizontalZeroFix = NA,
        ..rainCloudHorizontalAxis = NA,
        ..rainCloudSeparatePlots = NA,
        ..rainCloudHorizontalDisplay = NA,
        ..marginalMeanTerms = NA,
        ..marginalMeanBootstrap = NA,
        ..marginalMeanBootstrapSamples = NA,
        ..marginalMeanComparedToZero = NA,
        ..marginalMeanCiCorrection = NA,
        ..simpleMainEffectFactor = NA,
        ..simpleMainEffectModeratorFactorOne = NA,
        ..simpleMainEffectModeratorFactorTwo = NA,
        ..kruskalWallisFactors = NA,
        ..kruskalEffectSizeEstimates = NA,
        ..kruskalEpsilon = NA,
        ..kruskalEta = NA,
        ..kruskalCiLevel = NA,
        ..postHocTypeDunn = NA,
        ..residualsSavedToData = NA,
        ..residualsSavedToDataColumn = NA,
        ..residualsSavedToDataType = NA,
        ..predictionsSavedToData = NA,
        ..predictionsSavedToDataColumn = NA,
        ..residsOV = NA,
        ..predictOV = NA)
)

enhancedAnovaResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "enhancedAnovaResults",
    inherit = jmvcore::Group,
    active = list(
        status = function() private$.items[["status"]],
        modelSummary = function() private$.items[["modelSummary"]],
        descriptivesSection = function() private$.items[["descriptivesSection"]],
        effectSizesSection = function() private$.items[["effectSizesSection"]],
        assumptionsSection = function() private$.items[["assumptionsSection"]],
        contrasts = function() private$.items[["contrasts"]],
        orderRestrictions = function() private$.items[["orderRestrictions"]],
        postHocSection = function() private$.items[["postHocSection"]],
        marginalMeansSection = function() private$.items[["marginalMeansSection"]],
        simpleEffectsSection = function() private$.items[["simpleEffectsSection"]],
        nonparametric = function() private$.items[["nonparametric"]],
        plots = function() private$.items[["plots"]],
        qqPlot = function() private$.items[["qqPlot"]],
        residualPlot = function() private$.items[["residualPlot"]],
        raincloudPlot = function() private$.items[["raincloudPlot"]],
        savedColumns = function() private$.items[["savedColumns"]],
        residsOV = function() private$.items[["residsOV"]],
        predictOV = function() private$.items[["predictOV"]],
        apa = function() private$.items[["apa"]],
        teaching = function() private$.items[["teaching"]],
        publication = function() private$.items[["publication"]],
        reproducibility = function() private$.items[["reproducibility"]],
        about = function() private$.items[["about"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="JASP Enhanced ANOVA")
            self$add(jmvcore::Html$new(
                options=options,
                name="status",
                title="Implementation Status"))
            self$add(jmvcore::Html$new(
                options=options,
                name="modelSummary",
                title="Model Summary"))
            self$add(jmvcore::Html$new(
                options=options,
                name="descriptivesSection",
                title="Descriptive Statistics",
                visible="(descriptives)"))
            self$add(jmvcore::Html$new(
                options=options,
                name="effectSizesSection",
                title="Effect Sizes"))
            self$add(jmvcore::Html$new(
                options=options,
                name="assumptionsSection",
                title="Assumption Checks and Diagnostics"))
            self$add(jmvcore::Html$new(
                options=options,
                name="contrasts",
                title="Contrasts"))
            self$add(jmvcore::Html$new(
                options=options,
                name="orderRestrictions",
                title="Bayesian and Order Restricted Hypotheses"))
            self$add(jmvcore::Html$new(
                options=options,
                name="postHocSection",
                title="Post Hoc Tests"))
            self$add(jmvcore::Html$new(
                options=options,
                name="marginalMeansSection",
                title="Estimated Marginal Means"))
            self$add(jmvcore::Html$new(
                options=options,
                name="simpleEffectsSection",
                title="Simple Main Effects"))
            self$add(jmvcore::Html$new(
                options=options,
                name="nonparametric",
                title="Nonparametric Alternatives"))
            self$add(jmvcore::Html$new(
                options=options,
                name="plots",
                title="Plots"))
            self$add(jmvcore::Image$new(
                options=options,
                name="qqPlot",
                title="Q-Q Plot of Residuals",
                visible="(qqPlot)",
                width=520,
                height=420,
                renderFun=".qqPlot"))
            self$add(jmvcore::Image$new(
                options=options,
                name="residualPlot",
                title="Residual Plot",
                width=520,
                height=420,
                renderFun=".residualPlot"))
            self$add(jmvcore::Image$new(
                options=options,
                name="raincloudPlot",
                title="Raincloud Plot",
                width=640,
                height=440,
                renderFun=".raincloudPlot"))
            self$add(jmvcore::Html$new(
                options=options,
                name="savedColumns",
                title="Saved Dataset Columns"))
            self$add(jmvcore::Output$new(
                options=options,
                name="residsOV",
                title="Residuals",
                varTitle="Residuals",
                varDescription="Residuals from JASP Enhanced ANOVA",
                measureType="continuous",
                clearWith=list(
                    "dependent",
                    "fixedFactors",
                    "covariates")))
            self$add(jmvcore::Output$new(
                options=options,
                name="predictOV",
                title="Predicted values",
                varTitle="Predicted values",
                varDescription="Predicted values from JASP Enhanced ANOVA",
                measureType="continuous",
                clearWith=list(
                    "dependent",
                    "fixedFactors",
                    "covariates")))
            self$add(jmvcore::Html$new(
                options=options,
                name="apa",
                title="APA Reporting"))
            self$add(jmvcore::Html$new(
                options=options,
                name="teaching",
                title="Teaching Mode"))
            self$add(jmvcore::Html$new(
                options=options,
                name="publication",
                title="Publication Mode"))
            self$add(jmvcore::Html$new(
                options=options,
                name="reproducibility",
                title="Reproducibility"))
            self$add(jmvcore::Html$new(
                options=options,
                name="about",
                title="About and Citation"))}))

enhancedAnovaBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "enhancedAnovaBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "jaspEnhancedAnova",
                name = "enhancedAnova",
                version = c(0,1,0),
                options = options,
                results = enhancedAnovaResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'none')
        }))

#' JASP Enhanced ANOVA
#'
#' Classical ANOVA matching the JASP ANOVA analysis, including Type III SS, 
#' corrections, contrasts, post hoc tests, plots, marginal means, simple 
#' effects, nonparametric alternatives, order-restricted hypotheses, and 
#' export.
#' 
#' @param data .
#' @param dependent .
#' @param fixedFactors .
#' @param randomFactors .
#' @param covariates .
#' @param wlsWeights .
#' @param descriptives .
#' @param effectSizeEstimates .
#' @param effectSizeOmegaSquared .
#' @param effectSizePartialOmegaSquared .
#' @param effectSizeEtaSquared .
#' @param effectSizePartialEtaSquared .
#' @param effectSizeCi .
#' @param effectSizeCiLevel .
#' @param vovkSellke .
#' @param sumOfSquares .
#' @param homogeneityTests .
#' @param homogeneityCorrectionNone .
#' @param homogeneityCorrectionBrown .
#' @param homogeneityCorrectionWelch .
#' @param qqPlot .
#' @param qqPlotCi .
#' @param qqPlotCiLevel .
#' @param contrastType .
#' @param contrastCi .
#' @param contrastCiLevel .
#' @param contrastEffectSize .
#' @param restrictedSyntax .
#' @param restrictedInterceptInclusion .
#' @param restrictedAvailableCoefficients .
#' @param restrictedModelSummaryForAllModels .
#' @param restrictedMarginalMeanForAllModels .
#' @param restrictedInformedHypothesisTestForAllModels .
#' @param restrictedModelComparison .
#' @param restrictedModelComparisonWeights .
#' @param restrictedModelComparisonReference .
#' @param restrictedModelComparisonMatrix .
#' @param restrictedModelComparisonCoefficients .
#' @param restrictedModelComparisonCoefficientsHighlight .
#' @param restrictedHeterogeneityCorrection .
#' @param restrictedBootstrap .
#' @param restrictedBootstrapSamples .
#' @param restrictedBootstrapCiLevel .
#' @param restrictedMarginalMeanTerms .
#' @param postHocTerms .
#' @param postHocTypeStandard .
#' @param postHocTypeStandardBootstrap .
#' @param postHocTypeStandardBootstrapSamples .
#' @param postHocTypeStandardEffectSize .
#' @param postHocConditionalTable .
#' @param postHocTypeGames .
#' @param postHocTypeDunnet .
#' @param postHocCorrectionTukey .
#' @param postHocCorrectionScheffe .
#' @param postHocCorrectionBonferroni .
#' @param postHocCorrectionHolm .
#' @param postHocCorrectionSidak .
#' @param postHocCorrectionFdr .
#' @param postHocCi .
#' @param postHocCiLevel .
#' @param postHocSignificanceFlag .
#' @param postHocLetterTable .
#' @param postHocLetterAlpha .
#' @param descriptivePlotHorizontalAxis .
#' @param descriptivePlotSeparateLines .
#' @param descriptivePlotSeparatePlot .
#' @param descriptivePlotErrorBar .
#' @param descriptivePlotErrorBarType .
#' @param descriptivePlotCiLevel .
#' @param barPlotHorizontalAxis .
#' @param barPlotSeparatePlots .
#' @param barPlotErrorBars .
#' @param barPlotErrorBarType .
#' @param barPlotCiInterval .
#' @param barPlotHorizontalZeroFix .
#' @param rainCloudHorizontalAxis .
#' @param rainCloudSeparatePlots .
#' @param rainCloudHorizontalDisplay .
#' @param marginalMeanTerms .
#' @param marginalMeanBootstrap .
#' @param marginalMeanBootstrapSamples .
#' @param marginalMeanComparedToZero .
#' @param marginalMeanCiCorrection .
#' @param simpleMainEffectFactor .
#' @param simpleMainEffectModeratorFactorOne .
#' @param simpleMainEffectModeratorFactorTwo .
#' @param kruskalWallisFactors .
#' @param kruskalEffectSizeEstimates .
#' @param kruskalEpsilon .
#' @param kruskalEta .
#' @param kruskalCiLevel .
#' @param postHocTypeDunn .
#' @param residualsSavedToData .
#' @param residualsSavedToDataColumn .
#' @param residualsSavedToDataType .
#' @param predictionsSavedToData .
#' @param predictionsSavedToDataColumn .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$status} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$modelSummary} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$descriptivesSection} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$effectSizesSection} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$assumptionsSection} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$contrasts} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$orderRestrictions} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$postHocSection} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$marginalMeansSection} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$simpleEffectsSection} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$nonparametric} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$plots} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$qqPlot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$residualPlot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$raincloudPlot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$savedColumns} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$residsOV} \tab \tab \tab \tab \tab an output \cr
#'   \code{results$predictOV} \tab \tab \tab \tab \tab an output \cr
#'   \code{results$apa} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$teaching} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$publication} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$reproducibility} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$about} \tab \tab \tab \tab \tab a html \cr
#' }
#'
#' @export
enhancedAnova <- function(
    data,
    dependent,
    fixedFactors = NULL,
    randomFactors = NULL,
    covariates = NULL,
    wlsWeights = NULL,
    descriptives = FALSE,
    effectSizeEstimates = FALSE,
    effectSizeOmegaSquared = TRUE,
    effectSizePartialOmegaSquared = FALSE,
    effectSizeEtaSquared = FALSE,
    effectSizePartialEtaSquared = FALSE,
    effectSizeCi = FALSE,
    effectSizeCiLevel = 95,
    vovkSellke = FALSE,
    sumOfSquares = "type3",
    homogeneityTests = FALSE,
    homogeneityCorrectionNone = TRUE,
    homogeneityCorrectionBrown = FALSE,
    homogeneityCorrectionWelch = FALSE,
    qqPlot = FALSE,
    qqPlotCi = FALSE,
    qqPlotCiLevel = 95,
    contrastType = "none",
    contrastCi = TRUE,
    contrastCiLevel = 95,
    contrastEffectSize = FALSE,
    restrictedSyntax = "",
    restrictedInterceptInclusion = FALSE,
    restrictedAvailableCoefficients = FALSE,
    restrictedModelSummaryForAllModels = FALSE,
    restrictedMarginalMeanForAllModels = FALSE,
    restrictedInformedHypothesisTestForAllModels = FALSE,
    restrictedModelComparison = "complement",
    restrictedModelComparisonWeights = TRUE,
    restrictedModelComparisonReference = "complement",
    restrictedModelComparisonMatrix = FALSE,
    restrictedModelComparisonCoefficients = FALSE,
    restrictedModelComparisonCoefficientsHighlight = TRUE,
    restrictedHeterogeneityCorrection = "none",
    restrictedBootstrap = FALSE,
    restrictedBootstrapSamples = 1000,
    restrictedBootstrapCiLevel = 95,
    restrictedMarginalMeanTerms = NULL,
    postHocTerms = NULL,
    postHocTypeStandard = TRUE,
    postHocTypeStandardBootstrap = FALSE,
    postHocTypeStandardBootstrapSamples = 1000,
    postHocTypeStandardEffectSize = FALSE,
    postHocConditionalTable = FALSE,
    postHocTypeGames = FALSE,
    postHocTypeDunnet = FALSE,
    postHocCorrectionTukey = TRUE,
    postHocCorrectionScheffe = FALSE,
    postHocCorrectionBonferroni = FALSE,
    postHocCorrectionHolm = FALSE,
    postHocCorrectionSidak = FALSE,
    postHocCorrectionFdr = FALSE,
    postHocCi = TRUE,
    postHocCiLevel = 95,
    postHocSignificanceFlag = FALSE,
    postHocLetterTable = FALSE,
    postHocLetterAlpha = 0.05,
    descriptivePlotHorizontalAxis = NULL,
    descriptivePlotSeparateLines = NULL,
    descriptivePlotSeparatePlot = NULL,
    descriptivePlotErrorBar = TRUE,
    descriptivePlotErrorBarType = "ci",
    descriptivePlotCiLevel = 95,
    barPlotHorizontalAxis = NULL,
    barPlotSeparatePlots = NULL,
    barPlotErrorBars = TRUE,
    barPlotErrorBarType = "ci",
    barPlotCiInterval = 95,
    barPlotHorizontalZeroFix = TRUE,
    rainCloudHorizontalAxis = NULL,
    rainCloudSeparatePlots = NULL,
    rainCloudHorizontalDisplay = FALSE,
    marginalMeanTerms = NULL,
    marginalMeanBootstrap = FALSE,
    marginalMeanBootstrapSamples = 1000,
    marginalMeanComparedToZero = FALSE,
    marginalMeanCiCorrection = "none",
    simpleMainEffectFactor = NULL,
    simpleMainEffectModeratorFactorOne = NULL,
    simpleMainEffectModeratorFactorTwo = NULL,
    kruskalWallisFactors = NULL,
    kruskalEffectSizeEstimates = FALSE,
    kruskalEpsilon = TRUE,
    kruskalEta = FALSE,
    kruskalCiLevel = 95,
    postHocTypeDunn = FALSE,
    residualsSavedToData = FALSE,
    residualsSavedToDataColumn = "residuals",
    residualsSavedToDataType = "raw",
    predictionsSavedToData = FALSE,
    predictionsSavedToDataColumn = "predictions") {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("enhancedAnova requires jmvcore to be installed (restart may be required)")

    if ( ! missing(dependent)) dependent <- jmvcore::resolveQuo(jmvcore::enquo(dependent))
    if ( ! missing(fixedFactors)) fixedFactors <- jmvcore::resolveQuo(jmvcore::enquo(fixedFactors))
    if ( ! missing(randomFactors)) randomFactors <- jmvcore::resolveQuo(jmvcore::enquo(randomFactors))
    if ( ! missing(covariates)) covariates <- jmvcore::resolveQuo(jmvcore::enquo(covariates))
    if ( ! missing(wlsWeights)) wlsWeights <- jmvcore::resolveQuo(jmvcore::enquo(wlsWeights))
    if ( ! missing(restrictedMarginalMeanTerms)) restrictedMarginalMeanTerms <- jmvcore::resolveQuo(jmvcore::enquo(restrictedMarginalMeanTerms))
    if ( ! missing(postHocTerms)) postHocTerms <- jmvcore::resolveQuo(jmvcore::enquo(postHocTerms))
    if ( ! missing(descriptivePlotHorizontalAxis)) descriptivePlotHorizontalAxis <- jmvcore::resolveQuo(jmvcore::enquo(descriptivePlotHorizontalAxis))
    if ( ! missing(descriptivePlotSeparateLines)) descriptivePlotSeparateLines <- jmvcore::resolveQuo(jmvcore::enquo(descriptivePlotSeparateLines))
    if ( ! missing(descriptivePlotSeparatePlot)) descriptivePlotSeparatePlot <- jmvcore::resolveQuo(jmvcore::enquo(descriptivePlotSeparatePlot))
    if ( ! missing(barPlotHorizontalAxis)) barPlotHorizontalAxis <- jmvcore::resolveQuo(jmvcore::enquo(barPlotHorizontalAxis))
    if ( ! missing(barPlotSeparatePlots)) barPlotSeparatePlots <- jmvcore::resolveQuo(jmvcore::enquo(barPlotSeparatePlots))
    if ( ! missing(rainCloudHorizontalAxis)) rainCloudHorizontalAxis <- jmvcore::resolveQuo(jmvcore::enquo(rainCloudHorizontalAxis))
    if ( ! missing(rainCloudSeparatePlots)) rainCloudSeparatePlots <- jmvcore::resolveQuo(jmvcore::enquo(rainCloudSeparatePlots))
    if ( ! missing(marginalMeanTerms)) marginalMeanTerms <- jmvcore::resolveQuo(jmvcore::enquo(marginalMeanTerms))
    if ( ! missing(simpleMainEffectFactor)) simpleMainEffectFactor <- jmvcore::resolveQuo(jmvcore::enquo(simpleMainEffectFactor))
    if ( ! missing(simpleMainEffectModeratorFactorOne)) simpleMainEffectModeratorFactorOne <- jmvcore::resolveQuo(jmvcore::enquo(simpleMainEffectModeratorFactorOne))
    if ( ! missing(simpleMainEffectModeratorFactorTwo)) simpleMainEffectModeratorFactorTwo <- jmvcore::resolveQuo(jmvcore::enquo(simpleMainEffectModeratorFactorTwo))
    if ( ! missing(kruskalWallisFactors)) kruskalWallisFactors <- jmvcore::resolveQuo(jmvcore::enquo(kruskalWallisFactors))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(dependent), dependent, NULL),
            `if`( ! missing(fixedFactors), fixedFactors, NULL),
            `if`( ! missing(randomFactors), randomFactors, NULL),
            `if`( ! missing(covariates), covariates, NULL),
            `if`( ! missing(wlsWeights), wlsWeights, NULL),
            `if`( ! missing(restrictedMarginalMeanTerms), restrictedMarginalMeanTerms, NULL),
            `if`( ! missing(postHocTerms), postHocTerms, NULL),
            `if`( ! missing(descriptivePlotHorizontalAxis), descriptivePlotHorizontalAxis, NULL),
            `if`( ! missing(descriptivePlotSeparateLines), descriptivePlotSeparateLines, NULL),
            `if`( ! missing(descriptivePlotSeparatePlot), descriptivePlotSeparatePlot, NULL),
            `if`( ! missing(barPlotHorizontalAxis), barPlotHorizontalAxis, NULL),
            `if`( ! missing(barPlotSeparatePlots), barPlotSeparatePlots, NULL),
            `if`( ! missing(rainCloudHorizontalAxis), rainCloudHorizontalAxis, NULL),
            `if`( ! missing(rainCloudSeparatePlots), rainCloudSeparatePlots, NULL),
            `if`( ! missing(marginalMeanTerms), marginalMeanTerms, NULL),
            `if`( ! missing(simpleMainEffectFactor), simpleMainEffectFactor, NULL),
            `if`( ! missing(simpleMainEffectModeratorFactorOne), simpleMainEffectModeratorFactorOne, NULL),
            `if`( ! missing(simpleMainEffectModeratorFactorTwo), simpleMainEffectModeratorFactorTwo, NULL),
            `if`( ! missing(kruskalWallisFactors), kruskalWallisFactors, NULL))

    for (v in fixedFactors) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    for (v in randomFactors) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    for (v in restrictedMarginalMeanTerms) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    for (v in postHocTerms) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    for (v in descriptivePlotHorizontalAxis) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    for (v in descriptivePlotSeparateLines) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    for (v in descriptivePlotSeparatePlot) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    for (v in barPlotHorizontalAxis) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    for (v in barPlotSeparatePlots) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    for (v in rainCloudHorizontalAxis) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    for (v in rainCloudSeparatePlots) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    for (v in marginalMeanTerms) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    for (v in simpleMainEffectFactor) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    for (v in simpleMainEffectModeratorFactorOne) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    for (v in simpleMainEffectModeratorFactorTwo) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    for (v in kruskalWallisFactors) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])

    options <- enhancedAnovaOptions$new(
        dependent = dependent,
        fixedFactors = fixedFactors,
        randomFactors = randomFactors,
        covariates = covariates,
        wlsWeights = wlsWeights,
        descriptives = descriptives,
        effectSizeEstimates = effectSizeEstimates,
        effectSizeOmegaSquared = effectSizeOmegaSquared,
        effectSizePartialOmegaSquared = effectSizePartialOmegaSquared,
        effectSizeEtaSquared = effectSizeEtaSquared,
        effectSizePartialEtaSquared = effectSizePartialEtaSquared,
        effectSizeCi = effectSizeCi,
        effectSizeCiLevel = effectSizeCiLevel,
        vovkSellke = vovkSellke,
        sumOfSquares = sumOfSquares,
        homogeneityTests = homogeneityTests,
        homogeneityCorrectionNone = homogeneityCorrectionNone,
        homogeneityCorrectionBrown = homogeneityCorrectionBrown,
        homogeneityCorrectionWelch = homogeneityCorrectionWelch,
        qqPlot = qqPlot,
        qqPlotCi = qqPlotCi,
        qqPlotCiLevel = qqPlotCiLevel,
        contrastType = contrastType,
        contrastCi = contrastCi,
        contrastCiLevel = contrastCiLevel,
        contrastEffectSize = contrastEffectSize,
        restrictedSyntax = restrictedSyntax,
        restrictedInterceptInclusion = restrictedInterceptInclusion,
        restrictedAvailableCoefficients = restrictedAvailableCoefficients,
        restrictedModelSummaryForAllModels = restrictedModelSummaryForAllModels,
        restrictedMarginalMeanForAllModels = restrictedMarginalMeanForAllModels,
        restrictedInformedHypothesisTestForAllModels = restrictedInformedHypothesisTestForAllModels,
        restrictedModelComparison = restrictedModelComparison,
        restrictedModelComparisonWeights = restrictedModelComparisonWeights,
        restrictedModelComparisonReference = restrictedModelComparisonReference,
        restrictedModelComparisonMatrix = restrictedModelComparisonMatrix,
        restrictedModelComparisonCoefficients = restrictedModelComparisonCoefficients,
        restrictedModelComparisonCoefficientsHighlight = restrictedModelComparisonCoefficientsHighlight,
        restrictedHeterogeneityCorrection = restrictedHeterogeneityCorrection,
        restrictedBootstrap = restrictedBootstrap,
        restrictedBootstrapSamples = restrictedBootstrapSamples,
        restrictedBootstrapCiLevel = restrictedBootstrapCiLevel,
        restrictedMarginalMeanTerms = restrictedMarginalMeanTerms,
        postHocTerms = postHocTerms,
        postHocTypeStandard = postHocTypeStandard,
        postHocTypeStandardBootstrap = postHocTypeStandardBootstrap,
        postHocTypeStandardBootstrapSamples = postHocTypeStandardBootstrapSamples,
        postHocTypeStandardEffectSize = postHocTypeStandardEffectSize,
        postHocConditionalTable = postHocConditionalTable,
        postHocTypeGames = postHocTypeGames,
        postHocTypeDunnet = postHocTypeDunnet,
        postHocCorrectionTukey = postHocCorrectionTukey,
        postHocCorrectionScheffe = postHocCorrectionScheffe,
        postHocCorrectionBonferroni = postHocCorrectionBonferroni,
        postHocCorrectionHolm = postHocCorrectionHolm,
        postHocCorrectionSidak = postHocCorrectionSidak,
        postHocCorrectionFdr = postHocCorrectionFdr,
        postHocCi = postHocCi,
        postHocCiLevel = postHocCiLevel,
        postHocSignificanceFlag = postHocSignificanceFlag,
        postHocLetterTable = postHocLetterTable,
        postHocLetterAlpha = postHocLetterAlpha,
        descriptivePlotHorizontalAxis = descriptivePlotHorizontalAxis,
        descriptivePlotSeparateLines = descriptivePlotSeparateLines,
        descriptivePlotSeparatePlot = descriptivePlotSeparatePlot,
        descriptivePlotErrorBar = descriptivePlotErrorBar,
        descriptivePlotErrorBarType = descriptivePlotErrorBarType,
        descriptivePlotCiLevel = descriptivePlotCiLevel,
        barPlotHorizontalAxis = barPlotHorizontalAxis,
        barPlotSeparatePlots = barPlotSeparatePlots,
        barPlotErrorBars = barPlotErrorBars,
        barPlotErrorBarType = barPlotErrorBarType,
        barPlotCiInterval = barPlotCiInterval,
        barPlotHorizontalZeroFix = barPlotHorizontalZeroFix,
        rainCloudHorizontalAxis = rainCloudHorizontalAxis,
        rainCloudSeparatePlots = rainCloudSeparatePlots,
        rainCloudHorizontalDisplay = rainCloudHorizontalDisplay,
        marginalMeanTerms = marginalMeanTerms,
        marginalMeanBootstrap = marginalMeanBootstrap,
        marginalMeanBootstrapSamples = marginalMeanBootstrapSamples,
        marginalMeanComparedToZero = marginalMeanComparedToZero,
        marginalMeanCiCorrection = marginalMeanCiCorrection,
        simpleMainEffectFactor = simpleMainEffectFactor,
        simpleMainEffectModeratorFactorOne = simpleMainEffectModeratorFactorOne,
        simpleMainEffectModeratorFactorTwo = simpleMainEffectModeratorFactorTwo,
        kruskalWallisFactors = kruskalWallisFactors,
        kruskalEffectSizeEstimates = kruskalEffectSizeEstimates,
        kruskalEpsilon = kruskalEpsilon,
        kruskalEta = kruskalEta,
        kruskalCiLevel = kruskalCiLevel,
        postHocTypeDunn = postHocTypeDunn,
        residualsSavedToData = residualsSavedToData,
        residualsSavedToDataColumn = residualsSavedToDataColumn,
        residualsSavedToDataType = residualsSavedToDataType,
        predictionsSavedToData = predictionsSavedToData,
        predictionsSavedToDataColumn = predictionsSavedToDataColumn)

    analysis <- enhancedAnovaClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}
