
# This file is automatically generated, you probably don't want to edit this

enhancedManovaOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "enhancedManovaOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            dependent = NULL,
            fixedFactors = NULL,
            randomFactors = NULL,
            covariates = NULL,
            modelTerms = "",
            includeIntercept = TRUE,
            testPillai = TRUE,
            testWilks = TRUE,
            testHotellingLawley = TRUE,
            testRoy = FALSE,
            anovaTables = TRUE,
            vovkSellke = FALSE,
            boxMTest = FALSE,
            shapiroTest = FALSE,
            descriptives = FALSE,
            apaReport = TRUE, ...) {

            super$initialize(
                package="jaspEnhancedAnova",
                name="enhancedManova",
                requiresData=TRUE,
                ...)

            private$..dependent <- jmvcore::OptionVariables$new(
                "dependent",
                dependent,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..fixedFactors <- jmvcore::OptionVariables$new(
                "fixedFactors",
                fixedFactors,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"))
            private$..randomFactors <- jmvcore::OptionVariables$new(
                "randomFactors",
                randomFactors,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"))
            private$..covariates <- jmvcore::OptionVariables$new(
                "covariates",
                covariates,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..modelTerms <- jmvcore::OptionString$new(
                "modelTerms",
                modelTerms,
                default="")
            private$..includeIntercept <- jmvcore::OptionBool$new(
                "includeIntercept",
                includeIntercept,
                default=TRUE)
            private$..testPillai <- jmvcore::OptionBool$new(
                "testPillai",
                testPillai,
                default=TRUE)
            private$..testWilks <- jmvcore::OptionBool$new(
                "testWilks",
                testWilks,
                default=TRUE)
            private$..testHotellingLawley <- jmvcore::OptionBool$new(
                "testHotellingLawley",
                testHotellingLawley,
                default=TRUE)
            private$..testRoy <- jmvcore::OptionBool$new(
                "testRoy",
                testRoy,
                default=FALSE)
            private$..anovaTables <- jmvcore::OptionBool$new(
                "anovaTables",
                anovaTables,
                default=TRUE)
            private$..vovkSellke <- jmvcore::OptionBool$new(
                "vovkSellke",
                vovkSellke,
                default=FALSE)
            private$..boxMTest <- jmvcore::OptionBool$new(
                "boxMTest",
                boxMTest,
                default=FALSE)
            private$..shapiroTest <- jmvcore::OptionBool$new(
                "shapiroTest",
                shapiroTest,
                default=FALSE)
            private$..descriptives <- jmvcore::OptionBool$new(
                "descriptives",
                descriptives,
                default=FALSE)
            private$..apaReport <- jmvcore::OptionBool$new(
                "apaReport",
                apaReport,
                default=TRUE)

            self$.addOption(private$..dependent)
            self$.addOption(private$..fixedFactors)
            self$.addOption(private$..randomFactors)
            self$.addOption(private$..covariates)
            self$.addOption(private$..modelTerms)
            self$.addOption(private$..includeIntercept)
            self$.addOption(private$..testPillai)
            self$.addOption(private$..testWilks)
            self$.addOption(private$..testHotellingLawley)
            self$.addOption(private$..testRoy)
            self$.addOption(private$..anovaTables)
            self$.addOption(private$..vovkSellke)
            self$.addOption(private$..boxMTest)
            self$.addOption(private$..shapiroTest)
            self$.addOption(private$..descriptives)
            self$.addOption(private$..apaReport)
        }),
    active = list(
        dependent = function() private$..dependent$value,
        fixedFactors = function() private$..fixedFactors$value,
        randomFactors = function() private$..randomFactors$value,
        covariates = function() private$..covariates$value,
        modelTerms = function() private$..modelTerms$value,
        includeIntercept = function() private$..includeIntercept$value,
        testPillai = function() private$..testPillai$value,
        testWilks = function() private$..testWilks$value,
        testHotellingLawley = function() private$..testHotellingLawley$value,
        testRoy = function() private$..testRoy$value,
        anovaTables = function() private$..anovaTables$value,
        vovkSellke = function() private$..vovkSellke$value,
        boxMTest = function() private$..boxMTest$value,
        shapiroTest = function() private$..shapiroTest$value,
        descriptives = function() private$..descriptives$value,
        apaReport = function() private$..apaReport$value),
    private = list(
        ..dependent = NA,
        ..fixedFactors = NA,
        ..randomFactors = NA,
        ..covariates = NA,
        ..modelTerms = NA,
        ..includeIntercept = NA,
        ..testPillai = NA,
        ..testWilks = NA,
        ..testHotellingLawley = NA,
        ..testRoy = NA,
        ..anovaTables = NA,
        ..vovkSellke = NA,
        ..boxMTest = NA,
        ..shapiroTest = NA,
        ..descriptives = NA,
        ..apaReport = NA)
)

enhancedManovaResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "enhancedManovaResults",
    inherit = jmvcore::Group,
    active = list(
        status = function() private$.items[["status"]],
        modelSummary = function() private$.items[["modelSummary"]],
        multivariateTests = function() private$.items[["multivariateTests"]],
        univariateTables = function() private$.items[["univariateTables"]],
        descriptivesSection = function() private$.items[["descriptivesSection"]],
        assumptionsSection = function() private$.items[["assumptionsSection"]],
        apa = function() private$.items[["apa"]],
        reproducibility = function() private$.items[["reproducibility"]],
        about = function() private$.items[["about"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="JASP Enhanced MANCOVA")
            self$add(jmvcore::Html$new(
                options=options,
                name="status",
                title="Implementation Status"))
            self$add(jmvcore::Html$new(
                options=options,
                name="modelSummary",
                title="Model Summary"))
            self$add(jmvcore::Html$new(
                options=options,
                name="multivariateTests",
                title="Multivariate Tests"))
            self$add(jmvcore::Html$new(
                options=options,
                name="univariateTables",
                title="Univariate Follow-up Tables",
                visible="(anovaTables)"))
            self$add(jmvcore::Html$new(
                options=options,
                name="descriptivesSection",
                title="Descriptive Statistics",
                visible="(descriptives)"))
            self$add(jmvcore::Html$new(
                options=options,
                name="assumptionsSection",
                title="Assumption Checks"))
            self$add(jmvcore::Html$new(
                options=options,
                name="apa",
                title="APA Reporting",
                visible="(apaReport)"))
            self$add(jmvcore::Html$new(
                options=options,
                name="reproducibility",
                title="Reproducibility"))
            self$add(jmvcore::Html$new(
                options=options,
                name="about",
                title="About and Citation"))}))

enhancedManovaBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "enhancedManovaBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "jaspEnhancedAnova",
                name = "enhancedManova",
                version = c(0,1,0),
                options = options,
                results = enhancedManovaResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' JASP Enhanced MANCOVA
#'
#' True MANCOVA matching the JASP MANOVA workflow with covariate support,
#' including multivariate omnibus tests, univariate follow-up ANCOVA tables,
#' assumption checks, effect-size-oriented reporting, and reproducibility
#' output.
#'
#' @param data .
#' @param dependent .
#' @param fixedFactors .
#' @param randomFactors .
#' @param covariates .
#' @param modelTerms .
#' @param includeIntercept .
#' @param testPillai .
#' @param testWilks .
#' @param testHotellingLawley .
#' @param testRoy .
#' @param anovaTables .
#' @param vovkSellke .
#' @param boxMTest .
#' @param shapiroTest .
#' @param descriptives .
#' @param apaReport .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$status} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$modelSummary} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$multivariateTests} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$univariateTables} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$descriptivesSection} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$assumptionsSection} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$apa} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$reproducibility} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$about} \tab \tab \tab \tab \tab a html \cr
#' }
#'
#' @export
enhancedManova <- function(
    data,
    dependent,
    fixedFactors = NULL,
    randomFactors = NULL,
    covariates = NULL,
    modelTerms = "",
    includeIntercept = TRUE,
    testPillai = TRUE,
    testWilks = TRUE,
    testHotellingLawley = TRUE,
    testRoy = FALSE,
    anovaTables = TRUE,
    vovkSellke = FALSE,
    boxMTest = FALSE,
    shapiroTest = FALSE,
    descriptives = FALSE,
    apaReport = TRUE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("enhancedManova requires jmvcore to be installed (restart may be required)")

    if ( ! missing(dependent)) dependent <- jmvcore::resolveQuo(jmvcore::enquo(dependent))
    if ( ! missing(fixedFactors)) fixedFactors <- jmvcore::resolveQuo(jmvcore::enquo(fixedFactors))
    if ( ! missing(randomFactors)) randomFactors <- jmvcore::resolveQuo(jmvcore::enquo(randomFactors))
    if ( ! missing(covariates)) covariates <- jmvcore::resolveQuo(jmvcore::enquo(covariates))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(dependent), dependent, NULL),
            `if`( ! missing(fixedFactors), fixedFactors, NULL),
            `if`( ! missing(randomFactors), randomFactors, NULL),
            `if`( ! missing(covariates), covariates, NULL))

    for (v in fixedFactors) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    for (v in randomFactors) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])

    options <- enhancedManovaOptions$new(
        dependent = dependent,
        fixedFactors = fixedFactors,
        randomFactors = randomFactors,
        covariates = covariates,
        modelTerms = modelTerms,
        includeIntercept = includeIntercept,
        testPillai = testPillai,
        testWilks = testWilks,
        testHotellingLawley = testHotellingLawley,
        testRoy = testRoy,
        anovaTables = anovaTables,
        vovkSellke = vovkSellke,
        boxMTest = boxMTest,
        shapiroTest = shapiroTest,
        descriptives = descriptives,
        apaReport = apaReport)

    analysis <- enhancedManovaClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}
