
# This file is automatically generated, you probably don't want to edit this

enhancedRepeatedMeasuresAnovaOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "enhancedRepeatedMeasuresAnovaOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            rmFactorSpec = "",
            rmFactorNames = "RM Factor 1",
            rmFactorLevels = "Level 1, Level 2",
            repeatedMeasuresCells = NULL,
            betweenSubjectFactors = NULL,
            covariates = NULL,
            descriptives = FALSE,
            effectSizeEstimates = FALSE,
            effectSizeOmegaSquared = TRUE,
            effectSizePartialOmegaSquared = FALSE,
            effectSizeEtaSquared = FALSE,
            effectSizePartialEtaSquared = FALSE,
            effectSizeGeneralEtaSquared = FALSE,
            effectSizeCi = FALSE,
            effectSizeCiLevel = 95,
            vovkSellke = FALSE,
            sumOfSquares = "type3",
            poolErrorTermFollowup = FALSE,
            sphericityTests = TRUE,
            sphericityCorrectionNone = TRUE,
            sphericityCorrectionGreenhouseGeisser = FALSE,
            sphericityCorrectionHuynhFeldt = FALSE,
            homogeneityTests = FALSE,
            qqPlot = FALSE,
            qqPlotCi = FALSE,
            qqPlotCiLevel = 95,
            contrastType = "none",
            contrastCi = TRUE,
            contrastCiLevel = 95,
            contrastEffectSize = FALSE,
            restrictedSyntax = "",
            restrictedInterceptInclusion = FALSE,
            restrictedAvailableCoefficients = FALSE,
            restrictedModelSummaryForAllModels = FALSE,
            restrictedMarginalMeanForAllModels = FALSE,
            restrictedModelComparison = "complement",
            restrictedModelComparisonWeights = TRUE,
            restrictedModelComparisonReference = "complement",
            restrictedModelComparisonMatrix = FALSE,
            restrictedModelComparisonCoefficients = FALSE,
            restrictedModelComparisonCoefficientsHighlight = TRUE,
            restrictedHeterogeneityCorrection = "none",
            restrictedBootstrap = FALSE,
            restrictedBootstrapSamples = 1000,
            restrictedBootstrapCiLevel = 95,
            restrictedMarginalMeanTerms = NULL,
            postHocTerms = NULL,
            postHocEffectSize = FALSE,
            postHocConditionalTable = FALSE,
            postHocCorrectionHolm = TRUE,
            postHocCorrectionBonferroni = FALSE,
            postHocCorrectionTukey = FALSE,
            postHocCorrectionScheffe = FALSE,
            postHocCorrectionFdr = FALSE,
            postHocCi = TRUE,
            postHocCiLevel = 95,
            postHocSignificanceFlag = FALSE,
            postHocLetterTable = FALSE,
            postHocLetterAlpha = 0.05,
            descriptivePlotHorizontalAxis = NULL,
            descriptivePlotSeparateLines = NULL,
            descriptivePlotSeparatePlot = NULL,
            descriptivePlotErrorBar = TRUE,
            descriptivePlotErrorBarType = "ci",
            descriptivePlotCiLevel = 95,
            descriptivePlotYAxisLabel = "",
            descriptivePlotErrorBarPooled = FALSE,
            normalizeErrorBarsDescriptives = TRUE,
            barPlotHorizontalAxis = NULL,
            barPlotSeparatePlots = NULL,
            barPlotErrorBars = TRUE,
            barPlotErrorBarType = "ci",
            barPlotCiInterval = 95,
            barPlotHorizontalZeroFix = TRUE,
            labelYAxisTwo = "",
            usePooledStandErrorCITwo = FALSE,
            normalizeErrorBarsBarplot = TRUE,
            rainCloudHorizontalAxis = NULL,
            rainCloudSeparatePlots = NULL,
            rainCloudYAxisLabel = "",
            marginalMeanTerms = NULL,
            marginalMeanBootstrap = FALSE,
            marginalMeanBootstrapSamples = 1000,
            marginalMeanComparedToZero = FALSE,
            marginalMeanCiCorrection = "none",
            simpleMainEffectFactor = NULL,
            simpleMainEffectModeratorFactorOne = NULL,
            simpleMainEffectModeratorFactorTwo = NULL,
            simpleMainEffectErrorTermPooled = FALSE,
            friedmanWithinFactor = NULL,
            friedmanBetweenFactor = NULL,
            conoverTest = FALSE,
            residualsSavedToData = FALSE,
            residualsSavedToDataColumn = "residuals",
            residualsSavedToDataType = "raw",
            predictionsSavedToData = FALSE,
            predictionsSavedToDataColumn = "predictions", ...) {

            super$initialize(
                package="jaspEnhancedAnova",
                name="enhancedRepeatedMeasuresAnova",
                requiresData=TRUE,
                ...)

            private$..rmFactorSpec <- jmvcore::OptionString$new(
                "rmFactorSpec",
                rmFactorSpec,
                default="")
            private$..rmFactorNames <- jmvcore::OptionString$new(
                "rmFactorNames",
                rmFactorNames,
                default="RM Factor 1")
            private$..rmFactorLevels <- jmvcore::OptionString$new(
                "rmFactorLevels",
                rmFactorLevels,
                default="Level 1, Level 2")
            private$..repeatedMeasuresCells <- jmvcore::OptionVariables$new(
                "repeatedMeasuresCells",
                repeatedMeasuresCells,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..betweenSubjectFactors <- jmvcore::OptionVariables$new(
                "betweenSubjectFactors",
                betweenSubjectFactors,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"))
            private$..covariates <- jmvcore::OptionVariables$new(
                "covariates",
                covariates,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..descriptives <- jmvcore::OptionBool$new(
                "descriptives",
                descriptives,
                default=FALSE)
            private$..effectSizeEstimates <- jmvcore::OptionBool$new(
                "effectSizeEstimates",
                effectSizeEstimates,
                default=FALSE)
            private$..effectSizeOmegaSquared <- jmvcore::OptionBool$new(
                "effectSizeOmegaSquared",
                effectSizeOmegaSquared,
                default=TRUE)
            private$..effectSizePartialOmegaSquared <- jmvcore::OptionBool$new(
                "effectSizePartialOmegaSquared",
                effectSizePartialOmegaSquared,
                default=FALSE)
            private$..effectSizeEtaSquared <- jmvcore::OptionBool$new(
                "effectSizeEtaSquared",
                effectSizeEtaSquared,
                default=FALSE)
            private$..effectSizePartialEtaSquared <- jmvcore::OptionBool$new(
                "effectSizePartialEtaSquared",
                effectSizePartialEtaSquared,
                default=FALSE)
            private$..effectSizeGeneralEtaSquared <- jmvcore::OptionBool$new(
                "effectSizeGeneralEtaSquared",
                effectSizeGeneralEtaSquared,
                default=FALSE)
            private$..effectSizeCi <- jmvcore::OptionBool$new(
                "effectSizeCi",
                effectSizeCi,
                default=FALSE)
            private$..effectSizeCiLevel <- jmvcore::OptionNumber$new(
                "effectSizeCiLevel",
                effectSizeCiLevel,
                min=50,
                max=99.9,
                default=95)
            private$..vovkSellke <- jmvcore::OptionBool$new(
                "vovkSellke",
                vovkSellke,
                default=FALSE)
            private$..sumOfSquares <- jmvcore::OptionList$new(
                "sumOfSquares",
                sumOfSquares,
                options=list(
                    "type1",
                    "type2",
                    "type3"),
                default="type3")
            private$..poolErrorTermFollowup <- jmvcore::OptionBool$new(
                "poolErrorTermFollowup",
                poolErrorTermFollowup,
                default=FALSE)
            private$..sphericityTests <- jmvcore::OptionBool$new(
                "sphericityTests",
                sphericityTests,
                default=TRUE)
            private$..sphericityCorrectionNone <- jmvcore::OptionBool$new(
                "sphericityCorrectionNone",
                sphericityCorrectionNone,
                default=TRUE)
            private$..sphericityCorrectionGreenhouseGeisser <- jmvcore::OptionBool$new(
                "sphericityCorrectionGreenhouseGeisser",
                sphericityCorrectionGreenhouseGeisser,
                default=FALSE)
            private$..sphericityCorrectionHuynhFeldt <- jmvcore::OptionBool$new(
                "sphericityCorrectionHuynhFeldt",
                sphericityCorrectionHuynhFeldt,
                default=FALSE)
            private$..homogeneityTests <- jmvcore::OptionBool$new(
                "homogeneityTests",
                homogeneityTests,
                default=FALSE)
            private$..qqPlot <- jmvcore::OptionBool$new(
                "qqPlot",
                qqPlot,
                default=FALSE)
            private$..qqPlotCi <- jmvcore::OptionBool$new(
                "qqPlotCi",
                qqPlotCi,
                default=FALSE)
            private$..qqPlotCiLevel <- jmvcore::OptionNumber$new(
                "qqPlotCiLevel",
                qqPlotCiLevel,
                min=50,
                max=99.9,
                default=95)
            private$..contrastType <- jmvcore::OptionList$new(
                "contrastType",
                contrastType,
                options=list(
                    "none",
                    "deviation",
                    "simple",
                    "difference",
                    "helmert",
                    "repeated",
                    "polynomial"),
                default="none")
            private$..contrastCi <- jmvcore::OptionBool$new(
                "contrastCi",
                contrastCi,
                default=TRUE)
            private$..contrastCiLevel <- jmvcore::OptionNumber$new(
                "contrastCiLevel",
                contrastCiLevel,
                min=50,
                max=99.9,
                default=95)
            private$..contrastEffectSize <- jmvcore::OptionBool$new(
                "contrastEffectSize",
                contrastEffectSize,
                default=FALSE)
            private$..restrictedSyntax <- jmvcore::OptionString$new(
                "restrictedSyntax",
                restrictedSyntax,
                default="")
            private$..restrictedInterceptInclusion <- jmvcore::OptionBool$new(
                "restrictedInterceptInclusion",
                restrictedInterceptInclusion,
                default=FALSE)
            private$..restrictedAvailableCoefficients <- jmvcore::OptionBool$new(
                "restrictedAvailableCoefficients",
                restrictedAvailableCoefficients,
                default=FALSE)
            private$..restrictedModelSummaryForAllModels <- jmvcore::OptionBool$new(
                "restrictedModelSummaryForAllModels",
                restrictedModelSummaryForAllModels,
                default=FALSE)
            private$..restrictedMarginalMeanForAllModels <- jmvcore::OptionBool$new(
                "restrictedMarginalMeanForAllModels",
                restrictedMarginalMeanForAllModels,
                default=FALSE)
            private$..restrictedModelComparison <- jmvcore::OptionList$new(
                "restrictedModelComparison",
                restrictedModelComparison,
                options=list(
                    "complement",
                    "unconstrained",
                    "none"),
                default="complement")
            private$..restrictedModelComparisonWeights <- jmvcore::OptionBool$new(
                "restrictedModelComparisonWeights",
                restrictedModelComparisonWeights,
                default=TRUE)
            private$..restrictedModelComparisonReference <- jmvcore::OptionList$new(
                "restrictedModelComparisonReference",
                restrictedModelComparisonReference,
                options=list(
                    "complement",
                    "unconstrained"),
                default="complement")
            private$..restrictedModelComparisonMatrix <- jmvcore::OptionBool$new(
                "restrictedModelComparisonMatrix",
                restrictedModelComparisonMatrix,
                default=FALSE)
            private$..restrictedModelComparisonCoefficients <- jmvcore::OptionBool$new(
                "restrictedModelComparisonCoefficients",
                restrictedModelComparisonCoefficients,
                default=FALSE)
            private$..restrictedModelComparisonCoefficientsHighlight <- jmvcore::OptionBool$new(
                "restrictedModelComparisonCoefficientsHighlight",
                restrictedModelComparisonCoefficientsHighlight,
                default=TRUE)
            private$..restrictedHeterogeneityCorrection <- jmvcore::OptionList$new(
                "restrictedHeterogeneityCorrection",
                restrictedHeterogeneityCorrection,
                options=list(
                    "none",
                    "huberWhite0",
                    "huberWhite1",
                    "huberWhite2",
                    "huberWhite3",
                    "huberWhite4",
                    "huberWhite4m",
                    "huberWhite5"),
                default="none")
            private$..restrictedBootstrap <- jmvcore::OptionBool$new(
                "restrictedBootstrap",
                restrictedBootstrap,
                default=FALSE)
            private$..restrictedBootstrapSamples <- jmvcore::OptionInteger$new(
                "restrictedBootstrapSamples",
                restrictedBootstrapSamples,
                min=100,
                max=100000,
                default=1000)
            private$..restrictedBootstrapCiLevel <- jmvcore::OptionNumber$new(
                "restrictedBootstrapCiLevel",
                restrictedBootstrapCiLevel,
                min=50,
                max=99.9,
                default=95)
            private$..restrictedMarginalMeanTerms <- jmvcore::OptionVariables$new(
                "restrictedMarginalMeanTerms",
                restrictedMarginalMeanTerms,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"))
            private$..postHocTerms <- jmvcore::OptionVariables$new(
                "postHocTerms",
                postHocTerms,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"))
            private$..postHocEffectSize <- jmvcore::OptionBool$new(
                "postHocEffectSize",
                postHocEffectSize,
                default=FALSE)
            private$..postHocConditionalTable <- jmvcore::OptionBool$new(
                "postHocConditionalTable",
                postHocConditionalTable,
                default=FALSE)
            private$..postHocCorrectionHolm <- jmvcore::OptionBool$new(
                "postHocCorrectionHolm",
                postHocCorrectionHolm,
                default=TRUE)
            private$..postHocCorrectionBonferroni <- jmvcore::OptionBool$new(
                "postHocCorrectionBonferroni",
                postHocCorrectionBonferroni,
                default=FALSE)
            private$..postHocCorrectionTukey <- jmvcore::OptionBool$new(
                "postHocCorrectionTukey",
                postHocCorrectionTukey,
                default=FALSE)
            private$..postHocCorrectionScheffe <- jmvcore::OptionBool$new(
                "postHocCorrectionScheffe",
                postHocCorrectionScheffe,
                default=FALSE)
            private$..postHocCorrectionFdr <- jmvcore::OptionBool$new(
                "postHocCorrectionFdr",
                postHocCorrectionFdr,
                default=FALSE)
            private$..postHocCi <- jmvcore::OptionBool$new(
                "postHocCi",
                postHocCi,
                default=TRUE)
            private$..postHocCiLevel <- jmvcore::OptionNumber$new(
                "postHocCiLevel",
                postHocCiLevel,
                min=50,
                max=99.9,
                default=95)
            private$..postHocSignificanceFlag <- jmvcore::OptionBool$new(
                "postHocSignificanceFlag",
                postHocSignificanceFlag,
                default=FALSE)
            private$..postHocLetterTable <- jmvcore::OptionBool$new(
                "postHocLetterTable",
                postHocLetterTable,
                default=FALSE)
            private$..postHocLetterAlpha <- jmvcore::OptionNumber$new(
                "postHocLetterAlpha",
                postHocLetterAlpha,
                min=0,
                max=1,
                default=0.05)
            private$..descriptivePlotHorizontalAxis <- jmvcore::OptionVariable$new(
                "descriptivePlotHorizontalAxis",
                descriptivePlotHorizontalAxis,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"))
            private$..descriptivePlotSeparateLines <- jmvcore::OptionVariable$new(
                "descriptivePlotSeparateLines",
                descriptivePlotSeparateLines,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"))
            private$..descriptivePlotSeparatePlot <- jmvcore::OptionVariable$new(
                "descriptivePlotSeparatePlot",
                descriptivePlotSeparatePlot,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"))
            private$..descriptivePlotErrorBar <- jmvcore::OptionBool$new(
                "descriptivePlotErrorBar",
                descriptivePlotErrorBar,
                default=TRUE)
            private$..descriptivePlotErrorBarType <- jmvcore::OptionList$new(
                "descriptivePlotErrorBarType",
                descriptivePlotErrorBarType,
                options=list(
                    "ci",
                    "se"),
                default="ci")
            private$..descriptivePlotCiLevel <- jmvcore::OptionNumber$new(
                "descriptivePlotCiLevel",
                descriptivePlotCiLevel,
                min=50,
                max=99.9,
                default=95)
            private$..descriptivePlotYAxisLabel <- jmvcore::OptionString$new(
                "descriptivePlotYAxisLabel",
                descriptivePlotYAxisLabel,
                default="")
            private$..descriptivePlotErrorBarPooled <- jmvcore::OptionBool$new(
                "descriptivePlotErrorBarPooled",
                descriptivePlotErrorBarPooled,
                default=FALSE)
            private$..normalizeErrorBarsDescriptives <- jmvcore::OptionBool$new(
                "normalizeErrorBarsDescriptives",
                normalizeErrorBarsDescriptives,
                default=TRUE)
            private$..barPlotHorizontalAxis <- jmvcore::OptionVariable$new(
                "barPlotHorizontalAxis",
                barPlotHorizontalAxis,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"))
            private$..barPlotSeparatePlots <- jmvcore::OptionVariable$new(
                "barPlotSeparatePlots",
                barPlotSeparatePlots,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"))
            private$..barPlotErrorBars <- jmvcore::OptionBool$new(
                "barPlotErrorBars",
                barPlotErrorBars,
                default=TRUE)
            private$..barPlotErrorBarType <- jmvcore::OptionList$new(
                "barPlotErrorBarType",
                barPlotErrorBarType,
                options=list(
                    "ci",
                    "se"),
                default="ci")
            private$..barPlotCiInterval <- jmvcore::OptionNumber$new(
                "barPlotCiInterval",
                barPlotCiInterval,
                min=50,
                max=99.9,
                default=95)
            private$..barPlotHorizontalZeroFix <- jmvcore::OptionBool$new(
                "barPlotHorizontalZeroFix",
                barPlotHorizontalZeroFix,
                default=TRUE)
            private$..labelYAxisTwo <- jmvcore::OptionString$new(
                "labelYAxisTwo",
                labelYAxisTwo,
                default="")
            private$..usePooledStandErrorCITwo <- jmvcore::OptionBool$new(
                "usePooledStandErrorCITwo",
                usePooledStandErrorCITwo,
                default=FALSE)
            private$..normalizeErrorBarsBarplot <- jmvcore::OptionBool$new(
                "normalizeErrorBarsBarplot",
                normalizeErrorBarsBarplot,
                default=TRUE)
            private$..rainCloudHorizontalAxis <- jmvcore::OptionVariable$new(
                "rainCloudHorizontalAxis",
                rainCloudHorizontalAxis,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"))
            private$..rainCloudSeparatePlots <- jmvcore::OptionVariable$new(
                "rainCloudSeparatePlots",
                rainCloudSeparatePlots,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"))
            private$..rainCloudYAxisLabel <- jmvcore::OptionString$new(
                "rainCloudYAxisLabel",
                rainCloudYAxisLabel,
                default="")
            private$..marginalMeanTerms <- jmvcore::OptionVariables$new(
                "marginalMeanTerms",
                marginalMeanTerms,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"))
            private$..marginalMeanBootstrap <- jmvcore::OptionBool$new(
                "marginalMeanBootstrap",
                marginalMeanBootstrap,
                default=FALSE)
            private$..marginalMeanBootstrapSamples <- jmvcore::OptionInteger$new(
                "marginalMeanBootstrapSamples",
                marginalMeanBootstrapSamples,
                min=100,
                max=100000,
                default=1000)
            private$..marginalMeanComparedToZero <- jmvcore::OptionBool$new(
                "marginalMeanComparedToZero",
                marginalMeanComparedToZero,
                default=FALSE)
            private$..marginalMeanCiCorrection <- jmvcore::OptionList$new(
                "marginalMeanCiCorrection",
                marginalMeanCiCorrection,
                options=list(
                    "none",
                    "bonferroni",
                    "sidak"),
                default="none")
            private$..simpleMainEffectFactor <- jmvcore::OptionVariable$new(
                "simpleMainEffectFactor",
                simpleMainEffectFactor,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"))
            private$..simpleMainEffectModeratorFactorOne <- jmvcore::OptionVariable$new(
                "simpleMainEffectModeratorFactorOne",
                simpleMainEffectModeratorFactorOne,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"))
            private$..simpleMainEffectModeratorFactorTwo <- jmvcore::OptionVariable$new(
                "simpleMainEffectModeratorFactorTwo",
                simpleMainEffectModeratorFactorTwo,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"))
            private$..simpleMainEffectErrorTermPooled <- jmvcore::OptionBool$new(
                "simpleMainEffectErrorTermPooled",
                simpleMainEffectErrorTermPooled,
                default=FALSE)
            private$..friedmanWithinFactor <- jmvcore::OptionVariable$new(
                "friedmanWithinFactor",
                friedmanWithinFactor,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"))
            private$..friedmanBetweenFactor <- jmvcore::OptionVariable$new(
                "friedmanBetweenFactor",
                friedmanBetweenFactor,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"))
            private$..conoverTest <- jmvcore::OptionBool$new(
                "conoverTest",
                conoverTest,
                default=FALSE)
            private$..residualsSavedToData <- jmvcore::OptionBool$new(
                "residualsSavedToData",
                residualsSavedToData,
                default=FALSE)
            private$..residualsSavedToDataColumn <- jmvcore::OptionString$new(
                "residualsSavedToDataColumn",
                residualsSavedToDataColumn,
                default="residuals")
            private$..residualsSavedToDataType <- jmvcore::OptionList$new(
                "residualsSavedToDataType",
                residualsSavedToDataType,
                options=list(
                    "raw",
                    "standard",
                    "student"),
                default="raw")
            private$..predictionsSavedToData <- jmvcore::OptionBool$new(
                "predictionsSavedToData",
                predictionsSavedToData,
                default=FALSE)
            private$..predictionsSavedToDataColumn <- jmvcore::OptionString$new(
                "predictionsSavedToDataColumn",
                predictionsSavedToDataColumn,
                default="predictions")
            private$..residsOV <- jmvcore::OptionOutput$new(
                "residsOV")
            private$..predictOV <- jmvcore::OptionOutput$new(
                "predictOV")

            self$.addOption(private$..rmFactorSpec)
            self$.addOption(private$..rmFactorNames)
            self$.addOption(private$..rmFactorLevels)
            self$.addOption(private$..repeatedMeasuresCells)
            self$.addOption(private$..betweenSubjectFactors)
            self$.addOption(private$..covariates)
            self$.addOption(private$..descriptives)
            self$.addOption(private$..effectSizeEstimates)
            self$.addOption(private$..effectSizeOmegaSquared)
            self$.addOption(private$..effectSizePartialOmegaSquared)
            self$.addOption(private$..effectSizeEtaSquared)
            self$.addOption(private$..effectSizePartialEtaSquared)
            self$.addOption(private$..effectSizeGeneralEtaSquared)
            self$.addOption(private$..effectSizeCi)
            self$.addOption(private$..effectSizeCiLevel)
            self$.addOption(private$..vovkSellke)
            self$.addOption(private$..sumOfSquares)
            self$.addOption(private$..poolErrorTermFollowup)
            self$.addOption(private$..sphericityTests)
            self$.addOption(private$..sphericityCorrectionNone)
            self$.addOption(private$..sphericityCorrectionGreenhouseGeisser)
            self$.addOption(private$..sphericityCorrectionHuynhFeldt)
            self$.addOption(private$..homogeneityTests)
            self$.addOption(private$..qqPlot)
            self$.addOption(private$..qqPlotCi)
            self$.addOption(private$..qqPlotCiLevel)
            self$.addOption(private$..contrastType)
            self$.addOption(private$..contrastCi)
            self$.addOption(private$..contrastCiLevel)
            self$.addOption(private$..contrastEffectSize)
            self$.addOption(private$..restrictedSyntax)
            self$.addOption(private$..restrictedInterceptInclusion)
            self$.addOption(private$..restrictedAvailableCoefficients)
            self$.addOption(private$..restrictedModelSummaryForAllModels)
            self$.addOption(private$..restrictedMarginalMeanForAllModels)
            self$.addOption(private$..restrictedModelComparison)
            self$.addOption(private$..restrictedModelComparisonWeights)
            self$.addOption(private$..restrictedModelComparisonReference)
            self$.addOption(private$..restrictedModelComparisonMatrix)
            self$.addOption(private$..restrictedModelComparisonCoefficients)
            self$.addOption(private$..restrictedModelComparisonCoefficientsHighlight)
            self$.addOption(private$..restrictedHeterogeneityCorrection)
            self$.addOption(private$..restrictedBootstrap)
            self$.addOption(private$..restrictedBootstrapSamples)
            self$.addOption(private$..restrictedBootstrapCiLevel)
            self$.addOption(private$..restrictedMarginalMeanTerms)
            self$.addOption(private$..postHocTerms)
            self$.addOption(private$..postHocEffectSize)
            self$.addOption(private$..postHocConditionalTable)
            self$.addOption(private$..postHocCorrectionHolm)
            self$.addOption(private$..postHocCorrectionBonferroni)
            self$.addOption(private$..postHocCorrectionTukey)
            self$.addOption(private$..postHocCorrectionScheffe)
            self$.addOption(private$..postHocCorrectionFdr)
            self$.addOption(private$..postHocCi)
            self$.addOption(private$..postHocCiLevel)
            self$.addOption(private$..postHocSignificanceFlag)
            self$.addOption(private$..postHocLetterTable)
            self$.addOption(private$..postHocLetterAlpha)
            self$.addOption(private$..descriptivePlotHorizontalAxis)
            self$.addOption(private$..descriptivePlotSeparateLines)
            self$.addOption(private$..descriptivePlotSeparatePlot)
            self$.addOption(private$..descriptivePlotErrorBar)
            self$.addOption(private$..descriptivePlotErrorBarType)
            self$.addOption(private$..descriptivePlotCiLevel)
            self$.addOption(private$..descriptivePlotYAxisLabel)
            self$.addOption(private$..descriptivePlotErrorBarPooled)
            self$.addOption(private$..normalizeErrorBarsDescriptives)
            self$.addOption(private$..barPlotHorizontalAxis)
            self$.addOption(private$..barPlotSeparatePlots)
            self$.addOption(private$..barPlotErrorBars)
            self$.addOption(private$..barPlotErrorBarType)
            self$.addOption(private$..barPlotCiInterval)
            self$.addOption(private$..barPlotHorizontalZeroFix)
            self$.addOption(private$..labelYAxisTwo)
            self$.addOption(private$..usePooledStandErrorCITwo)
            self$.addOption(private$..normalizeErrorBarsBarplot)
            self$.addOption(private$..rainCloudHorizontalAxis)
            self$.addOption(private$..rainCloudSeparatePlots)
            self$.addOption(private$..rainCloudYAxisLabel)
            self$.addOption(private$..marginalMeanTerms)
            self$.addOption(private$..marginalMeanBootstrap)
            self$.addOption(private$..marginalMeanBootstrapSamples)
            self$.addOption(private$..marginalMeanComparedToZero)
            self$.addOption(private$..marginalMeanCiCorrection)
            self$.addOption(private$..simpleMainEffectFactor)
            self$.addOption(private$..simpleMainEffectModeratorFactorOne)
            self$.addOption(private$..simpleMainEffectModeratorFactorTwo)
            self$.addOption(private$..simpleMainEffectErrorTermPooled)
            self$.addOption(private$..friedmanWithinFactor)
            self$.addOption(private$..friedmanBetweenFactor)
            self$.addOption(private$..conoverTest)
            self$.addOption(private$..residualsSavedToData)
            self$.addOption(private$..residualsSavedToDataColumn)
            self$.addOption(private$..residualsSavedToDataType)
            self$.addOption(private$..predictionsSavedToData)
            self$.addOption(private$..predictionsSavedToDataColumn)
            self$.addOption(private$..residsOV)
            self$.addOption(private$..predictOV)
        }),
    active = list(
        rmFactorSpec = function() private$..rmFactorSpec$value,
        rmFactorNames = function() private$..rmFactorNames$value,
        rmFactorLevels = function() private$..rmFactorLevels$value,
        repeatedMeasuresCells = function() private$..repeatedMeasuresCells$value,
        betweenSubjectFactors = function() private$..betweenSubjectFactors$value,
        covariates = function() private$..covariates$value,
        descriptives = function() private$..descriptives$value,
        effectSizeEstimates = function() private$..effectSizeEstimates$value,
        effectSizeOmegaSquared = function() private$..effectSizeOmegaSquared$value,
        effectSizePartialOmegaSquared = function() private$..effectSizePartialOmegaSquared$value,
        effectSizeEtaSquared = function() private$..effectSizeEtaSquared$value,
        effectSizePartialEtaSquared = function() private$..effectSizePartialEtaSquared$value,
        effectSizeGeneralEtaSquared = function() private$..effectSizeGeneralEtaSquared$value,
        effectSizeCi = function() private$..effectSizeCi$value,
        effectSizeCiLevel = function() private$..effectSizeCiLevel$value,
        vovkSellke = function() private$..vovkSellke$value,
        sumOfSquares = function() private$..sumOfSquares$value,
        poolErrorTermFollowup = function() private$..poolErrorTermFollowup$value,
        sphericityTests = function() private$..sphericityTests$value,
        sphericityCorrectionNone = function() private$..sphericityCorrectionNone$value,
        sphericityCorrectionGreenhouseGeisser = function() private$..sphericityCorrectionGreenhouseGeisser$value,
        sphericityCorrectionHuynhFeldt = function() private$..sphericityCorrectionHuynhFeldt$value,
        homogeneityTests = function() private$..homogeneityTests$value,
        qqPlot = function() private$..qqPlot$value,
        qqPlotCi = function() private$..qqPlotCi$value,
        qqPlotCiLevel = function() private$..qqPlotCiLevel$value,
        contrastType = function() private$..contrastType$value,
        contrastCi = function() private$..contrastCi$value,
        contrastCiLevel = function() private$..contrastCiLevel$value,
        contrastEffectSize = function() private$..contrastEffectSize$value,
        restrictedSyntax = function() private$..restrictedSyntax$value,
        restrictedInterceptInclusion = function() private$..restrictedInterceptInclusion$value,
        restrictedAvailableCoefficients = function() private$..restrictedAvailableCoefficients$value,
        restrictedModelSummaryForAllModels = function() private$..restrictedModelSummaryForAllModels$value,
        restrictedMarginalMeanForAllModels = function() private$..restrictedMarginalMeanForAllModels$value,
        restrictedModelComparison = function() private$..restrictedModelComparison$value,
        restrictedModelComparisonWeights = function() private$..restrictedModelComparisonWeights$value,
        restrictedModelComparisonReference = function() private$..restrictedModelComparisonReference$value,
        restrictedModelComparisonMatrix = function() private$..restrictedModelComparisonMatrix$value,
        restrictedModelComparisonCoefficients = function() private$..restrictedModelComparisonCoefficients$value,
        restrictedModelComparisonCoefficientsHighlight = function() private$..restrictedModelComparisonCoefficientsHighlight$value,
        restrictedHeterogeneityCorrection = function() private$..restrictedHeterogeneityCorrection$value,
        restrictedBootstrap = function() private$..restrictedBootstrap$value,
        restrictedBootstrapSamples = function() private$..restrictedBootstrapSamples$value,
        restrictedBootstrapCiLevel = function() private$..restrictedBootstrapCiLevel$value,
        restrictedMarginalMeanTerms = function() private$..restrictedMarginalMeanTerms$value,
        postHocTerms = function() private$..postHocTerms$value,
        postHocEffectSize = function() private$..postHocEffectSize$value,
        postHocConditionalTable = function() private$..postHocConditionalTable$value,
        postHocCorrectionHolm = function() private$..postHocCorrectionHolm$value,
        postHocCorrectionBonferroni = function() private$..postHocCorrectionBonferroni$value,
        postHocCorrectionTukey = function() private$..postHocCorrectionTukey$value,
        postHocCorrectionScheffe = function() private$..postHocCorrectionScheffe$value,
        postHocCorrectionFdr = function() private$..postHocCorrectionFdr$value,
        postHocCi = function() private$..postHocCi$value,
        postHocCiLevel = function() private$..postHocCiLevel$value,
        postHocSignificanceFlag = function() private$..postHocSignificanceFlag$value,
        postHocLetterTable = function() private$..postHocLetterTable$value,
        postHocLetterAlpha = function() private$..postHocLetterAlpha$value,
        descriptivePlotHorizontalAxis = function() private$..descriptivePlotHorizontalAxis$value,
        descriptivePlotSeparateLines = function() private$..descriptivePlotSeparateLines$value,
        descriptivePlotSeparatePlot = function() private$..descriptivePlotSeparatePlot$value,
        descriptivePlotErrorBar = function() private$..descriptivePlotErrorBar$value,
        descriptivePlotErrorBarType = function() private$..descriptivePlotErrorBarType$value,
        descriptivePlotCiLevel = function() private$..descriptivePlotCiLevel$value,
        descriptivePlotYAxisLabel = function() private$..descriptivePlotYAxisLabel$value,
        descriptivePlotErrorBarPooled = function() private$..descriptivePlotErrorBarPooled$value,
        normalizeErrorBarsDescriptives = function() private$..normalizeErrorBarsDescriptives$value,
        barPlotHorizontalAxis = function() private$..barPlotHorizontalAxis$value,
        barPlotSeparatePlots = function() private$..barPlotSeparatePlots$value,
        barPlotErrorBars = function() private$..barPlotErrorBars$value,
        barPlotErrorBarType = function() private$..barPlotErrorBarType$value,
        barPlotCiInterval = function() private$..barPlotCiInterval$value,
        barPlotHorizontalZeroFix = function() private$..barPlotHorizontalZeroFix$value,
        labelYAxisTwo = function() private$..labelYAxisTwo$value,
        usePooledStandErrorCITwo = function() private$..usePooledStandErrorCITwo$value,
        normalizeErrorBarsBarplot = function() private$..normalizeErrorBarsBarplot$value,
        rainCloudHorizontalAxis = function() private$..rainCloudHorizontalAxis$value,
        rainCloudSeparatePlots = function() private$..rainCloudSeparatePlots$value,
        rainCloudYAxisLabel = function() private$..rainCloudYAxisLabel$value,
        marginalMeanTerms = function() private$..marginalMeanTerms$value,
        marginalMeanBootstrap = function() private$..marginalMeanBootstrap$value,
        marginalMeanBootstrapSamples = function() private$..marginalMeanBootstrapSamples$value,
        marginalMeanComparedToZero = function() private$..marginalMeanComparedToZero$value,
        marginalMeanCiCorrection = function() private$..marginalMeanCiCorrection$value,
        simpleMainEffectFactor = function() private$..simpleMainEffectFactor$value,
        simpleMainEffectModeratorFactorOne = function() private$..simpleMainEffectModeratorFactorOne$value,
        simpleMainEffectModeratorFactorTwo = function() private$..simpleMainEffectModeratorFactorTwo$value,
        simpleMainEffectErrorTermPooled = function() private$..simpleMainEffectErrorTermPooled$value,
        friedmanWithinFactor = function() private$..friedmanWithinFactor$value,
        friedmanBetweenFactor = function() private$..friedmanBetweenFactor$value,
        conoverTest = function() private$..conoverTest$value,
        residualsSavedToData = function() private$..residualsSavedToData$value,
        residualsSavedToDataColumn = function() private$..residualsSavedToDataColumn$value,
        residualsSavedToDataType = function() private$..residualsSavedToDataType$value,
        predictionsSavedToData = function() private$..predictionsSavedToData$value,
        predictionsSavedToDataColumn = function() private$..predictionsSavedToDataColumn$value,
        residsOV = function() private$..residsOV$value,
        predictOV = function() private$..predictOV$value),
    private = list(
        ..rmFactorSpec = NA,
        ..rmFactorNames = NA,
        ..rmFactorLevels = NA,
        ..repeatedMeasuresCells = NA,
        ..betweenSubjectFactors = NA,
        ..covariates = NA,
        ..descriptives = NA,
        ..effectSizeEstimates = NA,
        ..effectSizeOmegaSquared = NA,
        ..effectSizePartialOmegaSquared = NA,
        ..effectSizeEtaSquared = NA,
        ..effectSizePartialEtaSquared = NA,
        ..effectSizeGeneralEtaSquared = NA,
        ..effectSizeCi = NA,
        ..effectSizeCiLevel = NA,
        ..vovkSellke = NA,
        ..sumOfSquares = NA,
        ..poolErrorTermFollowup = NA,
        ..sphericityTests = NA,
        ..sphericityCorrectionNone = NA,
        ..sphericityCorrectionGreenhouseGeisser = NA,
        ..sphericityCorrectionHuynhFeldt = NA,
        ..homogeneityTests = NA,
        ..qqPlot = NA,
        ..qqPlotCi = NA,
        ..qqPlotCiLevel = NA,
        ..contrastType = NA,
        ..contrastCi = NA,
        ..contrastCiLevel = NA,
        ..contrastEffectSize = NA,
        ..restrictedSyntax = NA,
        ..restrictedInterceptInclusion = NA,
        ..restrictedAvailableCoefficients = NA,
        ..restrictedModelSummaryForAllModels = NA,
        ..restrictedMarginalMeanForAllModels = NA,
        ..restrictedModelComparison = NA,
        ..restrictedModelComparisonWeights = NA,
        ..restrictedModelComparisonReference = NA,
        ..restrictedModelComparisonMatrix = NA,
        ..restrictedModelComparisonCoefficients = NA,
        ..restrictedModelComparisonCoefficientsHighlight = NA,
        ..restrictedHeterogeneityCorrection = NA,
        ..restrictedBootstrap = NA,
        ..restrictedBootstrapSamples = NA,
        ..restrictedBootstrapCiLevel = NA,
        ..restrictedMarginalMeanTerms = NA,
        ..postHocTerms = NA,
        ..postHocEffectSize = NA,
        ..postHocConditionalTable = NA,
        ..postHocCorrectionHolm = NA,
        ..postHocCorrectionBonferroni = NA,
        ..postHocCorrectionTukey = NA,
        ..postHocCorrectionScheffe = NA,
        ..postHocCorrectionFdr = NA,
        ..postHocCi = NA,
        ..postHocCiLevel = NA,
        ..postHocSignificanceFlag = NA,
        ..postHocLetterTable = NA,
        ..postHocLetterAlpha = NA,
        ..descriptivePlotHorizontalAxis = NA,
        ..descriptivePlotSeparateLines = NA,
        ..descriptivePlotSeparatePlot = NA,
        ..descriptivePlotErrorBar = NA,
        ..descriptivePlotErrorBarType = NA,
        ..descriptivePlotCiLevel = NA,
        ..descriptivePlotYAxisLabel = NA,
        ..descriptivePlotErrorBarPooled = NA,
        ..normalizeErrorBarsDescriptives = NA,
        ..barPlotHorizontalAxis = NA,
        ..barPlotSeparatePlots = NA,
        ..barPlotErrorBars = NA,
        ..barPlotErrorBarType = NA,
        ..barPlotCiInterval = NA,
        ..barPlotHorizontalZeroFix = NA,
        ..labelYAxisTwo = NA,
        ..usePooledStandErrorCITwo = NA,
        ..normalizeErrorBarsBarplot = NA,
        ..rainCloudHorizontalAxis = NA,
        ..rainCloudSeparatePlots = NA,
        ..rainCloudYAxisLabel = NA,
        ..marginalMeanTerms = NA,
        ..marginalMeanBootstrap = NA,
        ..marginalMeanBootstrapSamples = NA,
        ..marginalMeanComparedToZero = NA,
        ..marginalMeanCiCorrection = NA,
        ..simpleMainEffectFactor = NA,
        ..simpleMainEffectModeratorFactorOne = NA,
        ..simpleMainEffectModeratorFactorTwo = NA,
        ..simpleMainEffectErrorTermPooled = NA,
        ..friedmanWithinFactor = NA,
        ..friedmanBetweenFactor = NA,
        ..conoverTest = NA,
        ..residualsSavedToData = NA,
        ..residualsSavedToDataColumn = NA,
        ..residualsSavedToDataType = NA,
        ..predictionsSavedToData = NA,
        ..predictionsSavedToDataColumn = NA,
        ..residsOV = NA,
        ..predictOV = NA)
)

enhancedRepeatedMeasuresAnovaResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "enhancedRepeatedMeasuresAnovaResults",
    inherit = jmvcore::Group,
    active = list(
        status = function() private$.items[["status"]],
        design = function() private$.items[["design"]],
        modelSummary = function() private$.items[["modelSummary"]],
        descriptivesSection = function() private$.items[["descriptivesSection"]],
        effectSizesSection = function() private$.items[["effectSizesSection"]],
        assumptionsSection = function() private$.items[["assumptionsSection"]],
        contrasts = function() private$.items[["contrasts"]],
        orderRestrictions = function() private$.items[["orderRestrictions"]],
        postHocSection = function() private$.items[["postHocSection"]],
        marginalMeansSection = function() private$.items[["marginalMeansSection"]],
        simpleEffectsSection = function() private$.items[["simpleEffectsSection"]],
        nonparametric = function() private$.items[["nonparametric"]],
        plots = function() private$.items[["plots"]],
        qqPlot = function() private$.items[["qqPlot"]],
        residualPlot = function() private$.items[["residualPlot"]],
        raincloudPlot = function() private$.items[["raincloudPlot"]],
        savedColumns = function() private$.items[["savedColumns"]],
        residsOV = function() private$.items[["residsOV"]],
        predictOV = function() private$.items[["predictOV"]],
        apa = function() private$.items[["apa"]],
        teaching = function() private$.items[["teaching"]],
        publication = function() private$.items[["publication"]],
        reproducibility = function() private$.items[["reproducibility"]],
        about = function() private$.items[["about"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="JASP Enhanced Repeated Measures ANOVA")
            self$add(jmvcore::Html$new(
                options=options,
                name="status",
                title="Implementation Status"))
            self$add(jmvcore::Html$new(
                options=options,
                name="design",
                title="Repeated Measures Design"))
            self$add(jmvcore::Html$new(
                options=options,
                name="modelSummary",
                title="Model Summary"))
            self$add(jmvcore::Html$new(
                options=options,
                name="descriptivesSection",
                title="Descriptive Statistics",
                visible="(descriptives)"))
            self$add(jmvcore::Html$new(
                options=options,
                name="effectSizesSection",
                title="Effect Sizes"))
            self$add(jmvcore::Html$new(
                options=options,
                name="assumptionsSection",
                title="Assumption Checks"))
            self$add(jmvcore::Html$new(
                options=options,
                name="contrasts",
                title="Repeated Measures Contrasts"))
            self$add(jmvcore::Html$new(
                options=options,
                name="orderRestrictions",
                title="Bayesian and Order Restricted Hypotheses"))
            self$add(jmvcore::Html$new(
                options=options,
                name="postHocSection",
                title="Post Hoc Tests"))
            self$add(jmvcore::Html$new(
                options=options,
                name="marginalMeansSection",
                title="Estimated Marginal Means"))
            self$add(jmvcore::Html$new(
                options=options,
                name="simpleEffectsSection",
                title="Simple Main Effects"))
            self$add(jmvcore::Html$new(
                options=options,
                name="nonparametric",
                title="Nonparametric Repeated Measures"))
            self$add(jmvcore::Html$new(
                options=options,
                name="plots",
                title="Plots"))
            self$add(jmvcore::Image$new(
                options=options,
                name="qqPlot",
                title="Q-Q Plot of Residuals",
                visible="(qqPlot)",
                width=520,
                height=420,
                renderFun=".qqPlot"))
            self$add(jmvcore::Image$new(
                options=options,
                name="residualPlot",
                title="Residual Plot",
                width=520,
                height=420,
                renderFun=".residualPlot"))
            self$add(jmvcore::Image$new(
                options=options,
                name="raincloudPlot",
                title="Raincloud Plot",
                width=640,
                height=440,
                renderFun=".raincloudPlot"))
            self$add(jmvcore::Html$new(
                options=options,
                name="savedColumns",
                title="Saved Dataset Columns"))
            self$add(jmvcore::Output$new(
                options=options,
                name="residsOV",
                title="Mean residuals",
                varTitle="RM mean residuals",
                varDescription="Subject-level mean residuals from JASP Enhanced Repeated Measures ANOVA",
                measureType="continuous",
                clearWith=list(
                    "repeatedMeasuresCells",
                    "betweenSubjectFactors",
                    "covariates")))
            self$add(jmvcore::Output$new(
                options=options,
                name="predictOV",
                title="Mean predicted values",
                varTitle="RM mean predicted values",
                varDescription="Subject-level mean predicted values from JASP Enhanced Repeated Measures ANOVA",
                measureType="continuous",
                clearWith=list(
                    "repeatedMeasuresCells",
                    "betweenSubjectFactors",
                    "covariates")))
            self$add(jmvcore::Html$new(
                options=options,
                name="apa",
                title="APA Reporting"))
            self$add(jmvcore::Html$new(
                options=options,
                name="teaching",
                title="Teaching Mode"))
            self$add(jmvcore::Html$new(
                options=options,
                name="publication",
                title="Publication Mode"))
            self$add(jmvcore::Html$new(
                options=options,
                name="reproducibility",
                title="Reproducibility"))
            self$add(jmvcore::Html$new(
                options=options,
                name="about",
                title="About and Citation"))}))

enhancedRepeatedMeasuresAnovaBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "enhancedRepeatedMeasuresAnovaBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "jaspEnhancedAnova",
                name = "enhancedRepeatedMeasuresAnova",
                version = c(0,1,0),
                options = options,
                results = enhancedRepeatedMeasuresAnovaResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'none')
        }))

#' JASP Enhanced Repeated Measures ANOVA
#'
#' Repeated Measures ANOVA matching the JASP RM ANOVA analysis, including 
#' multi-factor within-subject designs, sphericity corrections, post hoc 
#' tests, contrasts, plots, marginal means, simple effects, nonparametric 
#' alternatives, order-restricted hypotheses, and Bayesian model comparison.
#' 
#' @param data .
#' @param rmFactorSpec .
#' @param rmFactorNames .
#' @param rmFactorLevels .
#' @param repeatedMeasuresCells .
#' @param betweenSubjectFactors .
#' @param covariates .
#' @param descriptives .
#' @param effectSizeEstimates .
#' @param effectSizeOmegaSquared .
#' @param effectSizePartialOmegaSquared .
#' @param effectSizeEtaSquared .
#' @param effectSizePartialEtaSquared .
#' @param effectSizeGeneralEtaSquared .
#' @param effectSizeCi .
#' @param effectSizeCiLevel .
#' @param vovkSellke .
#' @param sumOfSquares .
#' @param poolErrorTermFollowup .
#' @param sphericityTests .
#' @param sphericityCorrectionNone .
#' @param sphericityCorrectionGreenhouseGeisser .
#' @param sphericityCorrectionHuynhFeldt .
#' @param homogeneityTests .
#' @param qqPlot .
#' @param qqPlotCi .
#' @param qqPlotCiLevel .
#' @param contrastType .
#' @param contrastCi .
#' @param contrastCiLevel .
#' @param contrastEffectSize .
#' @param restrictedSyntax .
#' @param restrictedInterceptInclusion .
#' @param restrictedAvailableCoefficients .
#' @param restrictedModelSummaryForAllModels .
#' @param restrictedMarginalMeanForAllModels .
#' @param restrictedModelComparison .
#' @param restrictedModelComparisonWeights .
#' @param restrictedModelComparisonReference .
#' @param restrictedModelComparisonMatrix .
#' @param restrictedModelComparisonCoefficients .
#' @param restrictedModelComparisonCoefficientsHighlight .
#' @param restrictedHeterogeneityCorrection .
#' @param restrictedBootstrap .
#' @param restrictedBootstrapSamples .
#' @param restrictedBootstrapCiLevel .
#' @param restrictedMarginalMeanTerms .
#' @param postHocTerms .
#' @param postHocEffectSize .
#' @param postHocConditionalTable .
#' @param postHocCorrectionHolm .
#' @param postHocCorrectionBonferroni .
#' @param postHocCorrectionTukey .
#' @param postHocCorrectionScheffe .
#' @param postHocCorrectionFdr .
#' @param postHocCi .
#' @param postHocCiLevel .
#' @param postHocSignificanceFlag .
#' @param postHocLetterTable .
#' @param postHocLetterAlpha .
#' @param descriptivePlotHorizontalAxis .
#' @param descriptivePlotSeparateLines .
#' @param descriptivePlotSeparatePlot .
#' @param descriptivePlotErrorBar .
#' @param descriptivePlotErrorBarType .
#' @param descriptivePlotCiLevel .
#' @param descriptivePlotYAxisLabel .
#' @param descriptivePlotErrorBarPooled .
#' @param normalizeErrorBarsDescriptives .
#' @param barPlotHorizontalAxis .
#' @param barPlotSeparatePlots .
#' @param barPlotErrorBars .
#' @param barPlotErrorBarType .
#' @param barPlotCiInterval .
#' @param barPlotHorizontalZeroFix .
#' @param labelYAxisTwo .
#' @param usePooledStandErrorCITwo .
#' @param normalizeErrorBarsBarplot .
#' @param rainCloudHorizontalAxis .
#' @param rainCloudSeparatePlots .
#' @param rainCloudYAxisLabel .
#' @param marginalMeanTerms .
#' @param marginalMeanBootstrap .
#' @param marginalMeanBootstrapSamples .
#' @param marginalMeanComparedToZero .
#' @param marginalMeanCiCorrection .
#' @param simpleMainEffectFactor .
#' @param simpleMainEffectModeratorFactorOne .
#' @param simpleMainEffectModeratorFactorTwo .
#' @param simpleMainEffectErrorTermPooled .
#' @param friedmanWithinFactor .
#' @param friedmanBetweenFactor .
#' @param conoverTest .
#' @param residualsSavedToData .
#' @param residualsSavedToDataColumn .
#' @param residualsSavedToDataType .
#' @param predictionsSavedToData .
#' @param predictionsSavedToDataColumn .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$status} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$design} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$modelSummary} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$descriptivesSection} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$effectSizesSection} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$assumptionsSection} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$contrasts} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$orderRestrictions} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$postHocSection} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$marginalMeansSection} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$simpleEffectsSection} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$nonparametric} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$plots} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$qqPlot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$residualPlot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$raincloudPlot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$savedColumns} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$residsOV} \tab \tab \tab \tab \tab an output \cr
#'   \code{results$predictOV} \tab \tab \tab \tab \tab an output \cr
#'   \code{results$apa} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$teaching} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$publication} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$reproducibility} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$about} \tab \tab \tab \tab \tab a html \cr
#' }
#'
#' @export
enhancedRepeatedMeasuresAnova <- function(
    data,
    rmFactorSpec = "",
    rmFactorNames = "RM Factor 1",
    rmFactorLevels = "Level 1, Level 2",
    repeatedMeasuresCells,
    betweenSubjectFactors,
    covariates,
    descriptives = FALSE,
    effectSizeEstimates = FALSE,
    effectSizeOmegaSquared = TRUE,
    effectSizePartialOmegaSquared = FALSE,
    effectSizeEtaSquared = FALSE,
    effectSizePartialEtaSquared = FALSE,
    effectSizeGeneralEtaSquared = FALSE,
    effectSizeCi = FALSE,
    effectSizeCiLevel = 95,
    vovkSellke = FALSE,
    sumOfSquares = "type3",
    poolErrorTermFollowup = FALSE,
    sphericityTests = TRUE,
    sphericityCorrectionNone = TRUE,
    sphericityCorrectionGreenhouseGeisser = FALSE,
    sphericityCorrectionHuynhFeldt = FALSE,
    homogeneityTests = FALSE,
    qqPlot = FALSE,
    qqPlotCi = FALSE,
    qqPlotCiLevel = 95,
    contrastType = "none",
    contrastCi = TRUE,
    contrastCiLevel = 95,
    contrastEffectSize = FALSE,
    restrictedSyntax = "",
    restrictedInterceptInclusion = FALSE,
    restrictedAvailableCoefficients = FALSE,
    restrictedModelSummaryForAllModels = FALSE,
    restrictedMarginalMeanForAllModels = FALSE,
    restrictedModelComparison = "complement",
    restrictedModelComparisonWeights = TRUE,
    restrictedModelComparisonReference = "complement",
    restrictedModelComparisonMatrix = FALSE,
    restrictedModelComparisonCoefficients = FALSE,
    restrictedModelComparisonCoefficientsHighlight = TRUE,
    restrictedHeterogeneityCorrection = "none",
    restrictedBootstrap = FALSE,
    restrictedBootstrapSamples = 1000,
    restrictedBootstrapCiLevel = 95,
    restrictedMarginalMeanTerms,
    postHocTerms,
    postHocEffectSize = FALSE,
    postHocConditionalTable = FALSE,
    postHocCorrectionHolm = TRUE,
    postHocCorrectionBonferroni = FALSE,
    postHocCorrectionTukey = FALSE,
    postHocCorrectionScheffe = FALSE,
    postHocCorrectionFdr = FALSE,
    postHocCi = TRUE,
    postHocCiLevel = 95,
    postHocSignificanceFlag = FALSE,
    postHocLetterTable = FALSE,
    postHocLetterAlpha = 0.05,
    descriptivePlotHorizontalAxis,
    descriptivePlotSeparateLines,
    descriptivePlotSeparatePlot,
    descriptivePlotErrorBar = TRUE,
    descriptivePlotErrorBarType = "ci",
    descriptivePlotCiLevel = 95,
    descriptivePlotYAxisLabel = "",
    descriptivePlotErrorBarPooled = FALSE,
    normalizeErrorBarsDescriptives = TRUE,
    barPlotHorizontalAxis,
    barPlotSeparatePlots,
    barPlotErrorBars = TRUE,
    barPlotErrorBarType = "ci",
    barPlotCiInterval = 95,
    barPlotHorizontalZeroFix = TRUE,
    labelYAxisTwo = "",
    usePooledStandErrorCITwo = FALSE,
    normalizeErrorBarsBarplot = TRUE,
    rainCloudHorizontalAxis,
    rainCloudSeparatePlots,
    rainCloudYAxisLabel = "",
    marginalMeanTerms,
    marginalMeanBootstrap = FALSE,
    marginalMeanBootstrapSamples = 1000,
    marginalMeanComparedToZero = FALSE,
    marginalMeanCiCorrection = "none",
    simpleMainEffectFactor,
    simpleMainEffectModeratorFactorOne,
    simpleMainEffectModeratorFactorTwo,
    simpleMainEffectErrorTermPooled = FALSE,
    friedmanWithinFactor,
    friedmanBetweenFactor,
    conoverTest = FALSE,
    residualsSavedToData = FALSE,
    residualsSavedToDataColumn = "residuals",
    residualsSavedToDataType = "raw",
    predictionsSavedToData = FALSE,
    predictionsSavedToDataColumn = "predictions") {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("enhancedRepeatedMeasuresAnova requires jmvcore to be installed (restart may be required)")

    if ( ! missing(repeatedMeasuresCells)) repeatedMeasuresCells <- jmvcore::resolveQuo(jmvcore::enquo(repeatedMeasuresCells))
    if ( ! missing(betweenSubjectFactors)) betweenSubjectFactors <- jmvcore::resolveQuo(jmvcore::enquo(betweenSubjectFactors))
    if ( ! missing(covariates)) covariates <- jmvcore::resolveQuo(jmvcore::enquo(covariates))
    if ( ! missing(restrictedMarginalMeanTerms)) restrictedMarginalMeanTerms <- jmvcore::resolveQuo(jmvcore::enquo(restrictedMarginalMeanTerms))
    if ( ! missing(postHocTerms)) postHocTerms <- jmvcore::resolveQuo(jmvcore::enquo(postHocTerms))
    if ( ! missing(descriptivePlotHorizontalAxis)) descriptivePlotHorizontalAxis <- jmvcore::resolveQuo(jmvcore::enquo(descriptivePlotHorizontalAxis))
    if ( ! missing(descriptivePlotSeparateLines)) descriptivePlotSeparateLines <- jmvcore::resolveQuo(jmvcore::enquo(descriptivePlotSeparateLines))
    if ( ! missing(descriptivePlotSeparatePlot)) descriptivePlotSeparatePlot <- jmvcore::resolveQuo(jmvcore::enquo(descriptivePlotSeparatePlot))
    if ( ! missing(barPlotHorizontalAxis)) barPlotHorizontalAxis <- jmvcore::resolveQuo(jmvcore::enquo(barPlotHorizontalAxis))
    if ( ! missing(barPlotSeparatePlots)) barPlotSeparatePlots <- jmvcore::resolveQuo(jmvcore::enquo(barPlotSeparatePlots))
    if ( ! missing(rainCloudHorizontalAxis)) rainCloudHorizontalAxis <- jmvcore::resolveQuo(jmvcore::enquo(rainCloudHorizontalAxis))
    if ( ! missing(rainCloudSeparatePlots)) rainCloudSeparatePlots <- jmvcore::resolveQuo(jmvcore::enquo(rainCloudSeparatePlots))
    if ( ! missing(marginalMeanTerms)) marginalMeanTerms <- jmvcore::resolveQuo(jmvcore::enquo(marginalMeanTerms))
    if ( ! missing(simpleMainEffectFactor)) simpleMainEffectFactor <- jmvcore::resolveQuo(jmvcore::enquo(simpleMainEffectFactor))
    if ( ! missing(simpleMainEffectModeratorFactorOne)) simpleMainEffectModeratorFactorOne <- jmvcore::resolveQuo(jmvcore::enquo(simpleMainEffectModeratorFactorOne))
    if ( ! missing(simpleMainEffectModeratorFactorTwo)) simpleMainEffectModeratorFactorTwo <- jmvcore::resolveQuo(jmvcore::enquo(simpleMainEffectModeratorFactorTwo))
    if ( ! missing(friedmanWithinFactor)) friedmanWithinFactor <- jmvcore::resolveQuo(jmvcore::enquo(friedmanWithinFactor))
    if ( ! missing(friedmanBetweenFactor)) friedmanBetweenFactor <- jmvcore::resolveQuo(jmvcore::enquo(friedmanBetweenFactor))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(repeatedMeasuresCells), repeatedMeasuresCells, NULL),
            `if`( ! missing(betweenSubjectFactors), betweenSubjectFactors, NULL),
            `if`( ! missing(covariates), covariates, NULL),
            `if`( ! missing(restrictedMarginalMeanTerms), restrictedMarginalMeanTerms, NULL),
            `if`( ! missing(postHocTerms), postHocTerms, NULL),
            `if`( ! missing(descriptivePlotHorizontalAxis), descriptivePlotHorizontalAxis, NULL),
            `if`( ! missing(descriptivePlotSeparateLines), descriptivePlotSeparateLines, NULL),
            `if`( ! missing(descriptivePlotSeparatePlot), descriptivePlotSeparatePlot, NULL),
            `if`( ! missing(barPlotHorizontalAxis), barPlotHorizontalAxis, NULL),
            `if`( ! missing(barPlotSeparatePlots), barPlotSeparatePlots, NULL),
            `if`( ! missing(rainCloudHorizontalAxis), rainCloudHorizontalAxis, NULL),
            `if`( ! missing(rainCloudSeparatePlots), rainCloudSeparatePlots, NULL),
            `if`( ! missing(marginalMeanTerms), marginalMeanTerms, NULL),
            `if`( ! missing(simpleMainEffectFactor), simpleMainEffectFactor, NULL),
            `if`( ! missing(simpleMainEffectModeratorFactorOne), simpleMainEffectModeratorFactorOne, NULL),
            `if`( ! missing(simpleMainEffectModeratorFactorTwo), simpleMainEffectModeratorFactorTwo, NULL),
            `if`( ! missing(friedmanWithinFactor), friedmanWithinFactor, NULL),
            `if`( ! missing(friedmanBetweenFactor), friedmanBetweenFactor, NULL))

    for (v in betweenSubjectFactors) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    for (v in restrictedMarginalMeanTerms) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    for (v in postHocTerms) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    for (v in descriptivePlotHorizontalAxis) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    for (v in descriptivePlotSeparateLines) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    for (v in descriptivePlotSeparatePlot) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    for (v in barPlotHorizontalAxis) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    for (v in barPlotSeparatePlots) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    for (v in rainCloudHorizontalAxis) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    for (v in rainCloudSeparatePlots) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    for (v in marginalMeanTerms) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    for (v in simpleMainEffectFactor) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    for (v in simpleMainEffectModeratorFactorOne) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    for (v in simpleMainEffectModeratorFactorTwo) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    for (v in friedmanWithinFactor) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    for (v in friedmanBetweenFactor) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])

    options <- enhancedRepeatedMeasuresAnovaOptions$new(
        rmFactorSpec = rmFactorSpec,
        rmFactorNames = rmFactorNames,
        rmFactorLevels = rmFactorLevels,
        repeatedMeasuresCells = repeatedMeasuresCells,
        betweenSubjectFactors = betweenSubjectFactors,
        covariates = covariates,
        descriptives = descriptives,
        effectSizeEstimates = effectSizeEstimates,
        effectSizeOmegaSquared = effectSizeOmegaSquared,
        effectSizePartialOmegaSquared = effectSizePartialOmegaSquared,
        effectSizeEtaSquared = effectSizeEtaSquared,
        effectSizePartialEtaSquared = effectSizePartialEtaSquared,
        effectSizeGeneralEtaSquared = effectSizeGeneralEtaSquared,
        effectSizeCi = effectSizeCi,
        effectSizeCiLevel = effectSizeCiLevel,
        vovkSellke = vovkSellke,
        sumOfSquares = sumOfSquares,
        poolErrorTermFollowup = poolErrorTermFollowup,
        sphericityTests = sphericityTests,
        sphericityCorrectionNone = sphericityCorrectionNone,
        sphericityCorrectionGreenhouseGeisser = sphericityCorrectionGreenhouseGeisser,
        sphericityCorrectionHuynhFeldt = sphericityCorrectionHuynhFeldt,
        homogeneityTests = homogeneityTests,
        qqPlot = qqPlot,
        qqPlotCi = qqPlotCi,
        qqPlotCiLevel = qqPlotCiLevel,
        contrastType = contrastType,
        contrastCi = contrastCi,
        contrastCiLevel = contrastCiLevel,
        contrastEffectSize = contrastEffectSize,
        restrictedSyntax = restrictedSyntax,
        restrictedInterceptInclusion = restrictedInterceptInclusion,
        restrictedAvailableCoefficients = restrictedAvailableCoefficients,
        restrictedModelSummaryForAllModels = restrictedModelSummaryForAllModels,
        restrictedMarginalMeanForAllModels = restrictedMarginalMeanForAllModels,
        restrictedModelComparison = restrictedModelComparison,
        restrictedModelComparisonWeights = restrictedModelComparisonWeights,
        restrictedModelComparisonReference = restrictedModelComparisonReference,
        restrictedModelComparisonMatrix = restrictedModelComparisonMatrix,
        restrictedModelComparisonCoefficients = restrictedModelComparisonCoefficients,
        restrictedModelComparisonCoefficientsHighlight = restrictedModelComparisonCoefficientsHighlight,
        restrictedHeterogeneityCorrection = restrictedHeterogeneityCorrection,
        restrictedBootstrap = restrictedBootstrap,
        restrictedBootstrapSamples = restrictedBootstrapSamples,
        restrictedBootstrapCiLevel = restrictedBootstrapCiLevel,
        restrictedMarginalMeanTerms = restrictedMarginalMeanTerms,
        postHocTerms = postHocTerms,
        postHocEffectSize = postHocEffectSize,
        postHocConditionalTable = postHocConditionalTable,
        postHocCorrectionHolm = postHocCorrectionHolm,
        postHocCorrectionBonferroni = postHocCorrectionBonferroni,
        postHocCorrectionTukey = postHocCorrectionTukey,
        postHocCorrectionScheffe = postHocCorrectionScheffe,
        postHocCorrectionFdr = postHocCorrectionFdr,
        postHocCi = postHocCi,
        postHocCiLevel = postHocCiLevel,
        postHocSignificanceFlag = postHocSignificanceFlag,
        postHocLetterTable = postHocLetterTable,
        postHocLetterAlpha = postHocLetterAlpha,
        descriptivePlotHorizontalAxis = descriptivePlotHorizontalAxis,
        descriptivePlotSeparateLines = descriptivePlotSeparateLines,
        descriptivePlotSeparatePlot = descriptivePlotSeparatePlot,
        descriptivePlotErrorBar = descriptivePlotErrorBar,
        descriptivePlotErrorBarType = descriptivePlotErrorBarType,
        descriptivePlotCiLevel = descriptivePlotCiLevel,
        descriptivePlotYAxisLabel = descriptivePlotYAxisLabel,
        descriptivePlotErrorBarPooled = descriptivePlotErrorBarPooled,
        normalizeErrorBarsDescriptives = normalizeErrorBarsDescriptives,
        barPlotHorizontalAxis = barPlotHorizontalAxis,
        barPlotSeparatePlots = barPlotSeparatePlots,
        barPlotErrorBars = barPlotErrorBars,
        barPlotErrorBarType = barPlotErrorBarType,
        barPlotCiInterval = barPlotCiInterval,
        barPlotHorizontalZeroFix = barPlotHorizontalZeroFix,
        labelYAxisTwo = labelYAxisTwo,
        usePooledStandErrorCITwo = usePooledStandErrorCITwo,
        normalizeErrorBarsBarplot = normalizeErrorBarsBarplot,
        rainCloudHorizontalAxis = rainCloudHorizontalAxis,
        rainCloudSeparatePlots = rainCloudSeparatePlots,
        rainCloudYAxisLabel = rainCloudYAxisLabel,
        marginalMeanTerms = marginalMeanTerms,
        marginalMeanBootstrap = marginalMeanBootstrap,
        marginalMeanBootstrapSamples = marginalMeanBootstrapSamples,
        marginalMeanComparedToZero = marginalMeanComparedToZero,
        marginalMeanCiCorrection = marginalMeanCiCorrection,
        simpleMainEffectFactor = simpleMainEffectFactor,
        simpleMainEffectModeratorFactorOne = simpleMainEffectModeratorFactorOne,
        simpleMainEffectModeratorFactorTwo = simpleMainEffectModeratorFactorTwo,
        simpleMainEffectErrorTermPooled = simpleMainEffectErrorTermPooled,
        friedmanWithinFactor = friedmanWithinFactor,
        friedmanBetweenFactor = friedmanBetweenFactor,
        conoverTest = conoverTest,
        residualsSavedToData = residualsSavedToData,
        residualsSavedToDataColumn = residualsSavedToDataColumn,
        residualsSavedToDataType = residualsSavedToDataType,
        predictionsSavedToData = predictionsSavedToData,
        predictionsSavedToDataColumn = predictionsSavedToDataColumn)

    analysis <- enhancedRepeatedMeasuresAnovaClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

